#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Extract stimulus timing from step-01 *_Stim_Analog.tif files.

Default layout:
  input : DATA_ROOT/01_oir_to_tif/
  output: DATA_ROOT/02_stim_map/

This step is conservative by default: existing complete outputs are skipped,
and overwrite removes only files generated by this step inside the selected
step-02 output folder.
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import re
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tifffile as tiff
from matplotlib import rcParams
from matplotlib.patches import Wedge


LOGGER = logging.getLogger("generate_stim_map")

rcParams["font.sans-serif"] = ["Arial Unicode MS", "SimHei", "DejaVu Sans"]
rcParams["axes.unicode_minus"] = False

STEP_NAME = "02_stim_map"
DEFAULT_NOSTIM_REL_THRESH = 0.05
DEFAULT_PROTOCOL_MATCH_TOLERANCE_SEC = 120.0
OUTPUT_SUFFIXES = (
    "_brightness_trace.csv",
    "_stim_trace.png",
    "_stim_trace.pdf",
    "_stim_schematic.png",
    "_stim_schematic.pdf",
    "_stim_pulse_trace.png",
    "_stim_pulse_trace.pdf",
    "_stim_event_slices.png",
    "_stim_event_slices.pdf",
    "_stim_map.csv",
    "_stim_events.csv",
    "_stim_pulse_events.csv",
    "_stim_block_diagnostics.csv",
)


@dataclass(frozen=True)
class TrialInput:
    trial_id: str
    rel_parent: Path
    input_dir: Path
    stim_path: Path
    metadata_path: Path
    raw_stim_dir: Path | None = None
    raw_oir_path: Path | None = None


@dataclass(frozen=True)
class AnalogTrace:
    trace: np.ndarray
    source: str
    raw_z_index: int | None = None
    raw_z_strategy: str = ""
    dt_scale: float = 1.0


@dataclass(frozen=True)
class StimProtocol:
    run_id: str
    timestamp_log_path: Path
    stim_map_path: Path | None
    config_path: Path | None
    config: dict
    stim_mode: str
    expected_duration_sec: float | None
    estimated_trial_start: datetime | None
    events: list[dict]


@dataclass
class RunSummary:
    found: int = 0
    processed: int = 0
    skipped: int = 0
    failed: int = 0


def configure_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def default_output_root(data_root: Path) -> Path:
    return data_root


def default_input_root(data_root: Path, output_root: Path) -> Path:
    return output_root / "01_oir_to_tif"


def default_stim_log_root(data_root: Path) -> Path | None:
    candidates = [
        data_root / "00_stim_logs_raw",
        data_root / "test_dataset_motor_rotation",
        data_root / "stim_logs",
        data_root / "motor_rotation",
    ]
    for candidate in candidates:
        if candidate.exists() and any(candidate.rglob("timestamp_log_*.csv")):
            return candidate
    return None


def step_output_root(output_root: Path) -> Path:
    return output_root / STEP_NAME


def trial_output_dir(step_root: Path, trial: TrialInput) -> Path:
    if str(trial.rel_parent) in ("", "."):
        return step_root / trial.trial_id
    return step_root / trial.rel_parent / trial.trial_id


def output_paths(out_dir: Path, trial_id: str) -> dict[str, Path]:
    return {
        "brightness_trace": out_dir / f"{trial_id}_brightness_trace.csv",
        "stim_trace": out_dir / f"{trial_id}_stim_trace.png",
        "stim_trace_pdf": out_dir / f"{trial_id}_stim_trace.pdf",
        "stim_schematic": out_dir / f"{trial_id}_stim_schematic.png",
        "stim_schematic_pdf": out_dir / f"{trial_id}_stim_schematic.pdf",
        "stim_pulse_trace": out_dir / f"{trial_id}_stim_pulse_trace.png",
        "stim_pulse_trace_pdf": out_dir / f"{trial_id}_stim_pulse_trace.pdf",
        "stim_event_slices": out_dir / f"{trial_id}_stim_event_slices.png",
        "stim_event_slices_pdf": out_dir / f"{trial_id}_stim_event_slices.pdf",
        "stim_map": out_dir / f"{trial_id}_stim_map.csv",
        "stim_events": out_dir / f"{trial_id}_stim_events.csv",
        "stim_pulse_events": out_dir / f"{trial_id}_stim_pulse_events.csv",
        "stim_block_diagnostics": out_dir / f"{trial_id}_stim_block_diagnostics.csv",
        "stim_event_slices_dir": out_dir / f"{trial_id}_stim_event_slices",
    }


def required_outputs_done(out_dir: Path, trial_id: str) -> bool:
    paths = output_paths(out_dir, trial_id)
    required = [
        paths["brightness_trace"],
        paths["stim_trace"],
        paths["stim_trace_pdf"],
        paths["stim_map"],
        paths["stim_events"],
        paths["stim_pulse_events"],
    ]
    if csv_has_data_rows(paths["stim_events"]):
        required.extend([paths["stim_schematic"], paths["stim_schematic_pdf"]])
    if csv_has_data_rows(paths["stim_pulse_events"]):
        required.extend(
            [
                paths["stim_schematic"],
                paths["stim_schematic_pdf"],
                paths["stim_pulse_trace"],
                paths["stim_pulse_trace_pdf"],
            ]
        )
    return all(path.exists() and path.stat().st_size > 0 for path in required)


def csv_has_data_rows(path: Path) -> bool:
    if not path.exists() or path.stat().st_size == 0:
        return False
    try:
        with path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.reader(handle)
            next(reader, None)
            return next(reader, None) is not None
    except OSError:
        return False


def clean_step_outputs(out_dir: Path, trial_id: str) -> int:
    removed = 0
    if not out_dir.exists():
        return removed

    paths = output_paths(out_dir, trial_id)
    slices_dir = paths["stim_event_slices_dir"]
    if slices_dir.exists() and slices_dir.is_dir():
        for child in sorted(slices_dir.glob("*")):
            if child.is_file():
                child.unlink()
                removed += 1
        slices_dir.rmdir()
        LOGGER.info("已删除旧的 step-02 文件夹：%s", slices_dir)

    for suffix in OUTPUT_SUFFIXES:
        path = out_dir / f"{trial_id}{suffix}"
        if path.exists() and path.is_file():
            path.unlink()
            removed += 1
            LOGGER.info("已删除旧的 step-02 文件：%s", path)
    return removed


def find_first_existing(folder: Path, patterns: tuple[str, ...]) -> Path | None:
    for pattern in patterns:
        matches = sorted(folder.glob(pattern))
        if matches:
            return matches[0]
    return None


def find_raw_stim_dir(input_dir: Path, trial_id: str) -> Path | None:
    candidates = [
        input_dir / f"{trial_id}_Stim_Analog_Raw",
    ]
    candidates.extend(sorted(input_dir.glob("*_Stim_Analog_Raw")))
    for candidate in candidates:
        if candidate.exists() and candidate.is_dir() and (candidate / "manifest.json").exists():
            return candidate
    return None


def parse_run_id(path: Path, prefix: str, suffix: str) -> str | None:
    name = path.name
    if not name.startswith(prefix) or not name.endswith(suffix):
        return None
    return name[len(prefix) : -len(suffix)]


def read_json_if_exists(path: Path | None) -> dict:
    if path is None or not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def expected_duration_from_config(config: dict) -> float | None:
    if not config:
        return None
    if config.get("computed_stim_total_ms") is not None:
        return float(config["computed_stim_total_ms"]) / 1000.0

    mcu_config = config.get("mcu_config", {})
    stim_mode = str(mcu_config.get("stim_mode", "")).lower()
    if stim_mode == "sustain" and mcu_config.get("stim_on_ms") is not None:
        return float(mcu_config["stim_on_ms"]) / 1000.0
    if stim_mode == "pulse":
        pulse_count = int(mcu_config.get("pulse_count", 0) or 0)
        pulse_on_ms = float(mcu_config.get("pulse_on_ms", 0) or 0)
        pulse_off_ms = float(mcu_config.get("pulse_off_ms", 0) or 0)
        if pulse_count > 0:
            total_ms = pulse_count * pulse_on_ms + max(0, pulse_count - 1) * pulse_off_ms
            return total_ms / 1000.0
    return None


def read_protocol_events(timestamp_log_path: Path, stim_map_path: Path | None, expected_duration_sec: float | None) -> list[dict]:
    timestamp_df = pd.read_csv(timestamp_log_path)
    angle_by_index: dict[int, object] = {}
    if stim_map_path is not None and stim_map_path.exists():
        stim_map_df = pd.read_csv(stim_map_path)
        if {"stim_id", "angle"}.issubset(stim_map_df.columns):
            angle_by_index = {
                int(row["stim_id"]): row["angle"]
                for _, row in stim_map_df.iterrows()
                if pd.notna(row.get("stim_id"))
            }

    events: list[dict] = []
    for _, row in timestamp_df.iterrows():
        event_name = str(row.get("event", ""))
        if not event_name.startswith("STIM_"):
            continue

        stim_index_raw = row.get("mcu_stim_index")
        if pd.isna(stim_index_raw):
            match = re.search(r"(\d+)$", event_name)
            stim_index = int(match.group(1)) if match else len(events) + 1
        else:
            stim_index = int(stim_index_raw)

        mcu_offset_ms = row.get("mcu_offset_ms")
        mcu_onset_sec = float(mcu_offset_ms) / 1000.0 if pd.notna(mcu_offset_ms) else np.nan
        angle = row.get("angle")
        if pd.isna(angle):
            angle = angle_by_index.get(stim_index, "")

        event = {
            "stim_index": stim_index,
            "mcu_onset_sec": round(float(mcu_onset_sec), 3) if pd.notna(mcu_onset_sec) else "",
            "mcu_offset_sec": round(float(mcu_onset_sec + expected_duration_sec), 3)
            if pd.notna(mcu_onset_sec) and expected_duration_sec is not None
            else "",
            "duration_sec": round(float(expected_duration_sec), 3)
            if expected_duration_sec is not None
            else "",
            "pol_angle": angle if pd.notna(angle) else "",
            "host_timestamp": row.get("host_timestamp", ""),
        }
        events.append(event)

    return events


def parse_host_datetime(value: object) -> datetime | None:
    if value is None or pd.isna(value):
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return datetime.fromisoformat(text)
    except ValueError:
        return None


def estimate_protocol_trial_start(events: list[dict]) -> datetime | None:
    for event in events:
        host_time = parse_host_datetime(event.get("host_timestamp"))
        mcu_onset_sec = event.get("mcu_onset_sec")
        if host_time is None or mcu_onset_sec == "":
            continue
        return host_time - timedelta(seconds=float(mcu_onset_sec))
    return None


def discover_stim_protocols(stim_log_root: Path | None) -> list[StimProtocol]:
    if stim_log_root is None:
        return []
    if not stim_log_root.exists():
        LOGGER.warning("刺激日志根目录不存在：%s", stim_log_root)
        return []

    protocols: list[StimProtocol] = []
    for timestamp_log_path in sorted(stim_log_root.rglob("timestamp_log_*.csv")):
        run_id = parse_run_id(timestamp_log_path, "timestamp_log_", ".csv")
        if not run_id:
            continue

        log_dir = timestamp_log_path.parent
        config_path = log_dir / f"experiment_config_{run_id}.json"
        stim_map_path = log_dir / f"stim_map_{run_id}.csv"
        config = read_json_if_exists(config_path if config_path.exists() else None)
        mcu_config = config.get("mcu_config", {})
        stim_mode = str(mcu_config.get("stim_mode", "") or "")
        expected_duration_sec = expected_duration_from_config(config)
        events = read_protocol_events(
            timestamp_log_path=timestamp_log_path,
            stim_map_path=stim_map_path if stim_map_path.exists() else None,
            expected_duration_sec=expected_duration_sec,
        )
        estimated_trial_start = estimate_protocol_trial_start(events)
        protocols.append(
            StimProtocol(
                run_id=run_id,
                timestamp_log_path=timestamp_log_path,
                stim_map_path=stim_map_path if stim_map_path.exists() else None,
                config_path=config_path if config_path.exists() else None,
                config=config,
                stim_mode=stim_mode,
                expected_duration_sec=expected_duration_sec,
                estimated_trial_start=estimated_trial_start,
                events=events,
            )
        )

    LOGGER.info("找到 %d 个刺激协议日志。", len(protocols))
    return protocols


def nearest_stim_block(
    stim_blocks: list[dict],
    target_onset_sec: float | None,
    max_delta_sec: float = 3.0,
) -> dict | None:
    if target_onset_sec is None or not stim_blocks:
        return None

    best_block = min(
        stim_blocks,
        key=lambda block: abs(float(block["start_time_sec"]) - target_onset_sec),
    )
    delta = abs(float(best_block["start_time_sec"]) - target_onset_sec)
    return best_block if delta <= max_delta_sec else None


def pulse_count_from_protocol(protocol: StimProtocol | None) -> int:
    if protocol is None or protocol.stim_mode.lower() != "pulse":
        return 0
    mcu_config = protocol.config.get("mcu_config", {})
    return int(mcu_config.get("pulse_count", 0) or 0)


def packet_blocks_from_pulse_blocks(stim_blocks: list[dict], protocol: StimProtocol | None) -> list[dict]:
    pulse_count = pulse_count_from_protocol(protocol)
    if protocol is None or pulse_count <= 1:
        return stim_blocks
    expected_pulses = len(protocol.events) * pulse_count
    if len(stim_blocks) < expected_pulses:
        return stim_blocks

    packet_blocks: list[dict] = []
    for stim_idx, protocol_event in enumerate(protocol.events):
        first = stim_idx * pulse_count
        packet = stim_blocks[first : first + pulse_count]
        if len(packet) != pulse_count:
            continue
        start_time = float(packet[0].get("start_time_sec", 0))
        end_time = float(packet[-1].get("end_time_sec", start_time))
        packet_blocks.append(
            {
                "stim_index": protocol_event.get("stim_index", stim_idx + 1),
                "start_frame": packet[0].get("start_frame", ""),
                "end_frame": packet[-1].get("end_frame", ""),
                "start_time_sec": round(start_time, 3),
                "end_time_sec": round(end_time, 3),
                "duration_sec": round(end_time - start_time, 3),
                "pol_angle": protocol_event.get("pol_angle", ""),
            }
        )
    return packet_blocks if packet_blocks else stim_blocks


def protocol_event_time_in_trial(
    event: dict,
    trial_start_estimate: datetime | None,
) -> tuple[float | None, float | None]:
    if trial_start_estimate is None:
        return None, None

    host_time = parse_host_datetime(event.get("host_timestamp"))
    if host_time is None:
        return None, None

    onset_sec = (host_time - trial_start_estimate).total_seconds()
    duration = _as_float_or_none(event.get("duration_sec"))
    if duration is None:
        mcu_onset = _as_float_or_none(event.get("mcu_onset_sec"))
        mcu_offset = _as_float_or_none(event.get("mcu_offset_sec"))
        if mcu_onset is not None and mcu_offset is not None:
            duration = mcu_offset - mcu_onset
    if duration is None or duration <= 0:
        return round(float(onset_sec), 3), None
    return round(float(onset_sec), 3), round(float(onset_sec + duration), 3)


def match_stim_protocol(
    protocols: list[StimProtocol],
    trial_start_estimate: datetime | None,
) -> tuple[StimProtocol | None, float | None]:
    if trial_start_estimate is None or not protocols:
        return None, None

    best_protocol: StimProtocol | None = None
    best_delta_sec: float | None = None

    for protocol in protocols:
        if protocol.estimated_trial_start is None:
            continue
        delta_sec = abs((trial_start_estimate - protocol.estimated_trial_start).total_seconds())
        if best_delta_sec is None or delta_sec < best_delta_sec:
            best_delta_sec = delta_sec
            best_protocol = protocol

    if best_delta_sec is None or best_delta_sec > DEFAULT_PROTOCOL_MATCH_TOLERANCE_SEC:
        return None, None
    return best_protocol, best_delta_sec


def find_raw_oir_path(data_root: Path, trial_id: str, rel_parent: Path) -> Path | None:
    candidate_paths = [
        data_root / "00_original_files" / rel_parent / trial_id / f"{trial_id}.oir",
        data_root / "00_original_files" / trial_id / f"{trial_id}.oir",
        data_root / rel_parent / trial_id / f"{trial_id}.oir",
        data_root / trial_id / f"{trial_id}.oir",
        data_root / f"{trial_id}.oir",
    ]
    for path in candidate_paths:
        if path.exists():
            return path
    return None


def discover_trials(input_root: Path, data_root: Path) -> list[TrialInput]:
    trials: list[TrialInput] = []
    for stim_path in sorted(input_root.rglob("*_Stim_Analog.tif")):
        input_dir = stim_path.parent
        metadata_path = find_first_existing(input_dir, ("*_metadata.json",))
        if metadata_path is None:
            LOGGER.warning("由于缺少 metadata JSON，跳过 %s。", input_dir)
            continue

        trial_id = input_dir.name
        rel_parent = input_dir.parent.relative_to(input_root)
        trials.append(
            TrialInput(
                trial_id=trial_id,
                rel_parent=rel_parent,
                input_dir=input_dir,
                stim_path=stim_path,
                metadata_path=metadata_path,
                raw_stim_dir=find_raw_stim_dir(input_dir, trial_id),
                raw_oir_path=find_raw_oir_path(data_root, trial_id, rel_parent),
            )
        )
    return trials


def estimate_trial_start_from_raw_file(raw_oir_path: Path | None, timepoints: int, dt: float) -> datetime | None:
    if raw_oir_path is None or not raw_oir_path.exists() or timepoints <= 0 or dt <= 0:
        return None
    modified_time = datetime.fromtimestamp(raw_oir_path.stat().st_mtime)
    return modified_time - timedelta(seconds=timepoints * dt)


def estimate_trial_start_from_metadata(meta: dict, raw_oir_path: Path | None, timepoints: int, dt: float) -> datetime | None:
    acquisition_time = meta.get("acquisition", {}).get("start_time")
    parsed_time = parse_host_datetime(acquisition_time)
    if parsed_time is not None:
        # The stimulus controller logs are local timestamps without timezone.
        # Drop timezone info after parsing so both clocks can be compared.
        return parsed_time.replace(tzinfo=None)

    return estimate_trial_start_from_raw_file(raw_oir_path, timepoints, dt)


def estimate_precise_boundary(
    brightness_trace: np.ndarray,
    frame_idx: int,
    baseline: float,
    peak: float,
    is_start: bool,
) -> float:
    if frame_idx < 0 or frame_idx >= len(brightness_trace):
        return 0.0 if is_start else 1.0

    brightness = brightness_trace[frame_idx]
    if peak - baseline > 0:
        ratio = (brightness - baseline) / (peak - baseline)
        ratio = np.clip(ratio, 0.0, 1.0)
    else:
        ratio = 0.5

    return float(1.0 - ratio) if is_start else float(ratio)


def analyze_stim_blocks(
    brightness_trace: np.ndarray,
    dt: float,
    dynamic_thresh: float,
    baseline: float,
    peak: float,
) -> list[dict]:
    is_stim_on = brightness_trace > dynamic_thresh
    stim_indices = np.where(is_stim_on)[0]
    if len(stim_indices) == 0:
        return []

    diffs = np.diff(stim_indices)
    split_points = np.where(diffs > 1)[0] + 1
    blocks = np.split(stim_indices, split_points)

    stim_blocks: list[dict] = []
    for block_idx, block in enumerate(blocks):
        if len(block) == 0:
            continue

        start_frame = int(block[0])
        end_frame = int(block[-1])
        start_offset = estimate_precise_boundary(
            brightness_trace, start_frame, baseline, peak, is_start=True
        )
        end_offset = estimate_precise_boundary(
            brightness_trace, end_frame, baseline, peak, is_start=False
        )
        start_time = (start_frame + start_offset) * dt
        end_time = (end_frame + end_offset) * dt

        stim_blocks.append(
            {
                "stim_index": block_idx + 1,
                "start_frame": start_frame,
                "end_frame": end_frame,
                "start_time_sec": round(float(start_time), 3),
                "end_time_sec": round(float(end_time), 3),
                "duration_sec": round(float(end_time - start_time), 3),
            }
        )
    return stim_blocks


def raw_stim_manifest(raw_stim_dir: Path | None) -> dict:
    if raw_stim_dir is None:
        return {}
    manifest_path = raw_stim_dir / "manifest.json"
    if not manifest_path.exists():
        return {}
    with manifest_path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def raw_stim_complete(raw_stim_dir: Path | None) -> bool:
    manifest = raw_stim_manifest(raw_stim_dir)
    if not manifest or raw_stim_dir is None:
        return False
    expected = int(manifest.get("file_count", manifest.get("frame_count", 0)) or 0)
    if expected <= 0:
        return False
    return len(sorted(raw_stim_dir.glob("t*.tif"))) >= expected


def read_projected_analog_trace(stim_path: Path) -> AnalogTrace:
    with tiff.TiffFile(stim_path) as tif:
        images = tif.asarray()
    if images.ndim == 2:
        trace = np.asarray([float(np.nanmean(images))], dtype=float)
    elif images.ndim == 3:
        trace = np.nanmean(images, axis=(1, 2)).astype(float)
    else:
        trace = np.nanmean(images.reshape((images.shape[0], -1)), axis=1).astype(float)
    return AnalogTrace(trace=trace, source="projected_stim_analog_tif")


def read_raw_analog_trace(raw_stim_dir: Path, raw_z_strategy: str) -> AnalogTrace:
    manifest = raw_stim_manifest(raw_stim_dir)
    files = sorted(raw_stim_dir.glob("t*.tif"))
    expected = int(manifest.get("file_count", manifest.get("frame_count", len(files))) or len(files))
    if expected > 0 and len(files) < expected:
        raise RuntimeError(
            "Raw stim analog folder is incomplete: {} has {} tif files, expected {}".format(
                raw_stim_dir, len(files), expected
            )
        )
    if not files:
        raise RuntimeError("Raw stim analog folder has no t*.tif files: {}".format(raw_stim_dir))

    per_z_rows: list[np.ndarray] = []
    for index, path in enumerate(files):
        if index == 0 or (index + 1) == len(files) or (index + 1) % 200 == 0:
            LOGGER.debug("正在读取原始刺激模拟信号 %s（%d/%d）", path.name, index + 1, len(files))
        arr = tiff.imread(path)
        if arr.ndim == 2:
            z_means = np.asarray([float(np.nanmean(arr))], dtype=float)
        else:
            z_means = np.nanmean(arr.reshape((arr.shape[0], -1)), axis=1).astype(float)
        per_z_rows.append(z_means)

    per_z = np.vstack(per_z_rows)
    if raw_z_strategy == "planes":
        trace = per_z.reshape(-1)
        n_z = int(per_z.shape[1]) if per_z.ndim == 2 and per_z.shape[1] > 0 else 1
        return AnalogTrace(
            trace=trace,
            source="raw_stim_analog_z_plane_sequence",
            raw_z_strategy=raw_z_strategy,
            dt_scale=1.0 / float(n_z),
        )

    if raw_z_strategy == "mean":
        trace = np.nanmean(per_z, axis=1)
        return AnalogTrace(trace=trace, source="raw_stim_analog_z_mean", raw_z_strategy=raw_z_strategy)

    if raw_z_strategy == "max":
        trace = np.nanmax(per_z, axis=1)
        return AnalogTrace(trace=trace, source="raw_stim_analog_z_max", raw_z_strategy=raw_z_strategy)

    z_ranges = np.nanpercentile(per_z, 95, axis=0) - np.nanpercentile(per_z, 5, axis=0)
    z_index = int(np.nanargmax(z_ranges))
    trace = per_z[:, z_index]
    return AnalogTrace(
        trace=trace,
        source="raw_stim_analog_best_z",
        raw_z_index=z_index + 1,
        raw_z_strategy="max-range",
    )


def read_analog_trace(trial: TrialInput, analog_source: str, raw_z_strategy: str) -> AnalogTrace:
    if analog_source in ("auto", "raw") and raw_stim_complete(trial.raw_stim_dir):
        assert trial.raw_stim_dir is not None
        return read_raw_analog_trace(trial.raw_stim_dir, raw_z_strategy)

    if analog_source == "raw":
        raise RuntimeError("Raw stim analog requested but complete raw folder is missing for {}".format(trial.trial_id))

    return read_projected_analog_trace(trial.stim_path)


def make_time_windows(total_time: float, preferred_window_sec: float) -> list[tuple[float, float]]:
    total_time = max(float(total_time), 1.0)
    preferred_window_sec = max(float(preferred_window_sec), 1.0)
    if total_time <= preferred_window_sec:
        return [(0.0, total_time)]
    windows = []
    start = 0.0
    while start < total_time:
        end = min(total_time, start + preferred_window_sec)
        windows.append((start, end))
        start = end
    return windows


def choose_plot_window_sec(total_time: float, n_events: int, has_pulses: bool) -> float:
    if total_time <= 180:
        return max(total_time, 1.0)
    if has_pulses:
        return 60.0
    if n_events >= 12:
        return 90.0
    return 120.0


def single_axis_fig_width(total_time: float) -> float:
    return min(max(14.0, float(total_time) / 18.0), 48.0)


def angle_sort_key(angle: str) -> tuple[int, float | str]:
    value = _as_float_or_none(angle)
    if value is None:
        return (1, str(angle))
    return (0, value)


def angle_to_color(angle: object):
    value = _as_float_or_none(angle)
    if value is None:
        return "0.45"
    normalized = (value % 180.0) / 180.0
    if abs(value % 180.0) < 1e-9 and value > 0:
        normalized = 1.0
    return plt.get_cmap("hsv")(0.72 * normalized)


def angle_label(angle: object) -> str:
    value = _as_float_or_none(angle)
    if value is None:
        return str(angle)
    if abs(value - round(value)) < 1e-6:
        return f"{int(round(value))} deg"
    return f"{value:g} deg"


def collect_angle_handles(angles: set[str]):
    handles = []
    for angle in sorted(angles, key=angle_sort_key):
        handles.append(
            plt.Line2D([0], [0], color=angle_to_color(angle), lw=6, label=angle_label(angle))
        )
    return handles


def add_angle_color_wheel(ax) -> None:
    inset = ax.inset_axes([0.86, 1.03, 0.12, 0.22])
    n_steps = 36
    for idx in range(n_steps):
        start = 180.0 * idx / n_steps
        end = 180.0 * (idx + 1) / n_steps
        mid_angle = (start + end) / 2.0
        inset.add_patch(
            Wedge(
                (0.0, 0.0),
                1.0,
                start,
                end,
                width=0.28,
                facecolor=angle_to_color(mid_angle),
                edgecolor="none",
            )
        )
    inset.text(1.05, -0.04, "0", ha="left", va="center", fontsize=7)
    inset.text(0.0, 1.08, "90", ha="center", va="bottom", fontsize=7)
    inset.text(-1.05, -0.04, "180", ha="right", va="center", fontsize=7)
    inset.text(0.0, -0.34, "angle color", ha="center", va="top", fontsize=7)
    inset.set_xlim(-1.15, 1.15)
    inset.set_ylim(-0.38, 1.15)
    inset.set_aspect("equal")
    inset.axis("off")


def add_figure_notes(ax, lines: list[str]) -> None:
    lines = [line for line in lines if str(line).strip()]
    if not lines:
        return
    ax.text(
        0.012,
        0.965,
        "\n".join(lines),
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=8,
        linespacing=1.25,
        bbox={
            "boxstyle": "round,pad=0.28",
            "facecolor": "white",
            "edgecolor": "0.75",
            "alpha": 0.82,
            "linewidth": 0.6,
        },
    )


def save_figure_with_pdf(fig, output_path: Path, dpi: int = 150) -> None:
    """
    Save a quick-preview PNG and an editable vector PDF for the same figure.
    """
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
    fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")


def plot_stim_trace(
    brightness_trace: np.ndarray,
    time_axis: np.ndarray,
    stim_blocks: list[dict],
    dynamic_thresh: float | None,
    trial_id: str,
    output_path: Path,
    has_pulses: bool = False,
    figure_notes: list[str] | None = None,
) -> None:
    total_time = time_axis[-1] if len(time_axis) > 0 else 1
    fig, ax = plt.subplots(1, 1, figsize=(single_axis_fig_width(total_time), 4.2))

    y_min = float(np.nanmin(brightness_trace)) if len(brightness_trace) else 0.0
    y_max = float(np.nanmax(brightness_trace)) if len(brightness_trace) else 1.0
    y_pad = max((y_max - y_min) * 0.08, 1.0)

    local_time = time_axis
    local_trace = brightness_trace
    max_points = 20000
    if len(local_trace) > max_points:
        downsample_factor = len(local_trace) // max_points + 1
        local_time = local_time[::downsample_factor]
        local_trace = local_trace[::downsample_factor]
    ax.plot(local_time, local_trace, "b-", linewidth=0.8, label="Voltage/brightness", alpha=0.75)

    if dynamic_thresh is not None:
        ax.axhline(
            y=dynamic_thresh,
            color="r",
            linestyle="--",
            linewidth=0.9,
            label=f"Threshold ({dynamic_thresh:.1f})",
        )

    angle_values: set[str] = set()
    for block in stim_blocks:
        block_start = _as_float_or_none(block.get("start_time_sec"))
        block_end = _as_float_or_none(block.get("end_time_sec"))
        if block_start is None or block_end is None:
            continue
        angle = str(block.get("pol_angle", ""))
        if angle != "":
            angle_values.add(angle)
        ax.axvspan(
            block_start,
            block_end,
            alpha=0.22,
            color=angle_to_color(angle),
        )
        if len(stim_blocks) <= 80:
            mid_t = (block_start + block_end) / 2
            ax.text(mid_t, y_max + y_pad * 0.15, f"#{block['stim_index']}", ha="center", va="bottom", fontsize=7)

    ax.set_xlim(0, total_time)
    ax.set_ylim(y_min - y_pad, y_max + y_pad)
    ax.set_xlabel("Time (sec)", fontsize=11)
    ax.set_ylabel("a.u.", fontsize=9)
    ax.set_title(f"Stimulus Voltage Trace - {trial_id}", fontsize=12, fontweight="bold")
    ax.grid(True, alpha=0.25)
    add_figure_notes(ax, figure_notes or [])

    handles, labels = ax.get_legend_handles_labels()
    angle_handles = collect_angle_handles(angle_values)
    if angle_handles:
        handles.extend(angle_handles)
        add_angle_color_wheel(ax)
    if handles:
        ax.legend(
            handles=handles,
            loc="lower left",
            bbox_to_anchor=(0.0, 1.02),
            fontsize=8,
            ncol=min(8, len(handles)),
            frameon=False,
        )
    plt.tight_layout()
    try:
        save_figure_with_pdf(fig, output_path, dpi=150)
    finally:
        plt.close(fig)


def _as_float_or_none(value: object) -> float | None:
    if value is None or value == "":
        return None
    try:
        if pd.isna(value):
            return None
    except TypeError:
        pass
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def plot_stim_schematic(
    events_rows: list[dict],
    pulse_events_rows: list[dict],
    stim_blocks: list[dict],
    trial_id: str,
    output_path: Path,
    figure_notes: list[str] | None = None,
) -> None:
    if not events_rows and not pulse_events_rows and not stim_blocks:
        return

    has_pulses = bool(pulse_events_rows)
    onset_values = []
    offset_values = []
    for row in events_rows:
        onset_values.append(_as_float_or_none(row.get("start_time_sec")))
        offset_values.append(_as_float_or_none(row.get("end_time_sec")))
    for row in pulse_events_rows:
        onset_values.append(_as_float_or_none(row.get("analog_anchored_pulse_onset_sec")))
        offset_values.append(_as_float_or_none(row.get("analog_anchored_pulse_offset_sec")))
    for block in stim_blocks:
        onset_values.append(_as_float_or_none(block.get("start_time_sec")))
        offset_values.append(_as_float_or_none(block.get("end_time_sec")))

    onset_values = [value for value in onset_values if value is not None]
    offset_values = [value for value in offset_values if value is not None]
    if not onset_values or not offset_values:
        return

    total_time = max(offset_values) + 5.0
    fig_height = 3.5 if has_pulses else 2.7
    fig, ax = plt.subplots(1, 1, figsize=(single_axis_fig_width(total_time), fig_height))
    angle_values: set[str] = set()

    for row in events_rows:
        onset = _as_float_or_none(row.get("start_time_sec"))
        offset = _as_float_or_none(row.get("end_time_sec"))
        if onset is None or offset is None or offset <= onset:
            continue
        angle = str(row.get("pol_angle", ""))
        if angle != "":
            angle_values.add(angle)
        ax.broken_barh(
            [(onset, offset - onset)],
            (0.12, 0.24),
            facecolors=angle_to_color(angle),
            edgecolors=angle_to_color(angle),
            alpha=0.58,
        )
        stim_index = row.get("stim_index", "")
        mid = (onset + offset) / 2
        if stim_index != "" and len(events_rows) <= 80:
            ax.text(mid, 0.42, str(stim_index), ha="center", va="bottom", fontsize=7)

    for row in pulse_events_rows:
        onset = _as_float_or_none(row.get("analog_anchored_pulse_onset_sec"))
        offset = _as_float_or_none(row.get("analog_anchored_pulse_offset_sec"))
        if onset is None or offset is None or offset <= onset:
            continue
        angle = str(row.get("pol_angle", ""))
        if angle != "":
            angle_values.add(angle)
        ax.broken_barh(
            [(onset, offset - onset)],
            (0.58, 0.30),
            facecolors=angle_to_color(angle),
            edgecolors=angle_to_color(angle),
            alpha=0.95,
            linewidth=0.45,
        )

    if has_pulses:
        labeled_stims: set[int] = set()
        for row in pulse_events_rows:
            if int(row.get("pulse_index", 0) or 0) != 1:
                continue
            stim_index = int(row.get("stim_index", 0) or 0)
            if stim_index in labeled_stims:
                continue
            onset = _as_float_or_none(row.get("analog_anchored_pulse_onset_sec"))
            if onset is None:
                continue
            labeled_stims.add(stim_index)
            if len(labeled_stims) <= 80:
                ax.text(onset, 0.93, str(stim_index), ha="center", va="bottom", fontsize=7, rotation=90)

    ax.set_xlim(0, total_time)
    ax.set_ylim(0, 1.05)
    if has_pulses:
        ax.set_yticks([0.24, 0.73])
        ax.set_yticklabels(["packet", "flash"])
    else:
        ax.set_yticks([0.24])
        ax.set_yticklabels(["stim"])
    ax.set_xlabel("Time (sec)", fontsize=11)
    ax.set_title(f"Stimulus Timing Schematic - {trial_id}", fontsize=12, fontweight="bold")
    ax.grid(True, axis="x", alpha=0.25)
    add_figure_notes(ax, figure_notes or [])

    angle_handles = collect_angle_handles(angle_values)
    if angle_handles:
        add_angle_color_wheel(ax)
        ax.legend(
            handles=angle_handles,
            loc="lower left",
            bbox_to_anchor=(0.0, 1.02),
            fontsize=8,
            ncol=min(8, len(angle_handles)),
            frameon=False,
        )

    plt.tight_layout()
    try:
        save_figure_with_pdf(fig, output_path, dpi=150)
    finally:
        plt.close(fig)


def build_summary_row(
    trial_id: str,
    protocol: StimProtocol | None,
    protocol_match_delta_sec: float | None,
    trial_start_estimate: datetime | None,
    events_rows: list[dict],
    analog_trace: AnalogTrace,
) -> dict:
    protocol_events = protocol.events if protocol is not None else []
    summary_row = {
        "trialID": trial_id,
        "stim_type": protocol.stim_mode if protocol is not None else "nostim",
        "number_of_stim": len(protocol_events),
        "initial_delay_sec": "",
        "avg_duration_sec": "",
        "avg_interval_sec": "",
        "strength": "",
        "pol_angle_list": "",
        "stim_protocol_id": protocol.run_id if protocol is not None else "",
        "stim_protocol_file": str(protocol.timestamp_log_path) if protocol is not None else "",
        "stim_protocol_dir": str(protocol.timestamp_log_path.parent) if protocol is not None else "",
        "trial_start_estimate": trial_start_estimate.isoformat() if trial_start_estimate is not None else "",
        "protocol_trial_start_estimate": (
            protocol.estimated_trial_start.isoformat()
            if protocol is not None and protocol.estimated_trial_start is not None
            else ""
        ),
        "protocol_match_delta_sec": round(float(protocol_match_delta_sec), 3)
        if protocol_match_delta_sec is not None
        else "",
        "analog_source": analog_trace.source,
        "raw_z_index": analog_trace.raw_z_index if analog_trace.raw_z_index is not None else "",
        "raw_z_strategy": analog_trace.raw_z_strategy,
    }

    if protocol is None or not protocol_events:
        return summary_row

    onsets = [_as_float_or_none(row.get("start_time_sec")) for row in events_rows]
    offsets = [_as_float_or_none(row.get("end_time_sec")) for row in events_rows]
    onsets = [onset for onset in onsets if onset is not None]
    offsets = [offset for offset in offsets if offset is not None]
    if onsets:
        summary_row["initial_delay_sec"] = round(float(onsets[0]), 2)
    if onsets and offsets and len(offsets) == len(onsets):
        durations = [offset - onset for onset, offset in zip(onsets, offsets)]
        summary_row["avg_duration_sec"] = round(float(np.mean(durations)), 2)
    if len(onsets) > 1:
        intervals = [onsets[i + 1] - onsets[i] for i in range(len(onsets) - 1)]
        summary_row["avg_interval_sec"] = round(float(np.mean(intervals)), 2)
    angles = [str(event.get("pol_angle", "")) for event in protocol_events if event.get("pol_angle", "") != ""]
    summary_row["pol_angle_list"] = ";".join(angles)

    return summary_row


def _format_ms_as_sec(value: object) -> str:
    if value is None or value == "":
        return ""
    try:
        return "{:.3g}s".format(float(value) / 1000.0)
    except (TypeError, ValueError):
        return ""


def compact_angle_summary(events: list[dict]) -> str:
    angles = [str(event.get("pol_angle", "")) for event in events if event.get("pol_angle", "") != ""]
    if not angles:
        return ""
    unique_angles = sorted(set(angles), key=angle_sort_key)
    if len(unique_angles) <= 8:
        return "angles: " + ", ".join([angle_label(angle) for angle in unique_angles])
    return "angles: {} unique".format(len(unique_angles))


def build_figure_notes(
    protocol: StimProtocol | None,
    protocol_match_delta_sec: float | None,
    analog_trace: AnalogTrace,
) -> list[str]:
    analog_label = analog_trace.source
    if analog_trace.raw_z_strategy:
        analog_label = "{} ({})".format(analog_label, analog_trace.raw_z_strategy)
    if analog_trace.raw_z_index is not None:
        analog_label = "{} z{}".format(analog_label, analog_trace.raw_z_index)

    if protocol is None:
        return [
            "protocol: none matched",
            "stim: nostim",
            "analog: {}".format(analog_label),
        ]

    mcu_config = protocol.config.get("mcu_config", {})
    mode = str(protocol.stim_mode or "").lower()
    lines = [
        "protocol: {}".format(protocol.run_id),
        "mode: {} | n={}".format(mode or "unknown", len(protocol.events)),
    ]
    if protocol_match_delta_sec is not None:
        lines.append("clock match: {:.1f}s".format(float(protocol_match_delta_sec)))

    initial_delay = _format_ms_as_sec(mcu_config.get("initial_delay_ms"))
    interval = _format_ms_as_sec(mcu_config.get("interval_ms"))
    if initial_delay or interval:
        lines.append("delay: {} | interval: {}".format(initial_delay or "NA", interval or "NA"))

    if mode == "pulse":
        lines.append(
            "pulse: {} x {} on / {} off".format(
                int(mcu_config.get("pulse_count", 0) or 0),
                _format_ms_as_sec(mcu_config.get("pulse_on_ms")) or "NA",
                _format_ms_as_sec(mcu_config.get("pulse_off_ms")) or "NA",
            )
        )
        if protocol.expected_duration_sec is not None:
            lines.append("packet: {:.3g}s".format(float(protocol.expected_duration_sec)))
    elif mode == "sustain":
        lines.append("stim on: {}".format(_format_ms_as_sec(mcu_config.get("stim_on_ms")) or "NA"))
    elif protocol.expected_duration_sec is not None:
        lines.append("duration: {:.3g}s".format(float(protocol.expected_duration_sec)))

    angle_summary = compact_angle_summary(protocol.events)
    if angle_summary:
        lines.append(angle_summary)
    lines.append("analog: {}".format(analog_label))
    return lines


def build_events_rows(
    trial_id: str,
    stim_blocks: list[dict],
    protocol: StimProtocol | None,
    protocol_match_delta_sec: float | None,
    trial_start_estimate: datetime | None,
) -> list[dict]:
    rows: list[dict] = []
    if protocol is not None:
        for idx, protocol_event in enumerate(protocol.events):
            onset_sec, offset_sec = protocol_event_time_in_trial(protocol_event, trial_start_estimate)
            analog_block = stim_blocks[idx] if idx < len(stim_blocks) else nearest_stim_block(stim_blocks, onset_sec)
            analog_start = analog_block.get("start_time_sec", "") if analog_block else ""
            analog_end = analog_block.get("end_time_sec", "") if analog_block else ""
            if analog_start != "":
                event_start = analog_start
                event_end = analog_end
                duration_sec = (
                    round(float(analog_end) - float(analog_start), 3)
                    if analog_end != ""
                    else protocol_event.get("duration_sec", "")
                )
                timing_source = "analog_voltage_with_protocol_metadata"
            else:
                if onset_sec is None:
                    continue
                event_start = onset_sec
                event_end = offset_sec if offset_sec is not None else ""
                duration_sec = (
                    round(float(offset_sec - onset_sec), 3)
                    if offset_sec is not None
                    else protocol_event.get("duration_sec", "")
                )
                timing_source = "protocol_absolute_time_fallback"
            analog_delta = (
                round(float(analog_start) - float(onset_sec), 3)
                if analog_start != "" and onset_sec is not None
                else ""
            )
            rows.append(
                {
                    "trialID": trial_id,
                    "stim_index": protocol_event.get("stim_index", len(rows) + 1),
                    "start_time_sec": event_start,
                    "end_time_sec": event_end,
                    "duration_sec": duration_sec,
                    "stim_type": protocol.stim_mode,
                    "pol_angle": protocol_event.get("pol_angle", ""),
                    "strength": "",
                    "stim_protocol_id": protocol.run_id,
                    "mcu_onset_sec": protocol_event.get("mcu_onset_sec", ""),
                    "mcu_offset_sec": protocol_event.get("mcu_offset_sec", ""),
                    "host_timestamp": protocol_event.get("host_timestamp", ""),
                    "timing_source": timing_source,
                    "protocol_match_delta_sec": round(float(protocol_match_delta_sec), 3)
                    if protocol_match_delta_sec is not None
                    else "",
                    "analog_detected_start_time_sec": analog_start,
                    "analog_detected_end_time_sec": analog_end,
                    "analog_minus_protocol_onset_sec": analog_delta,
                }
            )
        return rows

    return rows


def build_pulse_events_rows(
    trial_id: str,
    stim_blocks: list[dict],
    protocol: StimProtocol | None,
    trial_start_estimate: datetime | None,
) -> list[dict]:
    if protocol is None or protocol.stim_mode.lower() != "pulse":
        return []

    mcu_config = protocol.config.get("mcu_config", {})
    pulse_count = int(mcu_config.get("pulse_count", 0) or 0)
    pulse_on_sec = float(mcu_config.get("pulse_on_ms", 0) or 0) / 1000.0
    pulse_off_sec = float(mcu_config.get("pulse_off_ms", 0) or 0) / 1000.0
    if pulse_count <= 0 or pulse_on_sec <= 0:
        return []

    rows: list[dict] = []
    pulse_period_sec = pulse_on_sec + pulse_off_sec
    for stim_idx, protocol_event in enumerate(protocol.events):
        packet_onset_sec, _ = protocol_event_time_in_trial(protocol_event, trial_start_estimate)
        analog_block = nearest_stim_block(stim_blocks, packet_onset_sec)
        analog_packet_start = analog_block.get("start_time_sec", "") if analog_block else ""
        mcu_packet_start = protocol_event.get("mcu_onset_sec", "")
        angle = protocol_event.get("pol_angle", "")

        for pulse_index in range(1, pulse_count + 1):
            offset_sec = (pulse_index - 1) * pulse_period_sec
            mcu_onset = round(float(mcu_packet_start) + offset_sec, 6) if mcu_packet_start != "" else ""
            mcu_offset = round(float(mcu_packet_start) + offset_sec + pulse_on_sec, 6) if mcu_packet_start != "" else ""
            protocol_onset = round(float(packet_onset_sec) + offset_sec, 6) if packet_onset_sec is not None else ""
            protocol_offset = (
                round(float(packet_onset_sec) + offset_sec + pulse_on_sec, 6)
                if packet_onset_sec is not None
                else ""
            )
            analog_onset = round(float(analog_packet_start) + offset_sec, 6) if analog_packet_start != "" else ""
            analog_offset = round(float(analog_packet_start) + offset_sec + pulse_on_sec, 6) if analog_packet_start != "" else ""
            pulse_block_index = stim_idx * pulse_count + pulse_index - 1
            pulse_block = stim_blocks[pulse_block_index] if pulse_block_index < len(stim_blocks) else None
            if pulse_block is not None:
                analog_onset = pulse_block.get("start_time_sec", analog_onset)
                analog_offset = pulse_block.get("end_time_sec", analog_offset)
                timing_source = "analog_voltage_flash_with_protocol_metadata"
            else:
                timing_source = (
                    "protocol_absolute_time_plus_analog_packet"
                    if analog_packet_start != ""
                    else "protocol_absolute_time"
                )

            rows.append(
                {
                    "trialID": trial_id,
                    "stim_index": protocol_event.get("stim_index", ""),
                    "pulse_index": pulse_index,
                    "stim_type": "pulse",
                    "pol_angle": angle,
                    "stim_protocol_id": protocol.run_id,
                    "mcu_packet_onset_sec": mcu_packet_start,
                    "protocol_packet_onset_sec": packet_onset_sec if packet_onset_sec is not None else "",
                    "analog_packet_onset_sec": analog_packet_start,
                    "pulse_on_sec": round(pulse_on_sec, 6),
                    "pulse_off_sec": round(pulse_off_sec, 6),
                    "mcu_pulse_onset_sec": mcu_onset,
                    "mcu_pulse_offset_sec": mcu_offset,
                    "protocol_pulse_onset_sec": protocol_onset,
                    "protocol_pulse_offset_sec": protocol_offset,
                    "analog_anchored_pulse_onset_sec": analog_onset if analog_onset != "" else protocol_onset,
                    "analog_anchored_pulse_offset_sec": analog_offset if analog_offset != "" else protocol_offset,
                    "timing_source": timing_source,
                }
            )
    return rows


def block_judgement_rows(
    stim_blocks: list[dict],
    events_rows: list[dict],
    tolerance_sec: float = 0.35,
) -> list[dict]:
    rows: list[dict] = []
    for block_index, block in enumerate(stim_blocks, start=1):
        start = _as_float_or_none(block.get("start_time_sec"))
        end = _as_float_or_none(block.get("end_time_sec"))
        duration = _as_float_or_none(block.get("duration_sec"))
        matched_event = None
        for event in events_rows:
            analog_start = _as_float_or_none(event.get("analog_detected_start_time_sec"))
            analog_end = _as_float_or_none(event.get("analog_detected_end_time_sec"))
            event_start = _as_float_or_none(event.get("start_time_sec"))
            if start is None:
                continue
            if analog_start is not None and abs(analog_start - start) <= tolerance_sec:
                matched_event = event
                break
            if analog_end is not None and end is not None and abs(analog_end - end) <= tolerance_sec:
                matched_event = event
                break
            if event_start is not None and abs(event_start - start) <= tolerance_sec:
                matched_event = event
                break
        rows.append(
            {
                "block_index": block_index,
                "stim_index_detected": block.get("stim_index", block_index),
                "start_time_sec": block.get("start_time_sec", ""),
                "end_time_sec": block.get("end_time_sec", ""),
                "duration_sec": block.get("duration_sec", duration if duration is not None else ""),
                "final_is_stim_event": 1 if matched_event is not None else 0,
                "matched_final_stim_index": matched_event.get("stim_index", "") if matched_event is not None else "",
                "matched_timing_source": matched_event.get("timing_source", "") if matched_event is not None else "",
                "matched_stim_type": matched_event.get("stim_type", "") if matched_event is not None else "",
                "matched_pol_angle": matched_event.get("pol_angle", "") if matched_event is not None else "",
            }
        )
    return rows


def trial_date_label(trial_id: str, summary_row: dict | None = None) -> str:
    if summary_row is not None:
        trial_start_estimate = str(summary_row.get("trial_start_estimate", "") or "").strip()
        if trial_start_estimate:
            return trial_start_estimate[:10].replace("-", "")
    match = re.match(r"^(\d{8})", trial_id)
    if match:
        return match.group(1)
    return ""


def build_block_summary_rows(
    summaries: list[dict],
    block_rows_by_trial: dict[str, list[dict]],
) -> list[dict]:
    summary_by_trial = {str(row.get("trialID", "")): row for row in summaries}
    rows: list[dict] = []
    for trial_id in sorted(block_rows_by_trial):
        block_rows = block_rows_by_trial[trial_id]
        summary_row = summary_by_trial.get(trial_id, {})
        n_blocks_total = len(block_rows)
        n_final_one = sum(int(row.get("final_is_stim_event", 0) or 0) for row in block_rows)
        rows.append(
            {
                "date": trial_date_label(trial_id, summary_row),
                "trialID": trial_id,
                "n_blocks_total": n_blocks_total,
                "n_final_is_1": n_final_one,
                "n_final_is_0": n_blocks_total - n_final_one,
                "stim_type": summary_row.get("stim_type", ""),
                "number_of_stim": summary_row.get("number_of_stim", ""),
                "stim_protocol_id": summary_row.get("stim_protocol_id", ""),
                "protocol_match_delta_sec": summary_row.get("protocol_match_delta_sec", ""),
            }
        )
    return rows


def plot_stim_event_slice_panels(
    brightness_trace: np.ndarray,
    time_axis: np.ndarray,
    stim_blocks: list[dict],
    block_rows: list[dict],
    dynamic_thresh: float | None,
    trial_id: str,
    output_dir: Path,
    figure_notes: list[str] | None = None,
) -> None:
    if not stim_blocks or not block_rows or len(time_axis) == 0:
        return

    output_dir.mkdir(parents=True, exist_ok=True)
    global_y_min = float(np.nanmin(brightness_trace)) if len(brightness_trace) else 0.0
    global_y_max = float(np.nanmax(brightness_trace)) if len(brightness_trace) else 1.0
    y_pad = max((global_y_max - global_y_min) * 0.08, 1.0)

    block_by_index = {int(row.get("block_index", idx + 1)): row for idx, row in enumerate(block_rows)}
    note_lines = [str(line) for line in (figure_notes or []) if str(line).strip()]
    for panel_index, block in enumerate(stim_blocks):
        block_index = int(block.get("stim_index", panel_index + 1))
        start = _as_float_or_none(block.get("start_time_sec"))
        end = _as_float_or_none(block.get("end_time_sec"))
        if start is None or end is None:
            continue
        duration = max(0.1, end - start)
        pad = max(1.0, duration * 1.5)
        left = max(0.0, start - pad)
        right = min(float(time_axis[-1]), end + pad)
        mask = (time_axis >= left) & (time_axis <= right)
        local_time = time_axis[mask]
        local_trace = brightness_trace[mask]
        if len(local_time) == 0:
            continue
        fig, ax = plt.subplots(1, 1, figsize=(6.4, 3.8))
        ax.plot(local_time, local_trace, color="#2563eb", linewidth=0.9, alpha=0.85)
        if dynamic_thresh is not None:
            ax.axhline(dynamic_thresh, color="#dc2626", linestyle="--", linewidth=0.8)
        judged = block_by_index.get(block_index, {})
        flag = int(judged.get("final_is_stim_event", 0) or 0)
        color = "#16a34a" if flag == 1 else "#dc2626"
        ax.axvspan(start, end, color=color, alpha=0.22)
        ax.text(
            0.02,
            0.96,
            f"#{block_index}  {flag}",
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=9,
            fontweight="bold",
            color=color,
            bbox={
                "boxstyle": "round,pad=0.18",
                "facecolor": "white",
                "edgecolor": color,
                "alpha": 0.88,
                "linewidth": 0.7,
            },
        )
        if judged.get("matched_final_stim_index", "") != "":
            ax.text(
                0.98,
                0.96,
                f"final #{judged.get('matched_final_stim_index')}",
                transform=ax.transAxes,
                ha="right",
                va="top",
                fontsize=8,
                color="#374151",
            )
        ax.set_xlim(left, right)
        ax.set_ylim(global_y_min - y_pad, global_y_max + y_pad)
        ax.set_xlabel("sec", fontsize=9)
        ax.set_ylabel("a.u.", fontsize=9)
        ax.set_title(
            f"Stimulus block #{block_index} ({flag}) - {trial_id}",
            fontsize=11,
            fontweight="bold",
        )
        ax.grid(True, alpha=0.22)
        if note_lines:
            fig.text(0.01, 0.01, "\n".join(note_lines), ha="left", va="bottom", fontsize=8)
        panel_path = output_dir / f"{trial_id}_stim_block_{block_index:03d}.png"
        try:
            fig.tight_layout(rect=(0.0, 0.05, 1.0, 0.96))
            save_figure_with_pdf(fig, panel_path, dpi=150)
        finally:
            plt.close(fig)


def save_trial_outputs(
    out_dir: Path,
    trial_id: str,
    brightness_trace: np.ndarray,
    time_axis: np.ndarray,
    summary_row: dict,
    events_rows: list[dict],
    pulse_events_rows: list[dict],
    display_stim_blocks: list[dict],
    diagnostic_stim_blocks: list[dict],
    block_rows: list[dict],
    dynamic_thresh: float | None,
    analog_trace: AnalogTrace,
    figure_notes: list[str],
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = output_paths(out_dir, trial_id)

    pd.DataFrame(
        {
            "frame": np.arange(len(brightness_trace)),
            "time_sec": np.round(time_axis, 3),
            "brightness": brightness_trace,
            "analog_source": analog_trace.source,
            "raw_z_index": analog_trace.raw_z_index if analog_trace.raw_z_index is not None else "",
            "raw_z_strategy": analog_trace.raw_z_strategy,
        }
    ).to_csv(paths["brightness_trace"], index=False)

    summary_columns = [
        "trialID",
        "stim_type",
        "number_of_stim",
        "initial_delay_sec",
        "avg_duration_sec",
        "avg_interval_sec",
        "strength",
        "pol_angle_list",
        "stim_protocol_id",
        "stim_protocol_file",
        "stim_protocol_dir",
        "trial_start_estimate",
        "protocol_trial_start_estimate",
        "protocol_match_delta_sec",
        "analog_source",
        "raw_z_index",
        "raw_z_strategy",
    ]
    pd.DataFrame([summary_row]).reindex(columns=summary_columns).to_csv(paths["stim_map"], index=False)

    event_columns = [
        "trialID",
        "stim_index",
        "start_time_sec",
        "end_time_sec",
        "duration_sec",
        "stim_type",
        "pol_angle",
        "strength",
        "stim_protocol_id",
        "mcu_onset_sec",
        "mcu_offset_sec",
        "host_timestamp",
        "timing_source",
        "protocol_match_delta_sec",
        "analog_detected_start_time_sec",
        "analog_detected_end_time_sec",
        "analog_minus_protocol_onset_sec",
    ]
    pd.DataFrame(events_rows).reindex(columns=event_columns).to_csv(paths["stim_events"], index=False)

    pulse_event_columns = [
        "trialID",
        "stim_index",
        "pulse_index",
        "stim_type",
        "pol_angle",
        "stim_protocol_id",
        "mcu_packet_onset_sec",
        "protocol_packet_onset_sec",
        "analog_packet_onset_sec",
        "pulse_on_sec",
        "pulse_off_sec",
        "mcu_pulse_onset_sec",
        "mcu_pulse_offset_sec",
        "protocol_pulse_onset_sec",
        "protocol_pulse_offset_sec",
        "analog_anchored_pulse_onset_sec",
        "analog_anchored_pulse_offset_sec",
        "timing_source",
    ]
    pd.DataFrame(pulse_events_rows).reindex(columns=pulse_event_columns).to_csv(
        paths["stim_pulse_events"],
        index=False,
    )
    pd.DataFrame(block_rows).to_csv(paths["stim_block_diagnostics"], index=False)

    plot_stim_trace(
        brightness_trace=brightness_trace,
        time_axis=time_axis,
        stim_blocks=display_stim_blocks,
        dynamic_thresh=dynamic_thresh,
        trial_id=trial_id,
        output_path=paths["stim_trace"],
        has_pulses=bool(pulse_events_rows),
        figure_notes=figure_notes,
    )

    if events_rows or pulse_events_rows or display_stim_blocks:
        plot_stim_schematic(
            events_rows=events_rows,
            pulse_events_rows=pulse_events_rows,
            stim_blocks=display_stim_blocks,
            trial_id=trial_id,
            output_path=paths["stim_schematic"],
            figure_notes=figure_notes,
        )
        if pulse_events_rows:
            plot_stim_schematic(
                events_rows=events_rows,
                pulse_events_rows=pulse_events_rows,
                stim_blocks=display_stim_blocks,
                trial_id=trial_id,
                output_path=paths["stim_pulse_trace"],
                figure_notes=figure_notes,
            )
    if diagnostic_stim_blocks:
        plot_stim_event_slice_panels(
            brightness_trace=brightness_trace,
            time_axis=time_axis,
            stim_blocks=diagnostic_stim_blocks,
            block_rows=block_rows,
            dynamic_thresh=dynamic_thresh,
            trial_id=trial_id,
            output_dir=paths["stim_event_slices_dir"],
            figure_notes=figure_notes,
        )


def is_nostim(b_max: float, b_min: float, rel_thresh: float) -> bool:
    if b_max <= 0:
        return True
    return ((b_max - b_min) / b_max) < rel_thresh


def process_trial(
    trial: TrialInput,
    out_dir: Path,
    action: str,
    dry_run: bool,
    nostim_rel_thresh: float,
    protocols: list[StimProtocol],
    analog_source: str,
    raw_z_strategy: str,
) -> tuple[dict | None, list[dict], list[dict], str]:
    if required_outputs_done(out_dir, trial.trial_id) and action == "skip":
        return None, [], [], "skipped"

    if dry_run:
        LOGGER.info("[dry-run] 将处理 %s -> %s", trial.input_dir, out_dir)
        return None, [], [], "processed"

    if action == "overwrite":
        clean_step_outputs(out_dir, trial.trial_id)

    with trial.metadata_path.open("r", encoding="utf-8") as handle:
        meta = json.load(handle)
    dt = float(meta.get("temporal_calibration", {}).get("frame_interval_sec", 1.0) or 1.0)
    n_z = int(meta.get("dimensions", {}).get("z_slices", 1) or 1)
    timepoints = int(meta.get("dimensions", {}).get("timepoints", 0) or 0)
    if dt <= 0:
        LOGGER.warning("%s 的 frame_interval_sec=%s；将使用 1.0 秒。", trial.trial_id, dt)
        dt = 1.0

    analog_trace = read_analog_trace(trial, analog_source, raw_z_strategy)
    brightness_trace = analog_trace.trace
    analog_dt = dt * analog_trace.dt_scale
    time_axis = np.arange(len(brightness_trace)) * analog_dt

    b_max = float(np.max(brightness_trace))
    b_min = float(np.min(brightness_trace))
    if is_nostim(b_max, b_min, nostim_rel_thresh):
        stim_blocks: list[dict] = []
        dynamic_thresh = None
    else:
        dynamic_thresh = b_min + 1 / (n_z + 1) * (b_max - b_min)
        stim_blocks = analyze_stim_blocks(
            brightness_trace=brightness_trace,
            dt=analog_dt,
            dynamic_thresh=dynamic_thresh,
            baseline=b_min,
            peak=b_max,
        )

    trial_start_estimate = estimate_trial_start_from_metadata(meta, trial.raw_oir_path, timepoints, dt)
    protocol, protocol_match_delta_sec = match_stim_protocol(protocols, trial_start_estimate)
    if protocol is not None:
        LOGGER.info(
            "Matched %s to stimulus protocol %s (%s, absolute start delta %.3fs).",
            trial.trial_id,
            protocol.run_id,
            protocol.stim_mode or "unknown mode",
            protocol_match_delta_sec if protocol_match_delta_sec is not None else float("nan"),
        )
    else:
        LOGGER.info("%s 未按绝对时间匹配到刺激协议；标记为 nostim。", trial.trial_id)

    packet_stim_blocks = packet_blocks_from_pulse_blocks(stim_blocks, protocol)
    events_rows = build_events_rows(
        trial.trial_id,
        packet_stim_blocks,
        protocol,
        protocol_match_delta_sec,
        trial_start_estimate,
    )
    summary_row = build_summary_row(
        trial.trial_id,
        protocol,
        protocol_match_delta_sec,
        trial_start_estimate,
        events_rows,
        analog_trace,
    )
    pulse_events_rows = build_pulse_events_rows(trial.trial_id, stim_blocks, protocol, trial_start_estimate)
    block_rows = block_judgement_rows(stim_blocks, events_rows)
    figure_notes = build_figure_notes(protocol, protocol_match_delta_sec, analog_trace)
    display_stim_blocks = [
        {
            "stim_index": row.get("stim_index", index + 1),
            "start_time_sec": row.get("start_time_sec"),
            "end_time_sec": row.get("end_time_sec"),
            "duration_sec": row.get("duration_sec", ""),
            "pol_angle": row.get("pol_angle", ""),
        }
        for index, row in enumerate(events_rows)
    ]
    save_trial_outputs(
        out_dir=out_dir,
        trial_id=trial.trial_id,
        brightness_trace=brightness_trace,
        time_axis=time_axis,
        summary_row=summary_row,
        events_rows=events_rows,
        pulse_events_rows=pulse_events_rows,
        display_stim_blocks=display_stim_blocks,
        diagnostic_stim_blocks=stim_blocks,
        block_rows=block_rows,
        dynamic_thresh=dynamic_thresh,
        analog_trace=analog_trace,
        figure_notes=figure_notes,
    )
    return summary_row, events_rows, pulse_events_rows, "processed"


def save_combined_outputs(
    step_root: Path,
    summaries: list[dict],
    events: list[dict],
    pulse_events: list[dict],
    block_rows_by_trial: dict[str, list[dict]],
    dry_run: bool,
) -> None:
    if dry_run:
        LOGGER.info(
            "[dry-run] 将在 %s 中写入合并后的 stim_map.csv、stim_events.csv、stim_pulse_events.csv 和 stim_block_summary.csv",
            step_root,
        )
        return

    step_root.mkdir(parents=True, exist_ok=True)
    summary_columns = [
        "trialID",
        "stim_type",
        "number_of_stim",
        "initial_delay_sec",
        "avg_duration_sec",
        "avg_interval_sec",
        "strength",
        "pol_angle_list",
        "stim_protocol_id",
        "stim_protocol_file",
        "stim_protocol_dir",
        "trial_start_estimate",
        "protocol_trial_start_estimate",
        "protocol_match_delta_sec",
        "analog_source",
        "raw_z_index",
        "raw_z_strategy",
    ]
    event_columns = [
        "trialID",
        "stim_index",
        "start_time_sec",
        "end_time_sec",
        "duration_sec",
        "stim_type",
        "pol_angle",
        "strength",
        "stim_protocol_id",
        "mcu_onset_sec",
        "mcu_offset_sec",
        "host_timestamp",
        "timing_source",
        "protocol_match_delta_sec",
        "analog_detected_start_time_sec",
        "analog_detected_end_time_sec",
        "analog_minus_protocol_onset_sec",
    ]
    pd.DataFrame(summaries).reindex(columns=summary_columns).to_csv(step_root / "stim_map.csv", index=False)
    match_columns = [
        "trialID",
        "trial_start_estimate",
        "stim_protocol_id",
        "stim_protocol_file",
        "stim_protocol_dir",
        "protocol_trial_start_estimate",
        "protocol_match_delta_sec",
        "stim_type",
        "number_of_stim",
        "pol_angle_list",
        "analog_source",
        "raw_z_index",
        "raw_z_strategy",
    ]
    pd.DataFrame(summaries).reindex(columns=match_columns).to_csv(
        step_root / "stim_protocol_matches.csv",
        index=False,
    )
    pd.DataFrame(events).reindex(columns=event_columns).to_csv(step_root / "stim_events.csv", index=False)

    pulse_event_columns = [
        "trialID",
        "stim_index",
        "pulse_index",
        "stim_type",
        "pol_angle",
        "stim_protocol_id",
        "mcu_packet_onset_sec",
        "protocol_packet_onset_sec",
        "analog_packet_onset_sec",
        "pulse_on_sec",
        "pulse_off_sec",
        "mcu_pulse_onset_sec",
        "mcu_pulse_offset_sec",
        "protocol_pulse_onset_sec",
        "protocol_pulse_offset_sec",
        "analog_anchored_pulse_onset_sec",
        "analog_anchored_pulse_offset_sec",
        "timing_source",
    ]
    pd.DataFrame(pulse_events).reindex(columns=pulse_event_columns).to_csv(
        step_root / "stim_pulse_events.csv",
        index=False,
    )
    block_summary_columns = [
        "date",
        "trialID",
        "n_blocks_total",
        "n_final_is_1",
        "n_final_is_0",
        "stim_type",
        "number_of_stim",
        "stim_protocol_id",
        "protocol_match_delta_sec",
    ]
    pd.DataFrame(build_block_summary_rows(summaries, block_rows_by_trial)).reindex(
        columns=block_summary_columns
    ).to_csv(step_root / "stim_block_summary.csv", index=False)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate stimulus maps from step-01 stim analog outputs.")
    parser.add_argument("--data-root", type=Path, required=True, help="Original data root.")
    parser.add_argument("--input-root", type=Path, help="Step-01 TIFF root. Default: OUTPUT_ROOT/01_oir_to_tif.")
    parser.add_argument("--output-root", type=Path, help="Pipeline output root. Default: DATA_ROOT.")
    parser.add_argument("--action", choices=("skip", "overwrite"), default="skip", help="Existing-output behavior.")
    parser.add_argument("--dry-run", action="store_true", help="Print work plan without reading TIFFs or writing files.")
    parser.add_argument("--nostim-rel-thresh", type=float, default=DEFAULT_NOSTIM_REL_THRESH)
    parser.add_argument(
        "--analog-source",
        choices=("auto", "raw", "projected"),
        default="auto",
        help=(
            "Stim analog source. auto prefers *_Stim_Analog_Raw/ when complete, "
            "then falls back to *_Stim_Analog.tif."
        ),
    )
    parser.add_argument(
        "--raw-z-strategy",
        choices=("planes", "max-range", "mean", "max"),
        default="planes",
        help=(
            "How to reduce raw z-stack stim analog to one trace. "
            "planes expands z planes into a denser time axis."
        ),
    )
    parser.add_argument(
        "--stim-log-root",
        type=Path,
        help=(
            "Folder containing raw stimulus logs. Nested folders are supported; "
            "timestamp_log_*.csv is matched to stim_map_*.csv and experiment_config_*.json in the same folder."
        ),
    )
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--trial-id", help="Only process one trial ID, or a comma-separated list of trial IDs.")
    return parser


def read_first_row_dict(path: Path) -> dict:
    if not path.exists() or path.stat().st_size == 0:
        return {}
    try:
        df = pd.read_csv(path)
    except pd.errors.EmptyDataError:
        return {}
    if df.empty:
        return {}
    return df.iloc[0].to_dict()


def read_rows_dicts(path: Path) -> list[dict]:
    if not path.exists() or path.stat().st_size == 0:
        return []
    try:
        df = pd.read_csv(path)
    except pd.errors.EmptyDataError:
        return []
    if df.empty:
        return []
    return df.to_dict("records")


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose)

    data_root = args.data_root.expanduser().resolve()
    output_root = args.output_root.expanduser().resolve() if args.output_root else default_output_root(data_root).resolve()
    input_root = args.input_root.expanduser().resolve() if args.input_root else default_input_root(data_root, output_root).resolve()
    out_root = step_output_root(output_root)

    if not input_root.exists():
        if args.dry_run:
            LOGGER.warning("输入根目录尚不存在：%s", input_root)
            LOGGER.info("dry-run 完成。step 02 处理数据前必须先运行 step 01。")
            return 0
        LOGGER.error("输入根目录不存在：%s", input_root)
        return 1

    trials = discover_trials(input_root, data_root)
    if args.trial_id:
        wanted = {item.strip() for item in args.trial_id.split(",") if item.strip()}
        trials = [trial for trial in trials if trial.trial_id in wanted]
    summary = RunSummary(found=len(trials))
    LOGGER.info("输入根目录：%s", input_root)
    LOGGER.info("输出根目录：%s", out_root)
    LOGGER.info("模拟信号来源：%s", args.analog_source)
    LOGGER.info("原始 z 轴策略：%s", args.raw_z_strategy)
    LOGGER.info("找到 %d 个含 Stim_Analog 输出的 trial。", len(trials))
    stim_log_root = args.stim_log_root.expanduser().resolve() if args.stim_log_root else default_stim_log_root(data_root)
    if stim_log_root is not None:
        LOGGER.info("刺激日志根目录：%s", stim_log_root)
    protocols = discover_stim_protocols(stim_log_root)

    all_summaries: list[dict] = []
    all_events: list[dict] = []
    all_pulse_events: list[dict] = []
    all_block_rows_by_trial: dict[str, list[dict]] = {}

    for trial in trials:
        out_dir = trial_output_dir(out_root, trial)
        try:
            summary_row, events_rows, pulse_events_rows, status = process_trial(
                trial=trial,
                out_dir=out_dir,
                action=args.action,
                dry_run=args.dry_run,
                nostim_rel_thresh=args.nostim_rel_thresh,
                protocols=protocols,
                analog_source=args.analog_source,
                raw_z_strategy=args.raw_z_strategy,
            )
        except Exception as exc:
            LOGGER.exception("Failed trial %s: %s", trial.trial_id, exc)
            summary.failed += 1
            continue

        if status == "skipped":
            summary.skipped += 1
            LOGGER.info("[跳过] %s", trial.trial_id)
        else:
            summary.processed += 1
            LOGGER.info("[完成] %s", trial.trial_id)

        if summary_row is not None:
            all_summaries.append(summary_row)
        else:
            stim_map_path = output_paths(out_dir, trial.trial_id)["stim_map"]
            existing_summary_row = read_first_row_dict(stim_map_path)
            if existing_summary_row:
                all_summaries.append(existing_summary_row)
        all_events.extend(events_rows)
        all_pulse_events.extend(pulse_events_rows)
        block_path = output_paths(out_dir, trial.trial_id)["stim_block_diagnostics"]
        all_block_rows_by_trial[trial.trial_id] = read_rows_dicts(block_path)

    if all_summaries or all_block_rows_by_trial or args.dry_run:
        save_combined_outputs(
            out_root,
            all_summaries,
            all_events,
            all_pulse_events,
            all_block_rows_by_trial,
            dry_run=args.dry_run,
        )

    LOGGER.info("汇总：")
    LOGGER.info("  找到：%d", summary.found)
    LOGGER.info("  已处理或将处理：%d", summary.processed)
    LOGGER.info("  跳过：%d", summary.skipped)
    LOGGER.info("  失败：%d", summary.failed)
    return 1 if summary.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
