#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Motion correction with CaImAn.

Default layout:
  input : DATA_ROOT/01_oir_to_tif/
  stim  : DATA_ROOT/02_stim_map/
  output: DATA_ROOT/03_motion_correct/

This step is intentionally conservative. Existing corrected movies are skipped
by default, overwrite removes only files generated by this step inside the
selected trial output folder, and dry-run never opens TIFF movies.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import shutil
from dataclasses import dataclass
from pathlib import Path


LOGGER = logging.getLogger("motion_correct_caiman")

STEP_NAME = "03_motion_correct"
STEP_OUTPUT_PATTERNS = (
    "*_corrected_movie.tif",
    "*_corrected_movie.tiff",
    "*_motion_correct_figure.png",
    "*_metadata.json",
    "*_brightness_trace.csv",
    "*_stim_events.csv",
    "*_stim_map.csv",
    "*_stim_pulse_events.csv",
    "*_stim_trace.png",
    "*_stim_trace.pdf",
    "*_stim_schematic.png",
    "*_stim_schematic.pdf",
    "*_stim_pulse_trace.png",
    "*_stim_pulse_trace.pdf",
    "memmap_*",
)


@dataclass(frozen=True)
class TrialInput:
    trial_id: str
    rel_parent: Path
    input_dir: Path
    movie_path: Path
    metadata_path: Path | None


@dataclass
class RunSummary:
    found: int = 0
    processed: int = 0
    skipped: int = 0
    failed: int = 0


def configure_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def default_output_root(data_root: Path) -> Path:
    return data_root


def default_input_root(output_root: Path) -> Path:
    return output_root / "01_oir_to_tif"


def default_stim_root(output_root: Path) -> Path:
    return output_root / "02_stim_map"


def step_output_root(output_root: Path) -> Path:
    return output_root / STEP_NAME


def trial_output_dir(step_root: Path, trial: TrialInput) -> Path:
    if str(trial.rel_parent) in ("", "."):
        return step_root / trial.trial_id
    return step_root / trial.rel_parent / trial.trial_id


def corrected_movie_path(out_dir: Path, trial_id: str) -> Path:
    return out_dir / f"{trial_id}_corrected_movie.tif"


def required_outputs_done(out_dir: Path, trial_id: str) -> bool:
    path = corrected_movie_path(out_dir, trial_id)
    return path.exists() and path.is_file() and path.stat().st_size > 0


def find_first_existing(folder: Path, patterns: tuple[str, ...]) -> Path | None:
    for pattern in patterns:
        matches = sorted(folder.glob(pattern))
        if matches:
            return matches[0]
    return None


def discover_trials(input_root: Path) -> list[TrialInput]:
    trials: list[TrialInput] = []
    movie_paths = sorted(
        list(input_root.rglob("*_Max_Proj.tif"))
        + list(input_root.rglob("*_Max_Proj.tiff"))
    )

    for movie_path in movie_paths:
        if "_corrected_movie" in movie_path.name:
            continue
        input_dir = movie_path.parent
        trial_id = input_dir.name
        rel_parent = input_dir.parent.relative_to(input_root)
        metadata_path = find_first_existing(input_dir, ("*_metadata.json",))
        trials.append(
            TrialInput(
                trial_id=trial_id,
                rel_parent=rel_parent,
                input_dir=input_dir,
                movie_path=movie_path,
                metadata_path=metadata_path,
            )
        )
    return trials


def clean_step_outputs(out_dir: Path) -> int:
    if not out_dir.exists():
        return 0

    removed = 0
    for pattern in STEP_OUTPUT_PATTERNS:
        for path in out_dir.glob(pattern):
            if path.is_dir():
                shutil.rmtree(path)
                removed += 1
                LOGGER.info("Removed old step-03 folder: %s", path)
            elif path.is_file() or path.is_symlink():
                path.unlink()
                removed += 1
                LOGGER.info("Removed old step-03 file: %s", path)
    return removed


def read_fps_from_metadata(metadata_path: Path | None, default_fps: float) -> float:
    if metadata_path is None or not metadata_path.exists():
        LOGGER.warning("Metadata not found; using default fps=%s.", default_fps)
        return float(default_fps)

    try:
        with metadata_path.open("r", encoding="utf-8") as handle:
            data = json.load(handle)
        fps = data.get("temporal_calibration", {}).get("fps")
        if fps is None:
            LOGGER.warning("Metadata fps is null in %s; using default fps=%s.", metadata_path, default_fps)
            return float(default_fps)
        fps = float(fps)
        if fps <= 0:
            LOGGER.warning("Metadata fps=%s in %s; using default fps=%s.", fps, metadata_path, default_fps)
            return float(default_fps)
        return fps
    except Exception as exc:
        LOGGER.warning("Could not read fps from %s: %s; using default fps=%s.", metadata_path, exc, default_fps)
        return float(default_fps)


def copy_if_exists(src: Path | None, dst: Path) -> bool:
    if src is None or not src.exists():
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    LOGGER.info("Copied %s -> %s", src, dst)
    return True


def copy_sidecar_outputs(trial: TrialInput, out_dir: Path, stim_root: Path | None) -> None:
    copy_if_exists(trial.metadata_path, out_dir / f"{trial.trial_id}_metadata.json")

    if stim_root is None:
        return

    stim_dir = stim_root / trial.rel_parent / trial.trial_id
    sidecar_suffixes = (
        "_stim_events.csv",
        "_stim_map.csv",
        "_stim_pulse_events.csv",
    )
    for suffix in sidecar_suffixes:
        copy_if_exists(stim_dir / f"{trial.trial_id}{suffix}", out_dir / f"{trial.trial_id}{suffix}")


def configure_thread_limits(num_threads: int) -> None:
    value = str(max(1, int(num_threads)))
    os.environ.setdefault("MKL_NUM_THREADS", value)
    os.environ.setdefault("OPENBLAS_NUM_THREADS", value)
    os.environ.setdefault("VECLIB_MAXIMUM_THREADS", value)
    os.environ.setdefault("NUMEXPR_NUM_THREADS", value)

    try:
        import cv2

        cv2.setNumThreads(0)
    except Exception:
        pass


def run_caiman_motion_correction(
    trial: TrialInput,
    out_dir: Path,
    default_fps: float,
    n_processes: int | None,
    max_shifts: tuple[int, int],
    strides: tuple[int, int],
    overlaps: tuple[int, int],
    gsig_filt: tuple[int, int],
) -> None:
    import caiman as cm
    import numpy as np
    from caiman.motion_correction import MotionCorrect
    from caiman.source_extraction.cnmf import params as caiman_params

    out_dir.mkdir(parents=True, exist_ok=True)
    movie_paths = [str(trial.movie_path)]
    frate = read_fps_from_metadata(trial.metadata_path, default_fps=default_fps)

    LOGGER.info("Setting up CaImAn cluster for %s.", trial.trial_id)
    _, cluster, actual_processes = cm.cluster.setup_cluster(
        backend="multiprocessing",
        n_processes=n_processes,
        ignore_preexisting=False,
    )
    LOGGER.info("CaImAn cluster processes: %s", actual_processes)

    try:
        mc_dict = {
            "fnames": movie_paths,
            "fr": frate,
            "decay_time": 2.5,
            "pw_rigid": True,
            "max_shifts": max_shifts,
            "gSig_filt": gsig_filt,
            "strides": strides,
            "overlaps": overlaps,
            "max_deviation_rigid": 3,
            "border_nan": "copy",
        }
        parameters = caiman_params.CNMFParams(params_dict=mc_dict)
        motion_corrector = MotionCorrect(
            movie_paths,
            dview=cluster,
            **parameters.get_group("motion"),
        )
        motion_corrector.motion_correct(save_movie=True)

        bord_px = int(
            np.ceil(
                np.maximum(
                    np.max(np.abs(motion_corrector.x_shifts_els)),
                    np.max(np.abs(motion_corrector.y_shifts_els)),
                )
            )
        )
        if mc_dict["border_nan"] == "copy":
            bord_px = 0

        cm.save_memmap(
            motion_corrector.fname_tot_els,
            base_name=str(out_dir / "memmap_"),
            order="C",
            border_to_0=bord_px,
        )

        corrected = cm.load(motion_corrector.mmap_file)
        output_path = corrected_movie_path(out_dir, trial.trial_id)
        corrected.save(str(output_path), bigtiff=True)
        LOGGER.info("Saved corrected movie: %s", output_path)
    finally:
        try:
            cm.stop_server(dview=cluster)
            LOGGER.info("CaImAn cluster stopped.")
        except Exception as exc:
            LOGGER.warning("Failed to stop CaImAn cluster: %s", exc)


def process_trial(
    trial: TrialInput,
    out_dir: Path,
    stim_root: Path | None,
    action: str,
    dry_run: bool,
    default_fps: float,
    n_processes: int | None,
    num_threads: int,
    max_shift: int,
    stride: int,
    overlap: int,
    gsig_filt: int,
) -> str:
    if required_outputs_done(out_dir, trial.trial_id) and action == "skip":
        return "skipped"

    if dry_run:
        LOGGER.info("[dry-run] Would motion-correct %s -> %s", trial.movie_path, out_dir)
        return "processed"

    if action == "overwrite":
        clean_step_outputs(out_dir)

    configure_thread_limits(num_threads)
    run_caiman_motion_correction(
        trial=trial,
        out_dir=out_dir,
        default_fps=default_fps,
        n_processes=n_processes,
        max_shifts=(max_shift, max_shift),
        strides=(stride, stride),
        overlaps=(overlap, overlap),
        gsig_filt=(gsig_filt, gsig_filt),
    )
    copy_sidecar_outputs(trial, out_dir, stim_root)
    return "processed"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Motion-correct Max_Proj TIFFs with CaImAn.")
    parser.add_argument("--data-root", type=Path, required=True, help="Original data root.")
    parser.add_argument("--input-root", type=Path, help="Step-01 TIFF root. Default: OUTPUT_ROOT/01_oir_to_tif.")
    parser.add_argument("--stim-root", type=Path, help="Step-02 stim-map root. Default: OUTPUT_ROOT/02_stim_map.")
    parser.add_argument("--output-root", type=Path, help="Pipeline output root. Default: DATA_ROOT.")
    parser.add_argument("--action", choices=("skip", "overwrite"), default="skip", help="Existing-output behavior.")
    parser.add_argument("--dry-run", action="store_true", help="Print work plan without opening TIFFs.")
    parser.add_argument("--default-fps", type=float, default=2.0, help="Fallback fps when metadata is missing.")
    parser.add_argument("--n-processes", type=int, default=None, help="CaImAn worker processes. Default lets CaImAn choose.")
    parser.add_argument("--num-threads", type=int, default=1, help="Thread limit for BLAS/OpenCV libraries.")
    parser.add_argument("--max-shift", type=int, default=20, help="Maximum x/y shift in pixels.")
    parser.add_argument("--stride", type=int, default=48, help="Patch stride for pw-rigid correction.")
    parser.add_argument("--overlap", type=int, default=24, help="Patch overlap for pw-rigid correction.")
    parser.add_argument("--gsig-filt", type=int, default=5, help="Spatial high-pass filter size.")
    parser.add_argument("--verbose", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose)

    data_root = args.data_root.expanduser().resolve()
    output_root = args.output_root.expanduser().resolve() if args.output_root else default_output_root(data_root).resolve()
    input_root = args.input_root.expanduser().resolve() if args.input_root else default_input_root(output_root).resolve()
    stim_root = args.stim_root.expanduser().resolve() if args.stim_root else default_stim_root(output_root).resolve()
    out_root = step_output_root(output_root)

    if not input_root.exists():
        if args.dry_run:
            LOGGER.warning("Input root does not exist yet: %s", input_root)
            return 0
        LOGGER.error("Input root does not exist: %s", input_root)
        return 1

    if not stim_root.exists():
        LOGGER.warning("Stim root does not exist; sidecar stim files will not be copied: %s", stim_root)
        stim_root_or_none: Path | None = None
    else:
        stim_root_or_none = stim_root

    trials = discover_trials(input_root)
    summary = RunSummary(found=len(trials))
    LOGGER.info("Input root : %s", input_root)
    LOGGER.info("Stim root  : %s", stim_root_or_none or "(missing)")
    LOGGER.info("Output root: %s", out_root)
    LOGGER.info("Found %d trial(s) with Max_Proj TIFFs.", len(trials))

    for trial in trials:
        out_dir = trial_output_dir(out_root, trial)
        try:
            status = process_trial(
                trial=trial,
                out_dir=out_dir,
                stim_root=stim_root_or_none,
                action=args.action,
                dry_run=args.dry_run,
                default_fps=args.default_fps,
                n_processes=args.n_processes,
                num_threads=args.num_threads,
                max_shift=args.max_shift,
                stride=args.stride,
                overlap=args.overlap,
                gsig_filt=args.gsig_filt,
            )
        except Exception as exc:
            LOGGER.exception("Failed trial %s: %s", trial.trial_id, exc)
            summary.failed += 1
            continue

        if status == "skipped":
            summary.skipped += 1
            LOGGER.info("[skip] %s", trial.trial_id)
        else:
            summary.processed += 1
            LOGGER.info("[ok] %s", trial.trial_id)

    LOGGER.info("Summary:")
    LOGGER.info("  found: %d", summary.found)
    LOGGER.info("  processed or would process: %d", summary.processed)
    LOGGER.info("  skipped: %d", summary.skipped)
    LOGGER.info("  failed: %d", summary.failed)
    return 1 if summary.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
