#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Spatial high-pass filtering for corrected calcium movies.

Default layout:
  input : DATA_ROOT/03_motion_correct/
  output: DATA_ROOT/04_spatial_highpass/

The filter is applied frame-by-frame:
  highpass = frame - gaussian_blur(frame, sigma)

This keeps memory usage bounded for large TIFF movies. Existing outputs are
skipped by default, and overwrite removes only files generated by this step.
"""

from __future__ import annotations

import argparse
import json
import logging
import shutil
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import tifffile as tf
from scipy.ndimage import gaussian_filter


LOGGER = logging.getLogger("spatial_highpass")

STEP_NAME = "04_spatial_highpass"
STEP_OUTPUT_PATTERNS = (
    "*_spatial_highpass_movie.tif",
    "*_spatial_highpass_movie.tiff",
    "*_metadata.json",
    "*_brightness_trace.csv",
    "*_stim_events.csv",
    "*_stim_map.csv",
    "*_stim_pulse_events.csv",
    "*_stim_trace.png",
    "*_stim_trace.pdf",
    "*_stim_schematic.png",
    "*_stim_schematic.pdf",
    "*_stim_pulse_trace.png",
    "*_stim_pulse_trace.pdf",
    "spatial_highpass_summary.json",
    "preview_before_after.png",
    "preview_before_after.pdf",
)


@dataclass(frozen=True)
class TrialInput:
    trial_id: str
    rel_parent: Path
    input_dir: Path
    movie_path: Path
    metadata_path: Path | None


@dataclass
class RunSummary:
    found: int = 0
    processed: int = 0
    skipped: int = 0
    failed: int = 0


def configure_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def default_output_root(data_root: Path) -> Path:
    return data_root


def default_input_root(output_root: Path) -> Path:
    return output_root / "03_motion_correct"


def step_output_root(output_root: Path) -> Path:
    return output_root / STEP_NAME


def trial_output_dir(step_root: Path, trial: TrialInput) -> Path:
    if str(trial.rel_parent) in ("", "."):
        return step_root / trial.trial_id
    return step_root / trial.rel_parent / trial.trial_id


def output_movie_path(out_dir: Path, trial_id: str) -> Path:
    return out_dir / f"{trial_id}_spatial_highpass_movie.tif"


def required_outputs_done(out_dir: Path, trial_id: str) -> bool:
    path = output_movie_path(out_dir, trial_id)
    return path.exists() and path.is_file() and path.stat().st_size > 0


def find_first_existing(folder: Path, patterns: tuple[str, ...]) -> Path | None:
    for pattern in patterns:
        matches = sorted(folder.glob(pattern))
        if matches:
            return matches[0]
    return None


def discover_trials(input_root: Path) -> list[TrialInput]:
    patterns = (
        "*_brightness_adjusted_movie.tif",
        "*_brightness_corrected_movie.tif",
        "*_corrected_movie.tif",
    )
    movie_paths: list[Path] = []
    for pattern in patterns:
        movie_paths.extend(sorted(input_root.rglob(pattern)))

    seen_dirs: set[Path] = set()
    trials: list[TrialInput] = []
    for movie_path in movie_paths:
        input_dir = movie_path.parent
        if input_dir in seen_dirs:
            continue
        seen_dirs.add(input_dir)

        trial_id = input_dir.name
        rel_parent = input_dir.parent.relative_to(input_root)
        metadata_path = find_first_existing(input_dir, ("*_metadata.json",))
        trials.append(
            TrialInput(
                trial_id=trial_id,
                rel_parent=rel_parent,
                input_dir=input_dir,
                movie_path=movie_path,
                metadata_path=metadata_path,
            )
        )
    return trials


def clean_step_outputs(out_dir: Path) -> int:
    if not out_dir.exists():
        return 0

    removed = 0
    for pattern in STEP_OUTPUT_PATTERNS:
        for path in out_dir.glob(pattern):
            if path.is_dir():
                shutil.rmtree(path)
                removed += 1
                LOGGER.info("已删除旧的 step-04 文件夹：%s", path)
            elif path.is_file() or path.is_symlink():
                path.unlink()
                removed += 1
                LOGGER.info("已删除旧的 step-04 文件：%s", path)
    return removed


def copy_if_exists(src: Path | None, dst: Path) -> bool:
    if src is None or not src.exists():
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    LOGGER.info("已复制 %s -> %s", src, dst)
    return True


def copy_sidecar_outputs(trial: TrialInput, out_dir: Path) -> None:
    suffixes = (
        "_metadata.json",
        "_stim_events.csv",
        "_stim_map.csv",
        "_stim_pulse_events.csv",
    )
    for suffix in suffixes:
        copy_if_exists(trial.input_dir / f"{trial.trial_id}{suffix}", out_dir / f"{trial.trial_id}{suffix}")


def percentile_stretch(img: np.ndarray, pmin: float = 1.0, pmax: float = 99.5) -> np.ndarray:
    x = np.asarray(img, dtype=np.float32)
    lo = np.percentile(x, pmin)
    hi = np.percentile(x, pmax)
    if hi <= lo:
        hi = lo + 1e-6
    return np.clip((x - lo) / (hi - lo), 0, 1)


def highpass_frame(frame: np.ndarray, sigma_px: float, clip_negative: bool) -> np.ndarray:
    frame_f = np.asarray(frame, dtype=np.float32)
    lowfreq = gaussian_filter(frame_f, sigma=sigma_px)
    highpass = frame_f - lowfreq
    if clip_negative:
        highpass = np.maximum(highpass, 0)
    return highpass.astype(np.float32, copy=False)


def iter_movie_frames(movie_path: Path):
    with tf.TiffFile(movie_path) as tif:
        series = tif.series[0]
        if len(series.shape) != 3:
            arr = series.asarray()
            arr = np.asarray(arr)
            if arr.ndim != 3:
                raise ValueError(f"Movie must be 3D (T,Y,X), got shape={arr.shape}")
            for frame in arr:
                yield frame
            return

        for page in series.pages:
            arr = page.asarray()
            arr = np.asarray(arr)
            if arr.ndim == 2:
                yield arr
            elif arr.ndim == 3:
                for frame in arr:
                    yield frame
            else:
                raise ValueError(f"Unsupported TIFF page shape {arr.shape} in {movie_path}")


def movie_shape(movie_path: Path) -> tuple[int, int, int]:
    with tf.TiffFile(movie_path) as tif:
        shape = tuple(int(x) for x in tif.series[0].shape)
    if len(shape) != 3:
        raise ValueError(f"Movie must be 3D (T,Y,X), got shape={shape}")
    return shape


def save_preview(
    raw_mid: np.ndarray,
    hp_mid: np.ndarray,
    raw_mean: np.ndarray,
    hp_mean: np.ndarray,
    output_path: Path,
    dpi: int,
) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(10, 8))
    axes[0, 0].imshow(percentile_stretch(raw_mid), cmap="gray")
    axes[0, 0].set_title("Input frame")
    axes[0, 0].axis("off")

    axes[0, 1].imshow(percentile_stretch(hp_mid), cmap="gray")
    axes[0, 1].set_title("Spatial high-pass frame")
    axes[0, 1].axis("off")

    axes[1, 0].imshow(percentile_stretch(raw_mean), cmap="gray")
    axes[1, 0].set_title("Input mean")
    axes[1, 0].axis("off")

    axes[1, 1].imshow(percentile_stretch(hp_mean), cmap="gray")
    axes[1, 1].set_title("High-pass mean")
    axes[1, 1].axis("off")

    plt.tight_layout()
    try:
        fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
        fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")
    finally:
        plt.close(fig)


def process_movie_stream(
    movie_path: Path,
    out_movie: Path,
    preview_path: Path,
    sigma_px: float,
    clip_negative: bool,
    dpi: int,
) -> dict:
    n_frames, height, width = movie_shape(movie_path)
    midpoint = n_frames // 2
    raw_sum = np.zeros((height, width), dtype=np.float64)
    hp_sum = np.zeros((height, width), dtype=np.float64)
    raw_mid = None
    hp_mid = None

    out_movie.parent.mkdir(parents=True, exist_ok=True)
    with tf.TiffWriter(out_movie, bigtiff=True) as writer:
        for index, frame in enumerate(iter_movie_frames(movie_path)):
            hp_frame = highpass_frame(frame, sigma_px=sigma_px, clip_negative=clip_negative)
            writer.write(hp_frame, contiguous=True)
            raw_sum += np.asarray(frame, dtype=np.float32)
            hp_sum += hp_frame
            if index == midpoint:
                raw_mid = np.asarray(frame, dtype=np.float32).copy()
                hp_mid = hp_frame.copy()

    if raw_mid is None or hp_mid is None:
        raise RuntimeError(f"No frames were written for {movie_path}")

    save_preview(
        raw_mid=raw_mid,
        hp_mid=hp_mid,
        raw_mean=(raw_sum / n_frames).astype(np.float32),
        hp_mean=(hp_sum / n_frames).astype(np.float32),
        output_path=preview_path,
        dpi=dpi,
    )
    return {"frames": n_frames, "height": height, "width": width}


def process_trial(
    trial: TrialInput,
    out_dir: Path,
    action: str,
    dry_run: bool,
    sigma_px: float,
    clip_negative: bool,
    dpi: int,
) -> str:
    if required_outputs_done(out_dir, trial.trial_id) and action == "skip":
        return "skipped"

    if dry_run:
        LOGGER.info("[dry-run] 将执行高通处理 %s -> %s", trial.movie_path, out_dir)
        return "processed"

    if action == "overwrite":
        clean_step_outputs(out_dir)

    out_dir.mkdir(parents=True, exist_ok=True)
    out_movie = output_movie_path(out_dir, trial.trial_id)
    preview_path = out_dir / "preview_before_after.png"

    shape_info = process_movie_stream(
        movie_path=trial.movie_path,
        out_movie=out_movie,
        preview_path=preview_path,
        sigma_px=sigma_px,
        clip_negative=clip_negative,
        dpi=dpi,
    )
    copy_sidecar_outputs(trial, out_dir)

    summary = {
        "trial_id": trial.trial_id,
        "input_movie": str(trial.movie_path),
        "output_movie": str(out_movie),
        "gaussian_sigma_px": sigma_px,
        "clip_negative": clip_negative,
        **shape_info,
    }
    with (out_dir / "spatial_highpass_summary.json").open("w", encoding="utf-8") as handle:
        json.dump(summary, handle, indent=2)
    LOGGER.info("已保存空间高通电影：%s", out_movie)
    return "processed"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Apply spatial high-pass filtering to corrected movies.")
    parser.add_argument("--data-root", type=Path, required=True, help="Original data root.")
    parser.add_argument("--input-root", type=Path, help="Step-03 corrected movie root. Default: OUTPUT_ROOT/03_motion_correct.")
    parser.add_argument("--output-root", type=Path, help="Pipeline output root. Default: DATA_ROOT.")
    parser.add_argument("--action", choices=("skip", "overwrite"), default="skip", help="Existing-output behavior.")
    parser.add_argument("--dry-run", action="store_true", help="Print work plan without reading TIFFs or writing files.")
    parser.add_argument("--sigma-px", type=float, default=12.0, help="Gaussian sigma for spatial low-pass background.")
    parser.add_argument("--clip-negative", action="store_true", help="Clip negative high-pass values to zero.")
    parser.add_argument("--dpi", type=int, default=150, help="Preview figure DPI.")
    parser.add_argument("--verbose", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose)

    data_root = args.data_root.expanduser().resolve()
    output_root = args.output_root.expanduser().resolve() if args.output_root else default_output_root(data_root).resolve()
    input_root = args.input_root.expanduser().resolve() if args.input_root else default_input_root(output_root).resolve()
    out_root = step_output_root(output_root)

    if not input_root.exists():
        if args.dry_run:
            LOGGER.warning("输入根目录尚不存在：%s", input_root)
            return 0
        LOGGER.error("输入根目录不存在：%s", input_root)
        return 1

    trials = discover_trials(input_root)
    summary = RunSummary(found=len(trials))
    LOGGER.info("输入根目录：%s", input_root)
    LOGGER.info("输出根目录：%s", out_root)
    LOGGER.info("找到 %d 个含校正后电影的 trial。", len(trials))

    for trial in trials:
        out_dir = trial_output_dir(out_root, trial)
        try:
            status = process_trial(
                trial=trial,
                out_dir=out_dir,
                action=args.action,
                dry_run=args.dry_run,
                sigma_px=args.sigma_px,
                clip_negative=args.clip_negative,
                dpi=args.dpi,
            )
        except Exception as exc:
            LOGGER.exception("Failed trial %s: %s", trial.trial_id, exc)
            summary.failed += 1
            continue

        if status == "skipped":
            summary.skipped += 1
            LOGGER.info("[跳过] %s", trial.trial_id)
        else:
            summary.processed += 1
            LOGGER.info("[完成] %s", trial.trial_id)

    LOGGER.info("汇总：")
    LOGGER.info("  找到：%d", summary.found)
    LOGGER.info("  已处理或将处理：%d", summary.processed)
    LOGGER.info("  跳过：%d", summary.skipped)
    LOGGER.info("  失败：%d", summary.failed)
    return 1 if summary.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
