# @File (label="Select Root Directory", style="directory") rootDir
# @String (label="File Extension", value=".oir") ext
# @Integer (label="Max Threads", value=8) threads
# @String (label="Existing output mode", value="skip") existingMode

import os
import json
import glob
import shutil
import traceback

from java.lang import System
from ij import IJ
from ij.plugin import ZProjector, Duplicator
from loci.plugins import BF
from loci.plugins.in import ImporterOptions


# ============================================================
# 01_fiji_totif_worker.py
#
# Purpose
# -------
# Convert Olympus .oir recordings into TIF files readable by the
# downstream calcium-imaging pipeline.
#
# Output layout
# -------------
# For input:
#   DATA_ROOT/Processed_TIF_YYYYMMDD/<trial>/<trial>.oir
# or generally:
#   DATA_ROOT/<date_folder>/<trial>/<trial>.oir
#
# Output:
#   DATA_ROOT/Processed_TIF_<date_folder>/<trial>/
#       <title>_metadata.json
#       <title>_Max_Proj.tif
#       <title>_Stim_Analog.tif   # if channel 2 exists
#
# Existing-output behavior
# ------------------------
# existingMode = "skip"
#     Skip before opening .oir if required outputs already exist.
# existingMode = "overwrite"
#     Delete old step-01 outputs in the target folder, then rerun.
# existingMode = "keep"
#     Rerun without deleting old outputs.
#
# The skip check is intentionally placed BEFORE BF.openImagePlus(), because
# opening .oir in Bio-Formats Full RAM mode is the slow step.
# ============================================================


# -------------------- Configuration --------------------
VALID_EXISTING_MODES = set(["skip", "overwrite", "keep"])

# If True, strict skip requires Stim_Analog.tif for already-known two-channel
# outputs. Because we cannot know nC without opening the .oir, the default
# skip criterion is metadata + Max_Proj only. This is safer for mixed 1-channel
# and 2-channel datasets.
STRICT_REQUIRE_STIM_FOR_SKIP = False

# Files generated by this step and safe to remove in overwrite mode.
STEP01_OUTPUT_PATTERNS = [
    "*_metadata.json",
    "*_Max_Proj.tif",
    "*_Max_Proj.tiff",
    "*_Stim_Analog.tif",
    "*_Stim_Analog.tiff",
]
# -------------------------------------------------------


def _as_str(x):
    try:
        return str(x)
    except Exception:
        return ""


def normalize_existing_mode(mode):
    mode = _as_str(mode).strip().lower()
    if mode == "":
        mode = "skip"
    if mode not in VALID_EXISTING_MODES:
        print("[WARNING] Unknown existingMode='{}'; using 'skip'.".format(mode))
        mode = "skip"
    return mode


def strip_oir_extensions(filename):
    """
    Remove common Olympus/Bio-Formats sidecar extensions to infer the output title.
    """
    name = os.path.basename(filename)
    lower = name.lower()
    if lower.endswith(".oir"):
        return name[:-4]
    return os.path.splitext(name)[0]


def sanitize_title_from_filename(filename):
    """
    Match step 00 convention: remove spaces from trial/file names.
    """
    return strip_oir_extensions(filename).replace(" ", "")


def file_nonempty(path):
    return os.path.exists(path) and os.path.isfile(path) and os.path.getsize(path) > 0


def find_existing_file(output_dir_path, title, suffixes):
    for suffix in suffixes:
        p = os.path.join(output_dir_path, title + suffix)
        if file_nonempty(p):
            return p
    return None


def is_step01_done(output_dir_path, title):
    """
    Check whether the expensive OIR-to-TIF conversion is already complete.

    Default criterion:
      - metadata JSON exists and non-empty
      - Max_Proj TIF exists and non-empty

    Stim_Analog is not required by default because 1-channel recordings do not
    have it, and knowing whether a file has channel 2 would require opening the
    OIR, which defeats the purpose of skip.
    """
    meta = find_existing_file(output_dir_path, title, ["_metadata.json"])
    max_proj = find_existing_file(output_dir_path, title, ["_Max_Proj.tif", "_Max_Proj.tiff"])

    if meta is None or max_proj is None:
        return False

    if STRICT_REQUIRE_STIM_FOR_SKIP:
        stim = find_existing_file(output_dir_path, title, ["_Stim_Analog.tif", "_Stim_Analog.tiff"])
        if stim is None:
            return False

    return True


def clean_step01_outputs(output_dir_path):
    """
    Delete only outputs generated by this script.
    Do not remove downstream files.
    """
    if not os.path.exists(output_dir_path):
        return 0

    removed = 0
    for pattern in STEP01_OUTPUT_PATTERNS:
        for p in glob.glob(os.path.join(output_dir_path, pattern)):
            try:
                if os.path.isfile(p) or os.path.islink(p):
                    os.remove(p)
                    print("  Removed old file -> " + p)
                    removed += 1
                elif os.path.isdir(p):
                    shutil.rmtree(p)
                    print("  Removed old folder -> " + p)
                    removed += 1
            except Exception as e:
                print("  [WARNING] Failed to remove {}: {}".format(p, e))
    return removed


def save_metadata_json(imp, output_dir_path, title):
    cal = imp.getCalibration()

    width_px = int(imp.getWidth())
    height_px = int(imp.getHeight())
    nC = int(imp.getNChannels())
    nZ = int(imp.getNSlices())
    nT = int(imp.getNFrames())
    total_frames = int(imp.getStackSize())

    frame_interval = float(cal.frameInterval) if cal.frameInterval is not None else 0.0
    px_w = float(cal.pixelWidth) if cal.pixelWidth is not None else 0.0
    px_h = float(cal.pixelHeight) if cal.pixelHeight is not None else 0.0
    unit = str(cal.getUnit())

    if frame_interval > 0:
        fps = 1.0 / frame_interval
    else:
        fps = None
        print(
            "[WARNING] frame_interval=0 for '{}', fps set to null in metadata. "
            "Check Olympus calibration settings.".format(title)
        )

    fov_width_um = float(width_px * px_w)
    fov_height_um = float(height_px * px_h)

    if width_px > 0 and px_w > 0:
        pixel_size_um = float(px_w)
    else:
        pixel_size_um = None

    meta_dict = {
        "filename": str(title),
        "dimensions": {
            "width_pixel": width_px,
            "height_pixel": height_px,
            "channels": nC,
            "z_slices": nZ,
            "timepoints": nT,
            "total_frames": total_frames,
        },
        "temporal_calibration": {
            "frame_interval_sec": frame_interval,
            "fps": fps,
        },
        "physical_size": {
            "fov_width_um": fov_width_um,
            "fov_height_um": fov_height_um,
            "pixel_size_um": pixel_size_um,
            "unit": unit,
            # Backward-compatible fields used by older downstream scripts.
            "width": fov_width_um,
            "height": fov_height_um,
        },
    }

    json_path = os.path.join(output_dir_path, str(title) + "_metadata.json")

    try:
        json_str = json.dumps(meta_dict, indent=4)
        with open(json_path, "w") as f:
            f.write(json_str)
        print("Metadata JSON exported: " + json_path)
    except Exception as e:
        print("Failed to save JSON metadata: " + str(e))


def save_max_projection_single_channel(imp, output_path, nZ):
    zp = ZProjector(imp)
    zp.setMethod(ZProjector.MAX_METHOD)
    zp.setStopSlice(nZ)
    zp.doHyperStackProjection(True)
    imp_max = zp.getProjection()
    IJ.saveAsTiff(imp_max, output_path)
    imp_max.close()


def save_channel_z_projection(imp, channel_index, nZ, nT, output_path):
    imp_c = Duplicator().run(imp, channel_index, channel_index, 1, nZ, 1, nT)
    zp = ZProjector(imp_c)
    zp.setMethod(ZProjector.MAX_METHOD)
    zp.setStartSlice(1)
    zp.setStopSlice(nZ)
    zp.doHyperStackProjection(True)
    proj = zp.getProjection()
    IJ.saveAsTiff(proj, output_path)
    proj.close()
    imp_c.close()


def save_single_z_channel(imp, channel_index, nT, output_path):
    imp_c = Duplicator().run(imp, channel_index, channel_index, 1, 1, 1, nT)
    IJ.saveAsTiff(imp_c, output_path)
    imp_c.close()


def process_oir(file_path, output_dir_path):
    print("-" * 30)
    print("Opening (Full RAM Mode): " + file_path)

    options = ImporterOptions()
    options.setId(file_path)
    options.setGroupFiles(True)
    options.setOpenAllSeries(False)
    options.setVirtual(False)

    imp = None
    try:
        imps = BF.openImagePlus(options)
        if not imps:
            print("Failed to load: " + file_path)
            return False

        imp = imps[0]
        imp.setDisplayMode(IJ.GRAYSCALE)

        title = imp.getShortTitle().replace(" ", "")
        nZ = int(imp.getNSlices())
        nT = int(imp.getNFrames())
        nC = int(imp.getNChannels())

        save_metadata_json(imp, output_dir_path, title)
        print("Metadata: {} Channels, {} Z-Slices, {} Timepoints".format(nC, nZ, nT))

        max_proj_path = os.path.join(output_dir_path, title + "_Max_Proj.tif")
        stim_path = os.path.join(output_dir_path, title + "_Stim_Analog.tif")

        if nZ > 1:
            if nC == 1:
                print("Calculating Max Projection for single channel...")
                save_max_projection_single_channel(imp, max_proj_path, nZ)
                print("Projection saved: " + max_proj_path)

            elif nC == 2:
                print("Calculating Max Projections for each channel...")
                save_channel_z_projection(imp, 1, nZ, nT, max_proj_path)
                print("Channel 1 Max Projection saved: " + max_proj_path)

                save_channel_z_projection(imp, 2, nZ, nT, stim_path)
                print("Channel 2 Stim Analog saved: " + stim_path)

            else:
                print(
                    "[WARNING] {} channels detected (>2). "
                    "Saving channel 1 as Max_Proj.tif and channel 2 as Stim_Analog.tif; "
                    "channels 3+ are ignored.".format(nC)
                )
                save_channel_z_projection(imp, 1, nZ, nT, max_proj_path)
                print("Channel 1 Max Projection saved: " + max_proj_path)

                save_channel_z_projection(imp, 2, nZ, nT, stim_path)
                print("Channel 2 Stim Analog saved: " + stim_path)

        else:
            print("Only one Z-Slice detected. Saving individual channels as TIF.")
            if nC >= 1:
                save_single_z_channel(imp, 1, nT, max_proj_path)
                print("Channel 1 saved: " + max_proj_path)
            if nC >= 2:
                save_single_z_channel(imp, 2, nT, stim_path)
                print("Channel 2 saved: " + stim_path)

        return True

    except Exception as e:
        print("Processing error for " + file_path + ": " + str(e))
        traceback.print_exc()
        return False

    finally:
        try:
            if imp is not None:
                imp.close()
        except Exception:
            pass


def should_skip_or_prepare(file_path, target_dir, existing_mode):
    """
    Returns True if caller should skip processing this file.
    """
    title_guess = sanitize_title_from_filename(file_path)

    if not os.path.exists(target_dir):
        os.makedirs(target_dir)

    if existing_mode == "skip":
        if is_step01_done(target_dir, title_guess):
            print("[SKIP] Step 01 output already exists: {} -> {}".format(title_guess, target_dir))
            return True
        print("[RUN] Missing or incomplete Step 01 output: {}".format(title_guess))
        return False

    if existing_mode == "overwrite":
        print("[OVERWRITE] Cleaning old Step 01 outputs in: " + target_dir)
        clean_step01_outputs(target_dir)
        return False

    # existing_mode == "keep"
    print("[KEEP] Rerunning without deleting old outputs: {}".format(title_guess))
    return False


def infer_output_target(root_path, input_root, oir_filename):
    """
    Reproduce the original output layout:
      output_base = root_path / ("Processed_TIF_" + parent_dir_name)
      target_dir  = output_base / basename(input_root)

    Example:
      root_path = .../2026_olympus
      input_root = .../2026_olympus/20260204/Euprymna_retina_590_0001
      parent_dir_name = 20260204
      target_dir = .../2026_olympus/Processed_TIF_20260204/Euprymna_retina_590_0001
    """
    parent_dir_name = os.path.basename(os.path.dirname(input_root))
    trial_dir_name = os.path.basename(input_root)

    # If .oir files are directly inside a date folder rather than trial folders,
    # use the file stem as trial directory to avoid dumping many trials together.
    if trial_dir_name == parent_dir_name or trial_dir_name == os.path.basename(root_path):
        trial_dir_name = sanitize_title_from_filename(oir_filename)

    output_base = os.path.join(root_path, "Processed_TIF_" + parent_dir_name)
    target_dir = os.path.join(output_base, trial_dir_name.replace(" ", ""))
    return target_dir


def main():
    root_path = rootDir.getAbsolutePath()
    existing_mode = normalize_existing_mode(existingMode)

    print("\n" + "=" * 60)
    print("01 Fiji OIR-to-TIF worker")
    print("Root path     : " + root_path)
    print("Extension     : " + ext)
    print("Threads param : " + str(threads) + " (kept for compatibility; current loop is sequential)")
    print("Existing mode : " + existing_mode)
    print("=" * 60)

    n_found = 0
    n_skipped = 0
    n_done = 0
    n_failed = 0

    for root, dirs, files in os.walk(root_path):
        # Do not walk into generated output folders.
        dirs[:] = [d for d in dirs if not d.startswith("Processed_TIF_")]

        if "Processed_TIF_" in root:
            continue

        for f in files:
            if not f.lower().endswith(ext.lower()):
                continue

            n_found += 1
            file_path = os.path.join(root, f)
            target_dir = infer_output_target(root_path, root, f)

            try:
                if should_skip_or_prepare(file_path, target_dir, existing_mode):
                    n_skipped += 1
                    continue

                ok = process_oir(file_path, target_dir)
                if ok:
                    n_done += 1
                else:
                    n_failed += 1

            except Exception as e:
                print("[ERROR] Failed around file {}: {}".format(file_path, e))
                traceback.print_exc()
                n_failed += 1

            finally:
                System.gc()

    print("\n" + "=" * 60)
    print("BATCH PROCESSING COMPLETE")
    print("Found   : {}".format(n_found))
    print("Skipped : {}".format(n_skipped))
    print("Done    : {}".format(n_done))
    print("Failed  : {}".format(n_failed))
    print("=" * 60)


try:
    main()
except Exception as main_e:
    print("Main loop error: " + str(main_e))
    traceback.print_exc()
