#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Extract neuropil-corrected dF/F traces from suite2p outputs.

Default layout:
  input : DATA_ROOT/05_suite2p_roi_detection/
  output: DATA_ROOT/06_dff/

This step uses suite2p's own neuropil trace, Fneu.npy. It does not use manually
drawn neuropil ROIs. Existing outputs are skipped by default, and overwrite only
removes files generated by this step.

By default, ROI selection prefers step 05c curated ROI labels when available,
then falls back to suite2p iscell.npy. This keeps the raw suite2p output intact
while allowing downstream analysis to use the conservative ROI filter.
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import shutil
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd


LOGGER = logging.getLogger("extract_dff")

STEP_NAME = "06_dff"
STEP_OUTPUT_PATTERNS = (
    "*_roi_table.csv",
    "*_F_raw.npy",
    "*_Fneu.npy",
    "*_F_corrected.npy",
    "*_F0.npy",
    "*_dff.npy",
    "*_dff_traces.csv",
    "*_dff_summary.csv",
    "*_dff_heatmap.png",
    "*_dff_heatmap.pdf",
    "*_example_traces.png",
    "*_example_traces.pdf",
    "*_dff_summary.json",
    "*_metadata.json",
    "*_stim_events.csv",
    "*_stim_map.csv",
    "*_stim_pulse_events.csv",
)


@dataclass(frozen=True)
class TrialInput:
    trial_id: str
    rel_parent: Path
    input_dir: Path
    plane0_dir: Path
    f_path: Path
    fneu_path: Path
    iscell_path: Path
    stat_path: Path
    ops_path: Path
    metadata_path: Path | None
    stim_events_path: Path | None
    stim_map_path: Path | None
    stim_pulse_events_path: Path | None


@dataclass
class RunSummary:
    found: int = 0
    processed: int = 0
    skipped: int = 0
    failed: int = 0


def configure_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def default_output_root(data_root: Path) -> Path:
    return data_root


def default_input_root(output_root: Path) -> Path:
    return output_root / "05_suite2p_roi_detection"


def default_curated_root(output_root: Path) -> Path:
    return output_root / "05c_roi_quality_filter"


def step_output_root(output_root: Path) -> Path:
    return output_root / STEP_NAME


def trial_output_dir(step_root: Path, trial: TrialInput) -> Path:
    if str(trial.rel_parent) in ("", "."):
        return step_root / trial.trial_id
    return step_root / trial.rel_parent / trial.trial_id


def find_first_existing(folder: Path, patterns: tuple[str, ...]) -> Path | None:
    for pattern in patterns:
        matches = sorted(folder.glob(pattern))
        if matches:
            return matches[0]
    return None


def discover_trials(input_root: Path) -> list[TrialInput]:
    trials: list[TrialInput] = []
    for f_path in sorted(input_root.rglob("suite2p/plane0/F.npy")):
        plane0_dir = f_path.parent
        input_dir = plane0_dir.parent.parent
        trial_id = input_dir.name
        rel_parent = input_dir.parent.relative_to(input_root)
        trials.append(
            TrialInput(
                trial_id=trial_id,
                rel_parent=rel_parent,
                input_dir=input_dir,
                plane0_dir=plane0_dir,
                f_path=f_path,
                fneu_path=plane0_dir / "Fneu.npy",
                iscell_path=plane0_dir / "iscell.npy",
                stat_path=plane0_dir / "stat.npy",
                ops_path=plane0_dir / "ops.npy",
                metadata_path=find_first_existing(input_dir, ("*_metadata.json",)),
                stim_events_path=find_first_existing(input_dir, ("*_stim_events.csv",)),
                stim_map_path=find_first_existing(input_dir, ("*_stim_map.csv",)),
                stim_pulse_events_path=find_first_existing(input_dir, ("*_stim_pulse_events.csv",)),
            )
        )
    return trials


def required_outputs_done(out_dir: Path, trial_id: str) -> bool:
    required = (
        out_dir / f"{trial_id}_roi_table.csv",
        out_dir / f"{trial_id}_F_raw.npy",
        out_dir / f"{trial_id}_Fneu.npy",
        out_dir / f"{trial_id}_F_corrected.npy",
        out_dir / f"{trial_id}_F0.npy",
        out_dir / f"{trial_id}_dff.npy",
        out_dir / f"{trial_id}_dff_traces.csv",
        out_dir / f"{trial_id}_dff_summary.csv",
        out_dir / f"{trial_id}_dff_summary.json",
    )
    return all(path.exists() and path.stat().st_size > 0 for path in required)


def clean_step_outputs(out_dir: Path) -> int:
    if not out_dir.exists():
        return 0
    removed = 0
    for pattern in STEP_OUTPUT_PATTERNS:
        for path in out_dir.glob(pattern):
            if path.is_dir():
                shutil.rmtree(path)
                removed += 1
                LOGGER.info("Removed old step-06 folder: %s", path)
            elif path.is_file() or path.is_symlink():
                path.unlink()
                removed += 1
                LOGGER.info("Removed old step-06 file: %s", path)
    return removed


def copy_if_exists(src: Path | None, dst: Path) -> bool:
    if src is None or not src.exists():
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    LOGGER.info("Copied %s -> %s", src, dst)
    return True


def copy_sidecar_outputs(trial: TrialInput, out_dir: Path) -> None:
    copy_if_exists(trial.metadata_path, out_dir / f"{trial.trial_id}_metadata.json")
    copy_if_exists(trial.stim_events_path, out_dir / f"{trial.trial_id}_stim_events.csv")
    copy_if_exists(trial.stim_map_path, out_dir / f"{trial.trial_id}_stim_map.csv")
    copy_if_exists(trial.stim_pulse_events_path, out_dir / f"{trial.trial_id}_stim_pulse_events.csv")


def load_json(path: Path | None) -> dict:
    if path is None or not path.exists():
        return {}
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception as exc:
        LOGGER.warning("Could not read JSON %s: %s", path, exc)
        return {}


def safe_float(value, default: float | None = None) -> float | None:
    try:
        if value is None:
            return default
        out = float(value)
        return out if np.isfinite(out) else default
    except Exception:
        return default


def get_nested(mapping: dict, keys: tuple[str, ...]):
    current = mapping
    for key in keys:
        if not isinstance(current, dict):
            return None
        current = current.get(key)
    return current


def get_fps_from_metadata(meta: dict, ops: dict, default_fps: float) -> float:
    candidates = (
        get_nested(meta, ("temporal_calibration", "fps")),
        get_nested(meta, ("imaging", "fps")),
        get_nested(meta, ("acquisition", "fps")),
        meta.get("fps") if isinstance(meta, dict) else None,
        meta.get("frame_rate") if isinstance(meta, dict) else None,
        ops.get("fs") if isinstance(ops, dict) else None,
    )
    for candidate in candidates:
        fps = safe_float(candidate, None)
        if fps is not None and fps > 0:
            return float(fps)

    if isinstance(meta, dict):
        interval_candidates = (
            get_nested(meta, ("temporal_calibration", "frame_interval_sec")),
            get_nested(meta, ("temporal_calibration", "frame_interval")),
            meta.get("frame_interval_sec"),
            meta.get("frame_interval"),
        )
        for candidate in interval_candidates:
            dt = safe_float(candidate, None)
            if dt is not None and dt > 0:
                return float(1.0 / dt)

    return float(default_fps)


def read_csv_if_exists(path: Path | None) -> pd.DataFrame:
    if path is None or not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_csv(path)
    except Exception as exc:
        LOGGER.warning("Could not read CSV %s: %s", path, exc)
        return pd.DataFrame()


def load_ops(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        value = np.load(path, allow_pickle=True)
        item = value.item()
        return item if isinstance(item, dict) else {}
    except Exception:
        return {}


def validate_suite2p_arrays(trial: TrialInput) -> None:
    missing = [
        path.name
        for path in (trial.f_path, trial.fneu_path, trial.iscell_path, trial.stat_path, trial.ops_path)
        if not path.exists()
    ]
    if missing:
        raise FileNotFoundError(f"Missing required suite2p input(s): {', '.join(missing)}")


def load_suite2p_inputs(trial: TrialInput) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict]:
    validate_suite2p_arrays(trial)
    f_raw = np.load(trial.f_path, allow_pickle=True).astype(np.float32, copy=False)
    fneu = np.load(trial.fneu_path, allow_pickle=True).astype(np.float32, copy=False)
    iscell = np.load(trial.iscell_path, allow_pickle=True)
    stat = np.load(trial.stat_path, allow_pickle=True)
    ops = load_ops(trial.ops_path)

    if f_raw.ndim != 2 or fneu.ndim != 2:
        raise ValueError(f"F/Fneu must be 2D ROI x frame arrays, got F={f_raw.shape}, Fneu={fneu.shape}")
    if f_raw.shape != fneu.shape:
        raise ValueError(f"F and Fneu shape mismatch: {f_raw.shape} vs {fneu.shape}")
    if iscell.ndim != 2 or iscell.shape[0] != f_raw.shape[0]:
        raise ValueError(f"iscell.npy shape invalid: {iscell.shape}, expected rows={f_raw.shape[0]}")
    if len(stat) != f_raw.shape[0]:
        raise ValueError(f"stat.npy length mismatch: {len(stat)} vs n_roi={f_raw.shape[0]}")
    return f_raw, fneu, iscell, stat, ops


def curated_iscell_path(curated_root: Path, trial: TrialInput) -> Path:
    base = curated_root / trial.rel_parent / trial.trial_id
    return base / f"{trial.trial_id}_iscell_curated.npy"


def select_rois(
    iscell: np.ndarray,
    include_noncell: bool,
    roi_source: str,
    curated_path: Path | None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, str, str | None]:
    iscell_flag = iscell[:, 0].astype(bool)
    iscell_prob = iscell[:, 1].astype(float) if iscell.shape[1] >= 2 else np.full(iscell.shape[0], np.nan)
    selection_label = "suite2p_iscell"
    selection_path = None

    if roi_source == "all" or include_noncell:
        selected = np.arange(iscell.shape[0], dtype=int)
        return selected, iscell_flag, iscell_prob, "all_suite2p_roi", selection_path

    if roi_source in ("curated", "auto") and curated_path is not None and curated_path.exists():
        curated = np.load(curated_path, allow_pickle=True)
        if curated.ndim != 2 or curated.shape[0] != iscell.shape[0]:
            raise ValueError(
                f"Curated iscell shape invalid: {curated.shape}, expected rows={iscell.shape[0]}"
            )
        curated_flag = curated[:, 0].astype(bool)
        curated_prob = curated[:, 1].astype(float) if curated.shape[1] >= 2 else curated_flag.astype(float)
        selected = np.where(curated_flag)[0].astype(int)
        return selected, curated_flag, curated_prob, "05c_curated", str(curated_path)

    if roi_source == "curated":
        raise FileNotFoundError(f"Requested curated ROI source but file is missing: {curated_path}")

    selected = np.where(iscell_flag)[0].astype(int)
    return selected, iscell_flag, iscell_prob, selection_label, selection_path


def first_stim_start_sec(stim_events: pd.DataFrame) -> float | None:
    if stim_events.empty or "start_time_sec" not in stim_events.columns:
        return None
    values = pd.to_numeric(stim_events["start_time_sec"], errors="coerce").dropna()
    if values.empty:
        return None
    first = float(values.min())
    return first if first >= 0 else None


def compute_f0(
    f_corrected: np.ndarray,
    fps: float,
    stim_events: pd.DataFrame,
    f0_mode: str,
    f0_percentile: float,
    f0_window_sec: float,
    default_baseline_sec: float,
    min_baseline_frames: int,
) -> tuple[np.ndarray, dict]:
    info = {
        "f0_mode": f0_mode,
        "f0_percentile": float(f0_percentile),
        "f0_window_sec": float(f0_window_sec),
    }

    if f0_mode == "percentile":
        f0 = np.percentile(f_corrected, f0_percentile, axis=1, keepdims=True)
        return f0.astype(np.float32), info

    if f0_mode == "stim-baseline":
        start_sec = first_stim_start_sec(stim_events)
        if start_sec is None:
            baseline_frames = int(round(default_baseline_sec * fps))
        else:
            baseline_frames = int(np.floor(start_sec * fps))
        baseline_frames = min(max(baseline_frames, min_baseline_frames), f_corrected.shape[1])
        baseline = f_corrected[:, :baseline_frames]
        f0 = np.percentile(baseline, f0_percentile, axis=1, keepdims=True)
        info.update({"baseline_frames": int(baseline_frames), "first_stim_start_sec": start_sec})
        return f0.astype(np.float32), info

    window = max(1, int(round(f0_window_sec * fps)))
    rows = []
    for trace in f_corrected:
        series = pd.Series(trace)
        if f0_mode == "rolling-percentile":
            rows.append(
                series.rolling(window=window, center=True, min_periods=1)
                .quantile(f0_percentile / 100.0)
                .to_numpy(dtype=np.float32)
            )
        elif f0_mode == "rolling-median":
            rows.append(
                series.rolling(window=window, center=True, min_periods=1)
                .median()
                .to_numpy(dtype=np.float32)
            )
        else:
            raise ValueError(f"Unsupported f0_mode: {f0_mode}")
    info["rolling_window_frames"] = int(window)
    return np.vstack(rows).astype(np.float32), info


def compute_dff(f_corrected: np.ndarray, f0: np.ndarray, eps: float) -> np.ndarray:
    denominator = np.maximum(np.abs(f0), eps)
    return ((f_corrected - f0) / denominator).astype(np.float32)


def stat_xy(roi) -> tuple[float, float, int]:
    if not isinstance(roi, dict):
        return np.nan, np.nan, 0
    xpix = np.asarray(roi.get("xpix", []), dtype=float)
    ypix = np.asarray(roi.get("ypix", []), dtype=float)
    if len(xpix) and len(ypix):
        return float(np.mean(xpix)), float(np.mean(ypix)), int(len(xpix))
    med = roi.get("med", [np.nan, np.nan])
    y_mean = safe_float(med[0] if len(med) > 0 else None, np.nan)
    x_mean = safe_float(med[1] if len(med) > 1 else None, np.nan)
    return float(x_mean), float(y_mean), 0


def build_roi_table(
    trial_id: str,
    selected: np.ndarray,
    iscell_flag: np.ndarray,
    iscell_prob: np.ndarray,
    stat: np.ndarray,
    f_raw: np.ndarray,
    fneu: np.ndarray,
    f_corrected: np.ndarray,
    f0: np.ndarray,
    dff: np.ndarray,
) -> pd.DataFrame:
    rows = []
    f0_stat = f0 if f0.shape == dff.shape else np.repeat(f0, dff.shape[1], axis=1)
    for out_idx, suite2p_idx in enumerate(selected):
        x_mean, y_mean, npix = stat_xy(stat[suite2p_idx])
        trace = dff[out_idx]
        std_dff = float(np.nanstd(trace))
        max_dff = float(np.nanmax(trace))
        rows.append(
            {
                "trial_id": trial_id,
                "roi_id": out_idx + 1,
                "suite2p_original_id": int(suite2p_idx),
                "iscell": int(bool(iscell_flag[suite2p_idx])),
                "iscell_prob": float(iscell_prob[suite2p_idx]) if np.isfinite(iscell_prob[suite2p_idx]) else np.nan,
                "x_mean": x_mean,
                "y_mean": y_mean,
                "npix": npix,
                "mean_F": float(np.nanmean(f_raw[out_idx])),
                "mean_Fneu": float(np.nanmean(fneu[out_idx])),
                "mean_F_corrected": float(np.nanmean(f_corrected[out_idx])),
                "mean_F0": float(np.nanmean(f0_stat[out_idx])),
                "mean_dff": float(np.nanmean(trace)),
                "std_dff": std_dff,
                "max_dff": max_dff,
                "snr_like": float(max_dff / std_dff) if std_dff > 0 else np.nan,
            }
        )
    return pd.DataFrame(rows)


def write_dff_traces_csv(path: Path, dff: np.ndarray, fps: float) -> None:
    n_roi, n_frames = dff.shape
    fieldnames = ["frame", "time_sec"] + [f"roi_{i + 1:04d}" for i in range(n_roi)]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(fieldnames)
        for frame in range(n_frames):
            writer.writerow([frame, frame / fps, *dff[:, frame].tolist()])


def stim_spans(stim_events: pd.DataFrame) -> list[tuple[float, float]]:
    if stim_events.empty or "start_time_sec" not in stim_events.columns:
        return []
    spans = []
    for _, row in stim_events.iterrows():
        start = safe_float(row.get("start_time_sec"), None)
        if start is None:
            continue
        end = safe_float(row.get("end_time_sec"), None)
        duration = safe_float(row.get("duration_sec"), None)
        if end is None and duration is not None:
            end = start + duration
        if end is None or end < start:
            end = start
        spans.append((float(start), float(end)))
    return spans


def mark_stimuli(ax, stim_events: pd.DataFrame) -> None:
    for start, end in stim_spans(stim_events):
        if end > start:
            ax.axvspan(start, end, color="tab:orange", alpha=0.16, lw=0)
        else:
            ax.axvline(start, color="tab:orange", alpha=0.35, lw=0.8)


def save_dff_heatmap(
    dff: np.ndarray,
    fps: float,
    stim_events: pd.DataFrame,
    output_path: Path,
    trial_id: str,
    max_rois: int,
    dpi: int,
) -> None:
    import matplotlib.pyplot as plt

    if dff.size == 0:
        return
    heatmap = dff
    if max_rois > 0 and dff.shape[0] > max_rois:
        keep = np.argsort(np.nanmax(dff, axis=1))[::-1][:max_rois]
        heatmap = dff[keep]
    finite = heatmap[np.isfinite(heatmap)]
    vmin = float(np.nanpercentile(finite, 2)) if finite.size else -1.0
    vmax = float(np.nanpercentile(finite, 98)) if finite.size else 2.0
    if vmax <= vmin:
        vmax = vmin + 1e-6

    fig, ax = plt.subplots(figsize=(12, 6))
    im = ax.imshow(
        heatmap,
        aspect="auto",
        interpolation="nearest",
        cmap="viridis",
        extent=[0, heatmap.shape[1] / fps, heatmap.shape[0], 0],
        vmin=vmin,
        vmax=vmax,
    )
    mark_stimuli(ax, stim_events)
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("ROI")
    ax.set_title(f"dF/F heatmap - {trial_id}")
    fig.colorbar(im, ax=ax, label="dF/F")
    plt.tight_layout()
    try:
        fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
        fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")
    finally:
        plt.close(fig)


def choose_example_rois(roi_table: pd.DataFrame, n_roi: int, seed: int) -> list[int]:
    if n_roi <= 0:
        return []
    choices: list[int] = []
    if "max_dff" in roi_table:
        choices.append(int(pd.to_numeric(roi_table["max_dff"], errors="coerce").idxmax()))
    if "snr_like" in roi_table:
        snr = pd.to_numeric(roi_table["snr_like"], errors="coerce")
        if snr.notna().any():
            choices.append(int(snr.idxmax()))
    choices.append(int(np.random.default_rng(seed).integers(0, n_roi)))
    out = []
    for idx in choices:
        if 0 <= idx < n_roi and idx not in out:
            out.append(idx)
    return out


def save_example_traces(
    dff: np.ndarray,
    roi_table: pd.DataFrame,
    fps: float,
    stim_events: pd.DataFrame,
    output_path: Path,
    trial_id: str,
    seed: int,
    dpi: int,
) -> None:
    import matplotlib.pyplot as plt

    indices = choose_example_rois(roi_table, dff.shape[0], seed=seed)
    if not indices:
        return
    time_axis = np.arange(dff.shape[1]) / fps
    fig, axes = plt.subplots(len(indices), 1, figsize=(12, max(3, 1.9 * len(indices))), sharex=True)
    if len(indices) == 1:
        axes = [axes]
    for ax, idx in zip(axes, indices):
        mark_stimuli(ax, stim_events)
        ax.plot(time_axis, dff[idx], lw=0.9, color="tab:blue")
        row = roi_table.iloc[idx]
        ax.set_ylabel(
            f"ROI {int(row['roi_id'])}\ns2p {int(row['suite2p_original_id'])}",
            rotation=0,
            labelpad=36,
            va="center",
        )
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(f"Example dF/F traces - {trial_id}", y=0.995)
    plt.tight_layout()
    try:
        fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
        fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")
    finally:
        plt.close(fig)


def process_trial(trial: TrialInput, out_dir: Path, args: argparse.Namespace) -> tuple[str, dict]:
    out_dir.mkdir(parents=True, exist_ok=True)
    copy_sidecar_outputs(trial, out_dir)

    f_all, fneu_all, iscell, stat, ops = load_suite2p_inputs(trial)
    curated_path = curated_iscell_path(args.curated_root, trial) if args.curated_root else None
    selected, iscell_flag, iscell_prob, roi_source_used, roi_source_path = select_rois(
        iscell,
        include_noncell=args.include_noncell,
        roi_source=args.roi_source,
        curated_path=curated_path,
    )
    if len(selected) == 0:
        return "failed", {"trial_id": trial.trial_id, "status": "failed", "message": "No ROI selected after ROI filtering"}

    meta = load_json(trial.metadata_path)
    stim_events = read_csv_if_exists(trial.stim_events_path)
    fps = get_fps_from_metadata(meta, ops=ops, default_fps=args.default_fps)

    f_raw = f_all[selected]
    fneu = fneu_all[selected]
    f_corrected = (f_raw - args.neuropil_coeff * fneu).astype(np.float32)
    f0, f0_info = compute_f0(
        f_corrected=f_corrected,
        fps=fps,
        stim_events=stim_events,
        f0_mode=args.f0_mode,
        f0_percentile=args.f0_percentile,
        f0_window_sec=args.f0_window_sec,
        default_baseline_sec=args.default_baseline_sec,
        min_baseline_frames=args.min_baseline_frames,
    )
    dff = compute_dff(f_corrected, f0=f0, eps=args.f0_eps)

    np.save(out_dir / f"{trial.trial_id}_F_raw.npy", f_raw)
    np.save(out_dir / f"{trial.trial_id}_Fneu.npy", fneu)
    np.save(out_dir / f"{trial.trial_id}_F_corrected.npy", f_corrected)
    np.save(out_dir / f"{trial.trial_id}_F0.npy", f0)
    np.save(out_dir / f"{trial.trial_id}_dff.npy", dff)

    roi_table = build_roi_table(
        trial_id=trial.trial_id,
        selected=selected,
        iscell_flag=iscell_flag,
        iscell_prob=iscell_prob,
        stat=stat,
        f_raw=f_raw,
        fneu=fneu,
        f_corrected=f_corrected,
        f0=f0,
        dff=dff,
    )
    roi_table.to_csv(out_dir / f"{trial.trial_id}_roi_table.csv", index=False)
    write_dff_traces_csv(out_dir / f"{trial.trial_id}_dff_traces.csv", dff=dff, fps=fps)

    summary = {
        "trial_id": trial.trial_id,
        "status": "ok",
        "n_roi_total": int(f_all.shape[0]),
        "n_roi_selected": int(len(selected)),
        "n_frames": int(f_all.shape[1]),
        "fps": float(fps),
        "duration_sec": float(f_all.shape[1] / fps),
        "include_noncell": bool(args.include_noncell),
        "roi_source_requested": args.roi_source,
        "roi_source_used": roi_source_used,
        "roi_source_path": roi_source_path,
        "neuropil_source": "suite2p_Fneu.npy",
        "neuropil_coeff": float(args.neuropil_coeff),
        "f0_eps": float(args.f0_eps),
        "mean_dff": float(np.nanmean(dff)),
        "max_dff": float(np.nanmax(dff)),
        "mean_snr_like": float(pd.to_numeric(roi_table["snr_like"], errors="coerce").mean()),
        "metadata_path": str(trial.metadata_path) if trial.metadata_path else None,
        "stim_events_path": str(trial.stim_events_path) if trial.stim_events_path else None,
        "suite2p_plane0": str(trial.plane0_dir),
        **f0_info,
    }
    pd.DataFrame([summary]).to_csv(out_dir / f"{trial.trial_id}_dff_summary.csv", index=False)

    save_dff_heatmap(
        dff=dff,
        fps=fps,
        stim_events=stim_events,
        output_path=out_dir / f"{trial.trial_id}_dff_heatmap.png",
        trial_id=trial.trial_id,
        max_rois=args.heatmap_max_rois,
        dpi=args.dpi,
    )
    save_example_traces(
        dff=dff,
        roi_table=roi_table,
        fps=fps,
        stim_events=stim_events,
        output_path=out_dir / f"{trial.trial_id}_example_traces.png",
        trial_id=trial.trial_id,
        seed=args.random_seed,
        dpi=args.dpi,
    )

    with (out_dir / f"{trial.trial_id}_dff_summary.json").open("w", encoding="utf-8") as handle:
        json.dump({**summary, "selected_suite2p_indices": selected.astype(int).tolist()}, handle, indent=2)
    return "processed", summary


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Extract neuropil-corrected dF/F traces from suite2p outputs.")
    parser.add_argument("--data-root", type=Path, required=True, help="Original data root.")
    parser.add_argument("--input-root", type=Path, help="Step-05 suite2p root. Default: OUTPUT_ROOT/05_suite2p_roi_detection.")
    parser.add_argument("--output-root", type=Path, help="Pipeline output root. Default: DATA_ROOT.")
    parser.add_argument("--curated-root", type=Path, help="Step-05c curated ROI root. Default: OUTPUT_ROOT/05c_roi_quality_filter.")
    parser.add_argument("--action", choices=("skip", "overwrite"), default="skip", help="Existing-output behavior.")
    parser.add_argument("--dry-run", action="store_true", help="Print work plan without reading suite2p arrays or writing files.")
    parser.add_argument(
        "--roi-source",
        choices=("auto", "curated", "suite2p", "all"),
        default="auto",
        help="ROI selection source. auto uses 05c curated labels when present, otherwise suite2p iscell.",
    )
    parser.add_argument("--include-noncell", action="store_true", help="Keep all suite2p ROIs instead of only iscell==1.")
    parser.add_argument("--neuropil-coeff", type=float, default=0.7, help="Coefficient for suite2p Fneu subtraction.")
    parser.add_argument(
        "--f0-mode",
        choices=("percentile", "rolling-percentile", "rolling-median", "stim-baseline"),
        default="percentile",
        help="F0 estimation method.",
    )
    parser.add_argument("--f0-percentile", type=float, default=10.0, help="Percentile used by percentile-based F0 modes.")
    parser.add_argument("--f0-window-sec", type=float, default=60.0, help="Rolling F0 window size in seconds.")
    parser.add_argument("--f0-eps", type=float, default=1e-6, help="Minimum denominator for dF/F.")
    parser.add_argument("--default-fps", type=float, default=2.0, help="Fallback fps when metadata and ops are missing.")
    parser.add_argument("--default-baseline-sec", type=float, default=10.0, help="Fallback baseline duration for stim-baseline mode.")
    parser.add_argument("--min-baseline-frames", type=int, default=5, help="Minimum baseline frames for stim-baseline mode.")
    parser.add_argument("--heatmap-max-rois", type=int, default=300, help="Maximum ROIs shown in heatmap; 0 means all.")
    parser.add_argument("--dpi", type=int, default=150, help="Figure DPI.")
    parser.add_argument("--random-seed", type=int, default=0, help="Seed for choosing one random example trace.")
    parser.add_argument("--verbose", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose)

    data_root = args.data_root.expanduser().resolve()
    output_root = args.output_root.expanduser().resolve() if args.output_root else default_output_root(data_root).resolve()
    input_root = args.input_root.expanduser().resolve() if args.input_root else default_input_root(output_root).resolve()
    args.curated_root = args.curated_root.expanduser().resolve() if args.curated_root else default_curated_root(output_root).resolve()
    out_root = step_output_root(output_root)

    if not input_root.exists():
        if args.dry_run:
            LOGGER.warning("Input root does not exist yet: %s", input_root)
            return 0
        LOGGER.error("Input root does not exist: %s", input_root)
        return 1

    trials = discover_trials(input_root)
    summary = RunSummary(found=len(trials))
    rows: list[dict] = []

    LOGGER.info("Input root : %s", input_root)
    LOGGER.info("Curated root: %s", args.curated_root)
    LOGGER.info("Output root: %s", out_root)
    LOGGER.info("Found %d trial(s) with suite2p F.npy.", len(trials))

    for trial in trials:
        out_dir = trial_output_dir(out_root, trial)
        if required_outputs_done(out_dir, trial.trial_id) and args.action == "skip":
            summary.skipped += 1
            LOGGER.info("[skip] %s", trial.trial_id)
            continue

        if args.dry_run:
            summary.processed += 1
            LOGGER.info("[dry-run] Would extract dF/F from %s -> %s", trial.plane0_dir, out_dir)
            continue

        if args.action == "overwrite":
            clean_step_outputs(out_dir)

        try:
            status, row = process_trial(trial, out_dir, args)
            rows.append(row)
            if status == "processed":
                summary.processed += 1
                LOGGER.info("[ok] %s: n_roi=%s n_frames=%s", trial.trial_id, row.get("n_roi_selected"), row.get("n_frames"))
            elif status == "skipped":
                summary.skipped += 1
                LOGGER.info("[skip] %s: %s", trial.trial_id, row.get("message"))
            else:
                summary.failed += 1
                LOGGER.error("[failed] %s: %s", trial.trial_id, row.get("message"))
        except Exception as exc:
            summary.failed += 1
            LOGGER.exception("[failed] %s: %s", trial.trial_id, exc)
            rows.append({"trial_id": trial.trial_id, "status": "failed", "message": str(exc)})

    if rows:
        out_root.mkdir(parents=True, exist_ok=True)
        pd.DataFrame(rows).to_csv(out_root / "dff_summary.csv", index=False)

    LOGGER.info("Summary:")
    LOGGER.info("  found: %d", summary.found)
    LOGGER.info("  processed or would process: %d", summary.processed)
    LOGGER.info("  skipped: %d", summary.skipped)
    LOGGER.info("  failed: %d", summary.failed)
    return 1 if summary.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
