import subprocess
import os
import sys

# ============================================================
# 01_fiji_totif_ini.py
#
# Purpose
# -------
# Launch Fiji/ImageJ in headless mode and run 01_fiji_totif_worker.py.
#
# Main change
# -----------
# Adds EXISTING_MODE and passes it to the Fiji worker.
# The actual skip check is done inside the worker BEFORE Bio-Formats opens
# the .oir file, which is the expensive part.
# ============================================================

# -------------------- Configuration --------------------
# 1. Fiji executable path on the Linux workstation.
FIJI_PATH = "/home/yifei/Fiji/fiji-linux-x64"

# 2. Fiji worker script path.
WORKER_SCRIPT = "/mnt/50d357b2-473b-4533-8c74-1db99704876a/yifeiding/calcium_imaging/olympus_code/20260318_code/01_fiji_totif_worker.py"

# 3. Data root. The worker recursively searches .oir files under this folder.
DATA_ROOT = "/mnt/50d357b2-473b-4533-8c74-1db99704876a/yifeiding/calcium_imaging/2026_olympus"

# 4. Kept for compatibility with the Fiji parameter interface.
# The current worker processes files sequentially; this is not true parallelism.
MAX_THREADS = 30

# 5. Existing-output behavior.
#    "skip"       : skip trial if required output files already exist and are non-empty
#    "overwrite"  : delete old outputs generated by step 01, then rerun
#    "keep"       : rerun without deleting old outputs; normally not recommended
EXISTING_MODE = "skip"

# 6. Input extension.
EXTENSION = ".oir"
# -------------------------------------------------------


def _quote_for_fiji(value):
    """Escape single quotes for Fiji --run argument strings."""
    return str(value).replace("'", "\\'")


def run_fiji_task(
    fiji_bin,
    script_path,
    root_dir,
    extension=".oir",
    threads=8,
    existing_mode="skip",
):
    """
    Run Fiji headless with the worker script.
    """
    abs_root = os.path.abspath(root_dir)
    abs_script = os.path.abspath(script_path)

    if existing_mode not in {"skip", "overwrite", "keep"}:
        raise ValueError("EXISTING_MODE must be one of: skip, overwrite, keep")

    args = (
        "rootDir='{}',ext='{}',threads={},existingMode='{}'".format(
            _quote_for_fiji(abs_root),
            _quote_for_fiji(extension),
            int(threads),
            _quote_for_fiji(existing_mode),
        )
    )

    command = [
        fiji_bin,
        "--headless",
        "--run",
        abs_script,
        args,
    ]

    print("\n" + "=" * 60)
    print("Launching Fiji Task...")
    print("Fiji binary     : {}".format(fiji_bin))
    print("Worker script   : {}".format(abs_script))
    print("Target directory: {}".format(abs_root))
    print("Extension       : {}".format(extension))
    print("Existing mode   : {}".format(existing_mode))
    print("=" * 60)

    process = subprocess.Popen(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    try:
        for line in process.stdout:
            sys.stdout.write(line)
            sys.stdout.flush()
        process.wait()
    except KeyboardInterrupt:
        print("\nInterrupted by user. Terminating Fiji process...")
        process.terminate()
        process.wait()
        raise

    if process.returncode == 0:
        print("\nSUCCESS: Fiji task completed.")
        return True

    print("\nERROR: Fiji task failed with return code {}".format(process.returncode))
    return False


if __name__ == "__main__":
    if not os.path.exists(FIJI_PATH):
        print("Error: Fiji binary not found at " + FIJI_PATH)
        sys.exit(1)

    if not os.path.exists(WORKER_SCRIPT):
        print("Error: worker script not found at " + WORKER_SCRIPT)
        sys.exit(1)

    ok = run_fiji_task(
        FIJI_PATH,
        WORKER_SCRIPT,
        DATA_ROOT,
        extension=EXTENSION,
        threads=MAX_THREADS,
        existing_mode=EXISTING_MODE,
    )
    sys.exit(0 if ok else 1)
