#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Extract neuropil-corrected dF/F traces from suite2p outputs.

Default layout:
  input : DATA_ROOT/05_suite2p_roi_detection/
  output: DATA_ROOT/06_dff/

By default, this step uses suite2p only for ROI position/shape and extracts
fluorescence again from the motion-corrected movie. This keeps suite2p detection
free to use a spatial high-pass image while downstream traces still come from
the biologically meaningful corrected movie. Existing outputs are skipped by
default, and overwrite only removes files generated by this step.

By default, ROI selection uses the manual curation output when it exists, then
falls back to suite2p iscell.npy. Manual curation provides ROI position/shape;
traces are still extracted from the motion-corrected movie.
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import shutil
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import tifffile as tf


LOGGER = logging.getLogger("extract_dff")

STEP_NAME = "06_dff"
STEP_OUTPUT_PATTERNS = (
    "*_roi_table.csv",
    "*_F_raw.npy",
    "*_Fneu.npy",
    "*_F_corrected.npy",
    "*_F0.npy",
    "*_dff.npy",
    "*_dff_traces.csv",
    "*_dff_summary.csv",
    "*_dff_heatmap.png",
    "*_dff_heatmap.pdf",
    "*_example_traces.png",
    "*_example_traces.pdf",
    "*_dff_summary.json",
    "*_metadata.json",
    "*_stim_events.csv",
    "*_stim_map.csv",
    "*_stim_pulse_events.csv",
)


@dataclass(frozen=True)
class TrialInput:
    trial_id: str
    rel_parent: Path
    input_dir: Path
    plane0_dir: Path
    f_path: Path
    fneu_path: Path
    iscell_path: Path
    stat_path: Path
    ops_path: Path
    metadata_path: Path | None
    stim_events_path: Path | None
    stim_map_path: Path | None
    stim_pulse_events_path: Path | None


@dataclass
class RunSummary:
    found: int = 0
    processed: int = 0
    skipped: int = 0
    failed: int = 0


def configure_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def default_output_root(data_root: Path) -> Path:
    return data_root


def default_input_root(output_root: Path) -> Path:
    return output_root / "05_suite2p_roi_detection"


def default_manual_root(output_root: Path) -> Path:
    return output_root / "05e_roi_manual_curation"


def step_output_root(output_root: Path) -> Path:
    return output_root / STEP_NAME


def trial_output_dir(step_root: Path, trial: TrialInput) -> Path:
    if str(trial.rel_parent) in ("", "."):
        return step_root / trial.trial_id
    return step_root / trial.rel_parent / trial.trial_id


def find_first_existing(folder: Path, patterns: tuple[str, ...]) -> Path | None:
    for pattern in patterns:
        matches = sorted(folder.glob(pattern))
        if matches:
            return matches[0]
    return None


def discover_trials(input_root: Path) -> list[TrialInput]:
    trials: list[TrialInput] = []
    for f_path in sorted(input_root.rglob("suite2p/plane0/F.npy")):
        plane0_dir = f_path.parent
        input_dir = plane0_dir.parent.parent
        trial_id = input_dir.name
        rel_parent = input_dir.parent.relative_to(input_root)
        trials.append(
            TrialInput(
                trial_id=trial_id,
                rel_parent=rel_parent,
                input_dir=input_dir,
                plane0_dir=plane0_dir,
                f_path=f_path,
                fneu_path=plane0_dir / "Fneu.npy",
                iscell_path=plane0_dir / "iscell.npy",
                stat_path=plane0_dir / "stat.npy",
                ops_path=plane0_dir / "ops.npy",
                metadata_path=find_first_existing(input_dir, ("*_metadata.json",)),
                stim_events_path=find_first_existing(input_dir, ("*_stim_events.csv",)),
                stim_map_path=find_first_existing(input_dir, ("*_stim_map.csv",)),
                stim_pulse_events_path=find_first_existing(input_dir, ("*_stim_pulse_events.csv",)),
            )
        )
    return trials


def required_outputs_done(out_dir: Path, trial_id: str) -> bool:
    required = (
        out_dir / f"{trial_id}_roi_table.csv",
        out_dir / f"{trial_id}_F_raw.npy",
        out_dir / f"{trial_id}_Fneu.npy",
        out_dir / f"{trial_id}_F_corrected.npy",
        out_dir / f"{trial_id}_F0.npy",
        out_dir / f"{trial_id}_dff.npy",
        out_dir / f"{trial_id}_dff_traces.csv",
        out_dir / f"{trial_id}_dff_summary.csv",
        out_dir / f"{trial_id}_dff_summary.json",
    )
    return all(path.exists() and path.stat().st_size > 0 for path in required)


def clean_step_outputs(out_dir: Path) -> int:
    if not out_dir.exists():
        return 0
    removed = 0
    for pattern in STEP_OUTPUT_PATTERNS:
        for path in out_dir.glob(pattern):
            if path.is_dir():
                shutil.rmtree(path)
                removed += 1
                LOGGER.info("Removed old step-06 folder: %s", path)
            elif path.is_file() or path.is_symlink():
                path.unlink()
                removed += 1
                LOGGER.info("Removed old step-06 file: %s", path)
    return removed


def copy_if_exists(src: Path | None, dst: Path) -> bool:
    if src is None or not src.exists():
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    LOGGER.info("Copied %s -> %s", src, dst)
    return True


def copy_sidecar_outputs(trial: TrialInput, out_dir: Path) -> None:
    copy_if_exists(trial.metadata_path, out_dir / f"{trial.trial_id}_metadata.json")
    copy_if_exists(trial.stim_events_path, out_dir / f"{trial.trial_id}_stim_events.csv")
    copy_if_exists(trial.stim_map_path, out_dir / f"{trial.trial_id}_stim_map.csv")
    copy_if_exists(trial.stim_pulse_events_path, out_dir / f"{trial.trial_id}_stim_pulse_events.csv")


def load_json(path: Path | None) -> dict:
    if path is None or not path.exists():
        return {}
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception as exc:
        LOGGER.warning("Could not read JSON %s: %s", path, exc)
        return {}


def safe_float(value, default: float | None = None) -> float | None:
    try:
        if value is None:
            return default
        out = float(value)
        return out if np.isfinite(out) else default
    except Exception:
        return default


def get_nested(mapping: dict, keys: tuple[str, ...]):
    current = mapping
    for key in keys:
        if not isinstance(current, dict):
            return None
        current = current.get(key)
    return current


def get_fps_from_metadata(meta: dict, ops: dict, default_fps: float) -> float:
    candidates = (
        get_nested(meta, ("temporal_calibration", "fps")),
        get_nested(meta, ("imaging", "fps")),
        get_nested(meta, ("acquisition", "fps")),
        meta.get("fps") if isinstance(meta, dict) else None,
        meta.get("frame_rate") if isinstance(meta, dict) else None,
        ops.get("fs") if isinstance(ops, dict) else None,
    )
    for candidate in candidates:
        fps = safe_float(candidate, None)
        if fps is not None and fps > 0:
            return float(fps)

    if isinstance(meta, dict):
        interval_candidates = (
            get_nested(meta, ("temporal_calibration", "frame_interval_sec")),
            get_nested(meta, ("temporal_calibration", "frame_interval")),
            meta.get("frame_interval_sec"),
            meta.get("frame_interval"),
        )
        for candidate in interval_candidates:
            dt = safe_float(candidate, None)
            if dt is not None and dt > 0:
                return float(1.0 / dt)

    return float(default_fps)


def read_csv_if_exists(path: Path | None) -> pd.DataFrame:
    if path is None or not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_csv(path)
    except Exception as exc:
        LOGGER.warning("Could not read CSV %s: %s", path, exc)
        return pd.DataFrame()


def load_ops(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        value = np.load(path, allow_pickle=True)
        item = value.item()
        return item if isinstance(item, dict) else {}
    except Exception:
        return {}


def validate_suite2p_arrays(trial: TrialInput) -> None:
    missing = [
        path.name
        for path in (trial.f_path, trial.fneu_path, trial.iscell_path, trial.stat_path, trial.ops_path)
        if not path.exists()
    ]
    if missing:
        raise FileNotFoundError(f"Missing required suite2p input(s): {', '.join(missing)}")


def load_suite2p_inputs(trial: TrialInput) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict]:
    validate_suite2p_arrays(trial)
    f_raw = np.load(trial.f_path, allow_pickle=True).astype(np.float32, copy=False)
    fneu = np.load(trial.fneu_path, allow_pickle=True).astype(np.float32, copy=False)
    iscell = np.load(trial.iscell_path, allow_pickle=True)
    stat = np.load(trial.stat_path, allow_pickle=True)
    ops = load_ops(trial.ops_path)

    if f_raw.ndim != 2 or fneu.ndim != 2:
        raise ValueError(f"F/Fneu must be 2D ROI x frame arrays, got F={f_raw.shape}, Fneu={fneu.shape}")
    if f_raw.shape != fneu.shape:
        raise ValueError(f"F and Fneu shape mismatch: {f_raw.shape} vs {fneu.shape}")
    if iscell.ndim != 2 or iscell.shape[0] != f_raw.shape[0]:
        raise ValueError(f"iscell.npy shape invalid: {iscell.shape}, expected rows={f_raw.shape[0]}")
    if len(stat) != f_raw.shape[0]:
        raise ValueError(f"stat.npy length mismatch: {len(stat)} vs n_roi={f_raw.shape[0]}")
    return f_raw, fneu, iscell, stat, ops


def manual_plane0_dir(manual_root: Path, trial: TrialInput) -> Path:
    return manual_root / trial.rel_parent / trial.trial_id / "suite2p_compatible" / "plane0"


def load_manual_roi_inputs(
    manual_root: Path,
    trial: TrialInput,
) -> tuple[np.ndarray, np.ndarray, np.ndarray | None, np.ndarray | None, str] | None:
    plane0 = manual_plane0_dir(manual_root, trial)
    stat_path = plane0 / "stat.npy"
    if not stat_path.exists():
        return None

    stat = np.load(stat_path, allow_pickle=True)
    if len(stat) == 0:
        raise ValueError(f"Manual ROI stat.npy contains no ROI: {stat_path}")

    iscell_path = plane0 / "iscell.npy"
    if iscell_path.exists():
        iscell = np.load(iscell_path, allow_pickle=True)
    else:
        iscell = np.ones((len(stat), 2), dtype=np.float32)
    if iscell.ndim != 2 or iscell.shape[0] != len(stat):
        raise ValueError(f"Manual iscell shape invalid: {iscell.shape}, expected rows={len(stat)}")

    f_path = plane0 / "F.npy"
    fneu_path = plane0 / "Fneu.npy"
    f_raw = np.load(f_path, allow_pickle=True).astype(np.float32, copy=False) if f_path.exists() else None
    fneu = np.load(fneu_path, allow_pickle=True).astype(np.float32, copy=False) if fneu_path.exists() else None
    return stat, iscell, f_raw, fneu, str(plane0)


def select_rois(
    iscell: np.ndarray,
    include_noncell: bool,
    roi_source: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, str, str | None]:
    iscell_flag = iscell[:, 0].astype(bool)
    iscell_prob = iscell[:, 1].astype(float) if iscell.shape[1] >= 2 else np.full(iscell.shape[0], np.nan)
    selection_label = "iscell"
    selection_path = None

    if roi_source == "all" or include_noncell:
        selected = np.arange(iscell.shape[0], dtype=int)
        return selected, iscell_flag, iscell_prob, "all_suite2p_roi", selection_path

    selected = np.where(iscell_flag)[0].astype(int)
    return selected, iscell_flag, iscell_prob, selection_label, selection_path


def corrected_movie_path(data_root: Path, trial: TrialInput, explicit_root: Path | None = None) -> Path | None:
    roots = []
    if explicit_root is not None:
        roots.append(explicit_root)
    roots.append(data_root / "03_motion_correct")

    patterns = (
        "*_corrected_movie.tif",
        "*_corrected_movie.tiff",
    )
    for root in roots:
        trial_dir = root / trial.rel_parent / trial.trial_id
        for pattern in patterns:
            matches = sorted(trial_dir.glob(pattern))
            if matches:
                return matches[0]
    return None


def movie_as_tyx(path: Path) -> np.ndarray:
    try:
        movie = tf.memmap(path)
    except Exception:
        movie = tf.imread(path)
    arr = np.asarray(movie)
    if arr.ndim == 2:
        arr = arr[np.newaxis, :, :]
    if arr.ndim == 3:
        return arr
    if arr.ndim == 4 and arr.shape[-1] in (1, 2, 3, 4):
        return arr[..., 0]
    raise ValueError(f"Expected movie shaped T x Y x X, got {arr.shape} from {path}")


def stat_mask(roi: object, shape_yx: tuple[int, int]) -> tuple[np.ndarray, np.ndarray]:
    mask = np.zeros(shape_yx, dtype=bool)
    weights = np.array([], dtype=np.float32)
    if not isinstance(roi, dict):
        return mask, weights
    ypix = np.asarray(roi.get("ypix", []), dtype=int)
    xpix = np.asarray(roi.get("xpix", []), dtype=int)
    valid = (ypix >= 0) & (ypix < shape_yx[0]) & (xpix >= 0) & (xpix < shape_yx[1])
    ypix = ypix[valid]
    xpix = xpix[valid]
    if len(ypix) == 0:
        return mask, weights
    mask[ypix, xpix] = True
    lam = np.asarray(roi.get("lam", []), dtype=np.float32)
    if len(lam) == len(valid):
        lam = lam[valid]
    if len(lam) != len(ypix) or not np.isfinite(lam).any() or float(np.nansum(lam)) <= 0:
        weights = np.ones(len(ypix), dtype=np.float32)
    else:
        weights = lam.astype(np.float32, copy=False)
    return mask, weights


def mean_trace_from_mask(movie: np.ndarray, mask: np.ndarray, weights: np.ndarray | None = None) -> np.ndarray:
    if not np.any(mask):
        return np.full((movie.shape[0],), np.nan, dtype=np.float32)
    pixels = np.asarray(movie[:, mask], dtype=np.float32)
    if weights is not None and len(weights) == pixels.shape[1]:
        total = float(np.nansum(weights))
        if total > 0:
            return np.asarray(np.nansum(pixels * weights[np.newaxis, :], axis=1) / total, dtype=np.float32)
    return np.asarray(np.nanmean(pixels, axis=1), dtype=np.float32)


def neuropil_mask(
    roi_mask: np.ndarray,
    all_roi_mask: np.ndarray,
    inner_radius: int,
    outer_radius: int,
    min_pixels: int,
) -> np.ndarray:
    try:
        from scipy import ndimage as ndi
    except Exception:
        ypix, xpix = np.where(roi_mask)
        out = np.zeros_like(roi_mask, dtype=bool)
        if len(ypix) == 0:
            return out
        y0 = max(0, int(ypix.min()) - outer_radius)
        y1 = min(roi_mask.shape[0], int(ypix.max()) + outer_radius + 1)
        x0 = max(0, int(xpix.min()) - outer_radius)
        x1 = min(roi_mask.shape[1], int(xpix.max()) + outer_radius + 1)
        out[y0:y1, x0:x1] = True
        out &= ~all_roi_mask
        return out

    inner_radius = max(1, int(inner_radius))
    outer_radius = max(inner_radius + 1, int(outer_radius))
    inner = ndi.binary_dilation(roi_mask, iterations=inner_radius)
    outer = ndi.binary_dilation(roi_mask, iterations=outer_radius)
    ring = outer & ~inner & ~all_roi_mask
    if int(np.count_nonzero(ring)) >= min_pixels:
        return ring

    expanded = ndi.binary_dilation(roi_mask, iterations=outer_radius * 2)
    ring = expanded & ~inner & ~all_roi_mask
    return ring


def extract_traces_from_corrected_movie(
    movie_path: Path,
    stat: np.ndarray,
    selected: np.ndarray,
    neuropil_inner_radius: int,
    neuropil_outer_radius: int,
    min_neuropil_pixels: int,
) -> tuple[np.ndarray, np.ndarray]:
    movie = movie_as_tyx(movie_path)
    shape_yx = tuple(movie.shape[-2:])
    roi_masks: list[np.ndarray] = []
    roi_weights: list[np.ndarray] = []
    all_roi_mask = np.zeros(shape_yx, dtype=bool)

    for suite2p_idx in selected:
        mask, weights = stat_mask(stat[int(suite2p_idx)], shape_yx)
        roi_masks.append(mask)
        roi_weights.append(weights)
        all_roi_mask |= mask

    f_rows = []
    fneu_rows = []
    for mask, weights in zip(roi_masks, roi_weights):
        f_rows.append(mean_trace_from_mask(movie, mask, weights))
        nmask = neuropil_mask(
            roi_mask=mask,
            all_roi_mask=all_roi_mask,
            inner_radius=neuropil_inner_radius,
            outer_radius=neuropil_outer_radius,
            min_pixels=min_neuropil_pixels,
        )
        fneu_rows.append(mean_trace_from_mask(movie, nmask, None))

    return np.vstack(f_rows).astype(np.float32), np.vstack(fneu_rows).astype(np.float32)


def first_stim_start_sec(stim_events: pd.DataFrame) -> float | None:
    if stim_events.empty or "start_time_sec" not in stim_events.columns:
        return None
    values = pd.to_numeric(stim_events["start_time_sec"], errors="coerce").dropna()
    if values.empty:
        return None
    first = float(values.min())
    return first if first >= 0 else None


def compute_f0(
    f_corrected: np.ndarray,
    fps: float,
    stim_events: pd.DataFrame,
    f0_mode: str,
    f0_percentile: float,
    f0_window_sec: float,
    default_baseline_sec: float,
    min_baseline_frames: int,
) -> tuple[np.ndarray, dict]:
    info = {
        "f0_mode": f0_mode,
        "f0_percentile": float(f0_percentile),
        "f0_window_sec": float(f0_window_sec),
    }

    if f0_mode == "percentile":
        f0 = np.percentile(f_corrected, f0_percentile, axis=1, keepdims=True)
        return f0.astype(np.float32), info

    if f0_mode == "stim-baseline":
        start_sec = first_stim_start_sec(stim_events)
        if start_sec is None:
            baseline_frames = int(round(default_baseline_sec * fps))
        else:
            baseline_frames = int(np.floor(start_sec * fps))
        baseline_frames = min(max(baseline_frames, min_baseline_frames), f_corrected.shape[1])
        baseline = f_corrected[:, :baseline_frames]
        f0 = np.percentile(baseline, f0_percentile, axis=1, keepdims=True)
        info.update({"baseline_frames": int(baseline_frames), "first_stim_start_sec": start_sec})
        return f0.astype(np.float32), info

    window = max(1, int(round(f0_window_sec * fps)))
    rows = []
    for trace in f_corrected:
        series = pd.Series(trace)
        if f0_mode == "rolling-percentile":
            rows.append(
                series.rolling(window=window, center=True, min_periods=1)
                .quantile(f0_percentile / 100.0)
                .to_numpy(dtype=np.float32)
            )
        elif f0_mode == "rolling-median":
            rows.append(
                series.rolling(window=window, center=True, min_periods=1)
                .median()
                .to_numpy(dtype=np.float32)
            )
        else:
            raise ValueError(f"Unsupported f0_mode: {f0_mode}")
    info["rolling_window_frames"] = int(window)
    return np.vstack(rows).astype(np.float32), info


def compute_dff(f_corrected: np.ndarray, f0: np.ndarray, eps: float) -> np.ndarray:
    denominator = np.maximum(np.abs(f0), eps)
    return ((f_corrected - f0) / denominator).astype(np.float32)


def stat_xy(roi) -> tuple[float, float, int]:
    if not isinstance(roi, dict):
        return np.nan, np.nan, 0
    xpix = np.asarray(roi.get("xpix", []), dtype=float)
    ypix = np.asarray(roi.get("ypix", []), dtype=float)
    if len(xpix) and len(ypix):
        return float(np.mean(xpix)), float(np.mean(ypix)), int(len(xpix))
    med = roi.get("med", [np.nan, np.nan])
    y_mean = safe_float(med[0] if len(med) > 0 else None, np.nan)
    x_mean = safe_float(med[1] if len(med) > 1 else None, np.nan)
    return float(x_mean), float(y_mean), 0


def safe_int(value, default: int = -1) -> int:
    try:
        if value is None:
            return default
        out = int(value)
        return out
    except Exception:
        return default


def stat_roi_metadata(roi: object, stat_index: int) -> dict:
    if not isinstance(roi, dict):
        return {
            "roi_source": "suite2p",
            "roi_type": "suite2p",
            "manual_roi_id": -1,
            "suite2p_original_id": int(stat_index),
            "previous_suite2p_original_id": -1,
            "source_roi_id": f"suite2p_{int(stat_index)}",
        }

    roi_source = str(roi.get("roi_source", "") or "").strip()
    if roi_source in {"suite2p_reference", "suite2p"} or (not roi_source and "manual_roi_id" not in roi):
        suite2p_id = safe_int(roi.get("suite2p_original_id"), int(stat_index))
        return {
            "roi_source": "suite2p",
            "roi_type": str(roi.get("roi_type", "suite2p") or "suite2p"),
            "manual_roi_id": -1,
            "suite2p_original_id": suite2p_id,
            "previous_suite2p_original_id": -1,
            "source_roi_id": str(roi.get("source_roi_id", f"suite2p_{suite2p_id}") or f"suite2p_{suite2p_id}"),
        }

    manual_id = safe_int(roi.get("manual_roi_id"), int(stat_index) + 1)
    previous_suite2p_id = safe_int(roi.get("previous_suite2p_original_id"), -1)
    if previous_suite2p_id < 0:
        previous_suite2p_id = safe_int(roi.get("suite2p_original_id"), -1)
    return {
        "roi_source": "manual",
        "roi_type": str(roi.get("roi_type", "manual") or "manual"),
        "manual_roi_id": manual_id,
        "suite2p_original_id": -1,
        "previous_suite2p_original_id": previous_suite2p_id,
        "source_roi_id": str(roi.get("source_roi_id", f"manual_{manual_id}") or f"manual_{manual_id}"),
    }


def build_roi_table(
    trial_id: str,
    selected: np.ndarray,
    iscell_flag: np.ndarray,
    iscell_prob: np.ndarray,
    stat: np.ndarray,
    f_raw: np.ndarray,
    fneu: np.ndarray,
    f_corrected: np.ndarray,
    f0: np.ndarray,
    dff: np.ndarray,
) -> pd.DataFrame:
    rows = []
    f0_stat = f0 if f0.shape == dff.shape else np.repeat(f0, dff.shape[1], axis=1)
    for out_idx, stat_idx in enumerate(selected):
        roi_stat = stat[int(stat_idx)]
        x_mean, y_mean, npix = stat_xy(roi_stat)
        metadata = stat_roi_metadata(roi_stat, int(stat_idx))
        trace = dff[out_idx]
        std_dff = float(np.nanstd(trace))
        max_dff = float(np.nanmax(trace))
        rows.append(
            {
                "trial_id": trial_id,
                "roi_id": out_idx + 1,
                "source_roi_id": metadata["source_roi_id"],
                "roi_source": metadata["roi_source"],
                "roi_type": metadata["roi_type"],
                "manual_roi_id": metadata["manual_roi_id"],
                "suite2p_original_id": metadata["suite2p_original_id"],
                "previous_suite2p_original_id": metadata["previous_suite2p_original_id"],
                "stat_index": int(stat_idx),
                "iscell": int(bool(iscell_flag[stat_idx])),
                "iscell_prob": float(iscell_prob[stat_idx]) if np.isfinite(iscell_prob[stat_idx]) else np.nan,
                "x_mean": x_mean,
                "y_mean": y_mean,
                "npix": npix,
                "mean_F": float(np.nanmean(f_raw[out_idx])),
                "mean_Fneu": float(np.nanmean(fneu[out_idx])),
                "mean_F_corrected": float(np.nanmean(f_corrected[out_idx])),
                "mean_F0": float(np.nanmean(f0_stat[out_idx])),
                "mean_dff": float(np.nanmean(trace)),
                "std_dff": std_dff,
                "max_dff": max_dff,
                "snr_like": float(max_dff / std_dff) if std_dff > 0 else np.nan,
            }
        )
    return pd.DataFrame(rows)


def write_dff_traces_csv(path: Path, dff: np.ndarray, fps: float) -> None:
    n_roi, n_frames = dff.shape
    fieldnames = ["frame", "time_sec"] + [f"roi_{i + 1:04d}" for i in range(n_roi)]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(fieldnames)
        for frame in range(n_frames):
            writer.writerow([frame, frame / fps, *dff[:, frame].tolist()])


def stim_spans(stim_events: pd.DataFrame) -> list[tuple[float, float]]:
    if stim_events.empty or "start_time_sec" not in stim_events.columns:
        return []
    spans = []
    for _, row in stim_events.iterrows():
        start = safe_float(row.get("start_time_sec"), None)
        if start is None:
            continue
        end = safe_float(row.get("end_time_sec"), None)
        duration = safe_float(row.get("duration_sec"), None)
        if end is None and duration is not None:
            end = start + duration
        if end is None or end < start:
            end = start
        spans.append((float(start), float(end)))
    return spans


def mark_stimuli(ax, stim_events: pd.DataFrame) -> None:
    for start, end in stim_spans(stim_events):
        if end > start:
            ax.axvspan(start, end, color="tab:orange", alpha=0.16, lw=0)
        else:
            ax.axvline(start, color="tab:orange", alpha=0.35, lw=0.8)


def save_dff_heatmap(
    dff: np.ndarray,
    fps: float,
    stim_events: pd.DataFrame,
    output_path: Path,
    trial_id: str,
    max_rois: int,
    dpi: int,
) -> None:
    import matplotlib.pyplot as plt

    if dff.size == 0:
        return
    heatmap = dff
    if max_rois > 0 and dff.shape[0] > max_rois:
        keep = np.argsort(np.nanmax(dff, axis=1))[::-1][:max_rois]
        heatmap = dff[keep]
    finite = heatmap[np.isfinite(heatmap)]
    vmin = float(np.nanpercentile(finite, 2)) if finite.size else -1.0
    vmax = float(np.nanpercentile(finite, 98)) if finite.size else 2.0
    if vmax <= vmin:
        vmax = vmin + 1e-6

    fig, ax = plt.subplots(figsize=(12, 6))
    im = ax.imshow(
        heatmap,
        aspect="auto",
        interpolation="nearest",
        cmap="viridis",
        extent=[0, heatmap.shape[1] / fps, heatmap.shape[0], 0],
        vmin=vmin,
        vmax=vmax,
    )
    mark_stimuli(ax, stim_events)
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("ROI")
    ax.set_title(f"dF/F heatmap - {trial_id}")
    fig.colorbar(im, ax=ax, label="dF/F")
    plt.tight_layout()
    try:
        fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
        fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")
    finally:
        plt.close(fig)


def choose_example_rois(roi_table: pd.DataFrame, n_roi: int, seed: int) -> list[int]:
    if n_roi <= 0:
        return []
    choices: list[int] = []
    if "max_dff" in roi_table:
        choices.append(int(pd.to_numeric(roi_table["max_dff"], errors="coerce").idxmax()))
    if "snr_like" in roi_table:
        snr = pd.to_numeric(roi_table["snr_like"], errors="coerce")
        if snr.notna().any():
            choices.append(int(snr.idxmax()))
    choices.append(int(np.random.default_rng(seed).integers(0, n_roi)))
    out = []
    for idx in choices:
        if 0 <= idx < n_roi and idx not in out:
            out.append(idx)
    return out


def save_example_traces(
    dff: np.ndarray,
    roi_table: pd.DataFrame,
    fps: float,
    stim_events: pd.DataFrame,
    output_path: Path,
    trial_id: str,
    seed: int,
    dpi: int,
) -> None:
    import matplotlib.pyplot as plt

    indices = choose_example_rois(roi_table, dff.shape[0], seed=seed)
    if not indices:
        return
    time_axis = np.arange(dff.shape[1]) / fps
    fig, axes = plt.subplots(len(indices), 1, figsize=(12, max(3, 1.9 * len(indices))), sharex=True)
    if len(indices) == 1:
        axes = [axes]
    for ax, idx in zip(axes, indices):
        mark_stimuli(ax, stim_events)
        ax.plot(time_axis, dff[idx], lw=0.9, color="tab:blue")
        row = roi_table.iloc[idx]
        roi_source = str(row.get("roi_source", "suite2p"))
        if roi_source == "manual":
            source_label = f"manual {int(row.get('manual_roi_id', row['roi_id']))}"
        else:
            source_label = f"s2p {int(row.get('suite2p_original_id', idx))}"
        ax.set_ylabel(
            f"ROI {int(row['roi_id'])}\n{source_label}",
            rotation=0,
            labelpad=36,
            va="center",
        )
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
    axes[-1].set_xlabel("Time (s)")
    fig.suptitle(f"Example dF/F traces - {trial_id}", y=0.995)
    plt.tight_layout()
    try:
        fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
        fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")
    finally:
        plt.close(fig)


def process_trial(trial: TrialInput, out_dir: Path, args: argparse.Namespace) -> tuple[str, dict]:
    out_dir.mkdir(parents=True, exist_ok=True)
    copy_sidecar_outputs(trial, out_dir)

    suite2p_f_all, suite2p_fneu_all, suite2p_iscell, suite2p_stat, ops = load_suite2p_inputs(trial)
    f_all = suite2p_f_all
    fneu_all = suite2p_fneu_all
    iscell = suite2p_iscell
    stat = suite2p_stat
    manual_source_path = None

    manual_inputs = None
    if args.roi_source in ("auto", "manual"):
        manual_inputs = load_manual_roi_inputs(args.manual_root, trial)
        if manual_inputs is None and args.roi_source == "manual":
            raise FileNotFoundError(f"Requested manual ROI source but no manual compatible output was found for {trial.trial_id}")
    if manual_inputs is not None:
        stat, iscell, manual_f, manual_fneu, manual_source_path = manual_inputs
        if manual_f is not None and manual_fneu is not None and manual_f.shape == manual_fneu.shape:
            f_all = manual_f
            fneu_all = manual_fneu
        else:
            n_frames = suite2p_f_all.shape[1]
            f_all = np.full((len(stat), n_frames), np.nan, dtype=np.float32)
            fneu_all = np.full((len(stat), n_frames), np.nan, dtype=np.float32)

    selected, iscell_flag, iscell_prob, roi_source_used, roi_source_path = select_rois(
        iscell,
        include_noncell=args.include_noncell,
        roi_source=args.roi_source,
    )
    if manual_inputs is not None:
        roi_source_used = "manual_curation"
        roi_source_path = manual_source_path
    if len(selected) == 0:
        return "failed", {"trial_id": trial.trial_id, "status": "failed", "message": "No ROI selected after ROI filtering"}

    meta = load_json(trial.metadata_path)
    stim_events = read_csv_if_exists(trial.stim_events_path)
    fps = get_fps_from_metadata(meta, ops=ops, default_fps=args.default_fps)

    trace_movie_path = None
    if args.trace_source == "motion-corrected":
        trace_movie_path = corrected_movie_path(args.data_root, trial, args.trace_movie_root)
        if trace_movie_path is None:
            raise FileNotFoundError(
                f"Could not find motion-corrected movie for {trial.trial_id}. "
                "Use --trace-source suite2p to fall back to suite2p F.npy/Fneu.npy."
            )
        f_raw, fneu = extract_traces_from_corrected_movie(
            movie_path=trace_movie_path,
            stat=stat,
            selected=selected,
            neuropil_inner_radius=args.neuropil_inner_radius,
            neuropil_outer_radius=args.neuropil_outer_radius,
            min_neuropil_pixels=args.min_neuropil_pixels,
        )
        trace_source_used = "motion_corrected_movie"
        neuropil_source = "local_annulus_from_motion_corrected_movie"
    else:
        f_raw = f_all[selected]
        fneu = fneu_all[selected]
        trace_source_used = "manual_or_suite2p_F.npy" if manual_inputs is not None else "suite2p_F.npy"
        neuropil_source = "manual_or_suite2p_Fneu.npy" if manual_inputs is not None else "suite2p_Fneu.npy"

    f_corrected = (f_raw - args.neuropil_coeff * fneu).astype(np.float32)
    f0, f0_info = compute_f0(
        f_corrected=f_corrected,
        fps=fps,
        stim_events=stim_events,
        f0_mode=args.f0_mode,
        f0_percentile=args.f0_percentile,
        f0_window_sec=args.f0_window_sec,
        default_baseline_sec=args.default_baseline_sec,
        min_baseline_frames=args.min_baseline_frames,
    )
    dff = compute_dff(f_corrected, f0=f0, eps=args.f0_eps)

    np.save(out_dir / f"{trial.trial_id}_F_raw.npy", f_raw)
    np.save(out_dir / f"{trial.trial_id}_Fneu.npy", fneu)
    np.save(out_dir / f"{trial.trial_id}_F_corrected.npy", f_corrected)
    np.save(out_dir / f"{trial.trial_id}_F0.npy", f0)
    np.save(out_dir / f"{trial.trial_id}_dff.npy", dff)

    roi_table = build_roi_table(
        trial_id=trial.trial_id,
        selected=selected,
        iscell_flag=iscell_flag,
        iscell_prob=iscell_prob,
        stat=stat,
        f_raw=f_raw,
        fneu=fneu,
        f_corrected=f_corrected,
        f0=f0,
        dff=dff,
    )
    roi_table.to_csv(out_dir / f"{trial.trial_id}_roi_table.csv", index=False)
    write_dff_traces_csv(out_dir / f"{trial.trial_id}_dff_traces.csv", dff=dff, fps=fps)

    summary = {
        "trial_id": trial.trial_id,
        "status": "ok",
        "n_suite2p_roi_total": int(suite2p_f_all.shape[0]),
        "n_roi_total": int(len(stat)),
        "n_roi_selected": int(len(selected)),
        "n_frames": int(dff.shape[1]),
        "fps": float(fps),
        "duration_sec": float(dff.shape[1] / fps),
        "include_noncell": bool(args.include_noncell),
        "roi_source_requested": args.roi_source,
        "roi_source_used": roi_source_used,
        "roi_source_path": roi_source_path,
        "trace_source": trace_source_used,
        "trace_movie_path": str(trace_movie_path) if trace_movie_path is not None else None,
        "neuropil_source": neuropil_source,
        "neuropil_coeff": float(args.neuropil_coeff),
        "f0_eps": float(args.f0_eps),
        "mean_dff": float(np.nanmean(dff)),
        "max_dff": float(np.nanmax(dff)),
        "mean_snr_like": float(pd.to_numeric(roi_table["snr_like"], errors="coerce").mean()),
        "metadata_path": str(trial.metadata_path) if trial.metadata_path else None,
        "stim_events_path": str(trial.stim_events_path) if trial.stim_events_path else None,
        "suite2p_plane0": str(trial.plane0_dir),
        "manual_root": str(args.manual_root),
        **f0_info,
    }
    pd.DataFrame([summary]).to_csv(out_dir / f"{trial.trial_id}_dff_summary.csv", index=False)

    save_dff_heatmap(
        dff=dff,
        fps=fps,
        stim_events=stim_events,
        output_path=out_dir / f"{trial.trial_id}_dff_heatmap.png",
        trial_id=trial.trial_id,
        max_rois=args.heatmap_max_rois,
        dpi=args.dpi,
    )
    save_example_traces(
        dff=dff,
        roi_table=roi_table,
        fps=fps,
        stim_events=stim_events,
        output_path=out_dir / f"{trial.trial_id}_example_traces.png",
        trial_id=trial.trial_id,
        seed=args.random_seed,
        dpi=args.dpi,
    )

    selected_records = roi_table[
        [
            "roi_id",
            "source_roi_id",
            "roi_source",
            "roi_type",
            "manual_roi_id",
            "suite2p_original_id",
            "previous_suite2p_original_id",
            "stat_index",
        ]
    ].to_dict(orient="records")
    with (out_dir / f"{trial.trial_id}_dff_summary.json").open("w", encoding="utf-8") as handle:
        json.dump(
            {
                **summary,
                "selected_roi_records": selected_records,
                "selected_suite2p_indices": [
                    int(value)
                    for value in roi_table["suite2p_original_id"].tolist()
                    if pd.notna(value) and int(value) >= 0
                ],
            },
            handle,
            indent=2,
        )
    return "processed", summary


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Extract neuropil-corrected dF/F traces from suite2p outputs.")
    parser.add_argument("--data-root", type=Path, required=True, help="Original data root.")
    parser.add_argument("--input-root", type=Path, help="Step-05 suite2p root. Default: OUTPUT_ROOT/05_suite2p_roi_detection.")
    parser.add_argument("--manual-root", type=Path, help="Manual ROI curation root. Default: OUTPUT_ROOT/05e_roi_manual_curation.")
    parser.add_argument("--output-root", type=Path, help="Pipeline output root. Default: DATA_ROOT.")
    parser.add_argument("--action", choices=("skip", "overwrite"), default="skip", help="Existing-output behavior.")
    parser.add_argument("--dry-run", action="store_true", help="Print work plan without reading suite2p arrays or writing files.")
    parser.add_argument(
        "--roi-source",
        choices=("auto", "manual", "suite2p", "all"),
        default="auto",
        help="ROI selection source. auto uses manual curation when present, otherwise suite2p iscell.",
    )
    parser.add_argument("--include-noncell", action="store_true", help="Keep all suite2p ROIs instead of only iscell==1.")
    parser.add_argument(
        "--trace-source",
        choices=("motion-corrected", "suite2p"),
        default="motion-corrected",
        help="Trace source. Default: use suite2p ROI shapes but extract F/Fneu from step-03 motion-corrected movies.",
    )
    parser.add_argument(
        "--trace-movie-root",
        type=Path,
        help="Optional root containing motion-corrected movies. Default: DATA_ROOT/03_motion_correct.",
    )
    parser.add_argument("--neuropil-coeff", type=float, default=0.7, help="Coefficient for suite2p Fneu subtraction.")
    parser.add_argument("--neuropil-inner-radius", type=int, default=2, help="Step 06 motion-corrected trace mode: pixels excluded around each ROI before neuropil sampling.")
    parser.add_argument("--neuropil-outer-radius", type=int, default=20, help="Step 06 motion-corrected trace mode: outer neuropil ring radius in pixels.")
    parser.add_argument("--min-neuropil-pixels", type=int, default=50, help="Step 06 motion-corrected trace mode: minimum neuropil pixels before expanding the ring.")
    parser.add_argument(
        "--f0-mode",
        choices=("percentile", "rolling-percentile", "rolling-median", "stim-baseline"),
        default="percentile",
        help="F0 estimation method.",
    )
    parser.add_argument("--f0-percentile", type=float, default=10.0, help="Percentile used by percentile-based F0 modes.")
    parser.add_argument("--f0-window-sec", type=float, default=60.0, help="Rolling F0 window size in seconds.")
    parser.add_argument("--f0-eps", type=float, default=1e-6, help="Minimum denominator for dF/F.")
    parser.add_argument("--default-fps", type=float, default=2.0, help="Fallback fps when metadata and ops are missing.")
    parser.add_argument("--default-baseline-sec", type=float, default=10.0, help="Fallback baseline duration for stim-baseline mode.")
    parser.add_argument("--min-baseline-frames", type=int, default=5, help="Minimum baseline frames for stim-baseline mode.")
    parser.add_argument("--heatmap-max-rois", type=int, default=300, help="Maximum ROIs shown in heatmap; 0 means all.")
    parser.add_argument("--dpi", type=int, default=150, help="Figure DPI.")
    parser.add_argument("--random-seed", type=int, default=0, help="Seed for choosing one random example trace.")
    parser.add_argument("--verbose", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose)

    data_root = args.data_root.expanduser().resolve()
    output_root = args.output_root.expanduser().resolve() if args.output_root else default_output_root(data_root).resolve()
    input_root = args.input_root.expanduser().resolve() if args.input_root else default_input_root(output_root).resolve()
    args.manual_root = args.manual_root.expanduser().resolve() if args.manual_root else default_manual_root(output_root).resolve()
    out_root = step_output_root(output_root)

    if not input_root.exists():
        if args.dry_run:
            LOGGER.warning("Input root does not exist yet: %s", input_root)
            return 0
        LOGGER.error("Input root does not exist: %s", input_root)
        return 1

    trials = discover_trials(input_root)
    summary = RunSummary(found=len(trials))
    rows: list[dict] = []

    LOGGER.info("Input root : %s", input_root)
    LOGGER.info("Manual root: %s", args.manual_root)
    LOGGER.info("Output root: %s", out_root)
    LOGGER.info("Found %d trial(s) with suite2p F.npy.", len(trials))

    for trial in trials:
        out_dir = trial_output_dir(out_root, trial)
        if required_outputs_done(out_dir, trial.trial_id) and args.action == "skip":
            summary.skipped += 1
            LOGGER.info("[skip] %s", trial.trial_id)
            continue

        if args.dry_run:
            summary.processed += 1
            LOGGER.info("[dry-run] Would extract dF/F from %s -> %s", trial.plane0_dir, out_dir)
            continue

        if args.action == "overwrite":
            clean_step_outputs(out_dir)

        try:
            status, row = process_trial(trial, out_dir, args)
            rows.append(row)
            if status == "processed":
                summary.processed += 1
                LOGGER.info("[ok] %s: n_roi=%s n_frames=%s", trial.trial_id, row.get("n_roi_selected"), row.get("n_frames"))
            elif status == "skipped":
                summary.skipped += 1
                LOGGER.info("[skip] %s: %s", trial.trial_id, row.get("message"))
            else:
                summary.failed += 1
                LOGGER.error("[failed] %s: %s", trial.trial_id, row.get("message"))
        except Exception as exc:
            summary.failed += 1
            LOGGER.exception("[failed] %s: %s", trial.trial_id, exc)
            rows.append({"trial_id": trial.trial_id, "status": "failed", "message": str(exc)})

    if rows:
        out_root.mkdir(parents=True, exist_ok=True)
        pd.DataFrame(rows).to_csv(out_root / "dff_summary.csv", index=False)

    LOGGER.info("Summary:")
    LOGGER.info("  found: %d", summary.found)
    LOGGER.info("  processed or would process: %d", summary.processed)
    LOGGER.info("  skipped: %d", summary.skipped)
    LOGGER.info("  failed: %d", summary.failed)
    return 1 if summary.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
