#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Extract neuropil-corrected dF/F traces from suite2p outputs.

Default layout:
  input : DATA_ROOT/05_suite2p_roi_detection/
  output: DATA_ROOT/06_dff/

By default, this step uses suite2p only for ROI position/shape and extracts
fluorescence again from the motion-corrected movie. This keeps suite2p detection
free to use a spatial high-pass image while downstream traces still come from
the biologically meaningful corrected movie. Existing outputs are skipped by
default, and overwrite only removes files generated by this step.

By default, ROI selection uses ``auto`` mode: final manual curation output is
preferred, and trials without final manual ROI fall back to suite2p ``iscell``
ROIs. Manual curation provides ROI position/shape; traces are still extracted
from the motion-corrected movie.
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import tifffile as tf


LOGGER = logging.getLogger("extract_dff")

STEP_NAME = "06_dff"
STEP_OUTPUT_PATTERNS = (
    "*_roi_table.csv",
    "*_F_raw.npy",
    "*_Fneu.npy",
    "*_F_corrected.npy",
    "*_F0.npy",
    "*_dff.npy",
    "*_dff_traces.csv",
    "*_dff_summary.csv",
    "*_dff_heatmap.png",
    "*_dff_heatmap.pdf",
    "*_dff_heatmap_sorted.png",
    "*_dff_heatmap_sorted.pdf",
    "*_example_traces.png",
    "*_example_traces.pdf",
    "*_dff_trace_examples_with_stim.png",
    "*_dff_trace_examples_with_stim.pdf",
    "*_dff_distribution.png",
    "*_dff_distribution.pdf",
    "*_neuropil_correction_examples.png",
    "*_neuropil_correction_examples.pdf",
    "*_artifact_regression_examples.png",
    "*_artifact_regression_examples.pdf",
    "*_artifact_qc_summary.png",
    "*_artifact_qc_summary.pdf",
    "*_artifact_components.csv",
    "*_roi_spatial_activity_map.png",
    "*_roi_spatial_activity_map.pdf",
    "*_dff_summary.json",
    "*_metadata.json",
    "*_stim_events.csv",
    "*_stim_map.csv",
    "*_stim_pulse_events.csv",
)


@dataclass(frozen=True)
class TrialInput:
    trial_id: str
    rel_parent: Path
    input_dir: Path
    plane0_dir: Path
    f_path: Path
    fneu_path: Path
    iscell_path: Path
    stat_path: Path
    ops_path: Path
    metadata_path: Path | None
    stim_events_path: Path | None
    stim_map_path: Path | None
    stim_pulse_events_path: Path | None


@dataclass
class RunSummary:
    found: int = 0
    processed: int = 0
    skipped: int = 0
    failed: int = 0


def configure_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def default_output_root(data_root: Path) -> Path:
    return data_root


def default_input_root(output_root: Path) -> Path:
    return output_root / "05_suite2p_roi_detection"


def default_manual_root(output_root: Path) -> Path:
    return output_root / "05e_roi_manual_curation"


def default_stim_root(output_root: Path) -> Path:
    return output_root / "02_stim_map"


def step_output_root(output_root: Path) -> Path:
    return output_root / STEP_NAME


def trial_output_dir(step_root: Path, trial: TrialInput) -> Path:
    if str(trial.rel_parent) in ("", "."):
        return step_root / trial.trial_id
    return step_root / trial.rel_parent / trial.trial_id


def find_first_existing(folder: Path, patterns: tuple[str, ...]) -> Path | None:
    for pattern in patterns:
        matches = sorted(folder.glob(pattern))
        if matches:
            return matches[0]
    return None


def find_stim_sidecar(folder: Path, trial_id: str, patterns: tuple[str, ...]) -> Path | None:
    preferred = tuple(f"{trial_id}{pattern[1:]}" if pattern.startswith("*") else pattern for pattern in patterns)
    found = find_first_existing(folder, preferred)
    if found is not None:
        return found
    return find_first_existing(folder, patterns)


def resolve_stim_sidecar(preferred_dir: Path, fallback_dir: Path, trial_id: str, patterns: tuple[str, ...]) -> Path | None:
    if preferred_dir.exists():
        found = find_stim_sidecar(preferred_dir, trial_id, patterns)
        if found is not None:
            return found
    return find_stim_sidecar(fallback_dir, trial_id, patterns)


def discover_trials(input_root: Path, stim_root: Path) -> list[TrialInput]:
    trials: list[TrialInput] = []
    for f_path in sorted(input_root.rglob("suite2p/plane0/F.npy")):
        plane0_dir = f_path.parent
        input_dir = plane0_dir.parent.parent
        trial_id = input_dir.name
        rel_parent = input_dir.parent.relative_to(input_root)
        stim_dir = stim_root / rel_parent / trial_id
        trials.append(
            TrialInput(
                trial_id=trial_id,
                rel_parent=rel_parent,
                input_dir=input_dir,
                plane0_dir=plane0_dir,
                f_path=f_path,
                fneu_path=plane0_dir / "Fneu.npy",
                iscell_path=plane0_dir / "iscell.npy",
                stat_path=plane0_dir / "stat.npy",
                ops_path=plane0_dir / "ops.npy",
                metadata_path=find_first_existing(input_dir, ("*_metadata.json",)),
                stim_events_path=resolve_stim_sidecar(stim_dir, input_dir, trial_id, ("*_stim_events.csv",)),
                stim_map_path=resolve_stim_sidecar(stim_dir, input_dir, trial_id, ("*_stim_map.csv",)),
                stim_pulse_events_path=resolve_stim_sidecar(stim_dir, input_dir, trial_id, ("*_stim_pulse_events.csv",)),
            )
        )
    return trials


def required_outputs_done(out_dir: Path, trial_id: str) -> bool:
    required = (
        out_dir / f"{trial_id}_roi_table.csv",
        out_dir / f"{trial_id}_F_raw.npy",
        out_dir / f"{trial_id}_Fneu.npy",
        out_dir / f"{trial_id}_F_corrected.npy",
        out_dir / f"{trial_id}_F0.npy",
        out_dir / f"{trial_id}_dff.npy",
        out_dir / f"{trial_id}_dff_traces.csv",
        out_dir / f"{trial_id}_dff_summary.csv",
        out_dir / f"{trial_id}_dff_summary.json",
    )
    return all(path.exists() and path.stat().st_size > 0 for path in required)


def clean_step_outputs(out_dir: Path) -> int:
    if not out_dir.exists():
        return 0
    removed = 0
    for pattern in STEP_OUTPUT_PATTERNS:
        for path in out_dir.glob(pattern):
            if path.is_dir():
                shutil.rmtree(path)
                removed += 1
                LOGGER.info("Removed old step-06 folder: %s", path)
            elif path.is_file() or path.is_symlink():
                path.unlink()
                removed += 1
                LOGGER.info("Removed old step-06 file: %s", path)
    return removed


def make_temp_output_dir(out_dir: Path) -> Path:
    out_dir.parent.mkdir(parents=True, exist_ok=True)
    return Path(tempfile.mkdtemp(prefix=f".{out_dir.name}.tmp-", dir=out_dir.parent))


def remove_path(path: Path) -> None:
    if path.is_dir():
        shutil.rmtree(path)
    elif path.exists() or path.is_symlink():
        path.unlink()


def install_temp_outputs(temp_dir: Path, out_dir: Path, clean_existing: bool) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    if clean_existing:
        clean_step_outputs(out_dir)
    for src in temp_dir.iterdir():
        dst = out_dir / src.name
        if dst.exists() or dst.is_symlink():
            remove_path(dst)
        shutil.move(str(src), str(dst))
    shutil.rmtree(temp_dir, ignore_errors=True)


def copy_if_exists(src: Path | None, dst: Path) -> bool:
    if src is None or not src.exists():
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    LOGGER.info("Copied %s -> %s", src, dst)
    return True


def copy_sidecar_outputs(trial: TrialInput, out_dir: Path) -> None:
    copy_if_exists(trial.metadata_path, out_dir / f"{trial.trial_id}_metadata.json")
    copy_if_exists(trial.stim_events_path, out_dir / f"{trial.trial_id}_stim_events.csv")
    copy_if_exists(trial.stim_map_path, out_dir / f"{trial.trial_id}_stim_map.csv")
    copy_if_exists(trial.stim_pulse_events_path, out_dir / f"{trial.trial_id}_stim_pulse_events.csv")


def load_json(path: Path | None) -> dict:
    if path is None or not path.exists():
        return {}
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except Exception as exc:
        LOGGER.warning("Could not read JSON %s: %s", path, exc)
        return {}


def safe_float(value, default: float | None = None) -> float | None:
    try:
        if value is None:
            return default
        out = float(value)
        return out if np.isfinite(out) else default
    except Exception:
        return default


def get_nested(mapping: dict, keys: tuple[str, ...]):
    current = mapping
    for key in keys:
        if not isinstance(current, dict):
            return None
        current = current.get(key)
    return current


def get_fps_from_metadata(meta: dict, ops: dict, default_fps: float) -> float:
    candidates = (
        get_nested(meta, ("temporal_calibration", "fps")),
        get_nested(meta, ("imaging", "fps")),
        get_nested(meta, ("acquisition", "fps")),
        meta.get("fps") if isinstance(meta, dict) else None,
        meta.get("frame_rate") if isinstance(meta, dict) else None,
        ops.get("fs") if isinstance(ops, dict) else None,
    )
    for candidate in candidates:
        fps = safe_float(candidate, None)
        if fps is not None and fps > 0:
            return float(fps)

    if isinstance(meta, dict):
        interval_candidates = (
            get_nested(meta, ("temporal_calibration", "frame_interval_sec")),
            get_nested(meta, ("temporal_calibration", "frame_interval")),
            meta.get("frame_interval_sec"),
            meta.get("frame_interval"),
        )
        for candidate in interval_candidates:
            dt = safe_float(candidate, None)
            if dt is not None and dt > 0:
                return float(1.0 / dt)

    return float(default_fps)


def read_csv_if_exists(path: Path | None) -> pd.DataFrame:
    if path is None or not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_csv(path)
    except Exception as exc:
        LOGGER.warning("Could not read CSV %s: %s", path, exc)
        return pd.DataFrame()


def load_ops(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        value = np.load(path, allow_pickle=True)
        item = value.item()
        return item if isinstance(item, dict) else {}
    except Exception:
        return {}


def validate_suite2p_arrays(trial: TrialInput) -> None:
    missing = [
        path.name
        for path in (trial.f_path, trial.fneu_path, trial.iscell_path, trial.stat_path, trial.ops_path)
        if not path.exists()
    ]
    if missing:
        raise FileNotFoundError(f"Missing required suite2p input(s): {', '.join(missing)}")


def load_suite2p_inputs(trial: TrialInput) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict]:
    validate_suite2p_arrays(trial)
    f_raw = np.load(trial.f_path, allow_pickle=True).astype(np.float32, copy=False)
    fneu = np.load(trial.fneu_path, allow_pickle=True).astype(np.float32, copy=False)
    iscell = np.load(trial.iscell_path, allow_pickle=True)
    stat = np.load(trial.stat_path, allow_pickle=True)
    ops = load_ops(trial.ops_path)

    if f_raw.ndim != 2 or fneu.ndim != 2:
        raise ValueError(f"F/Fneu must be 2D ROI x frame arrays, got F={f_raw.shape}, Fneu={fneu.shape}")
    if f_raw.shape != fneu.shape:
        raise ValueError(f"F and Fneu shape mismatch: {f_raw.shape} vs {fneu.shape}")
    if iscell.ndim != 2 or iscell.shape[0] != f_raw.shape[0]:
        raise ValueError(f"iscell.npy shape invalid: {iscell.shape}, expected rows={f_raw.shape[0]}")
    if len(stat) != f_raw.shape[0]:
        raise ValueError(f"stat.npy length mismatch: {len(stat)} vs n_roi={f_raw.shape[0]}")
    return f_raw, fneu, iscell, stat, ops


def manual_plane0_dir(manual_root: Path, trial: TrialInput) -> Path:
    return manual_root / trial.rel_parent / trial.trial_id / "suite2p_compatible" / "plane0"


def load_manual_roi_inputs(
    manual_root: Path,
    trial: TrialInput,
) -> tuple[np.ndarray, np.ndarray, np.ndarray | None, np.ndarray | None, str] | None:
    plane0 = manual_plane0_dir(manual_root, trial)
    stat_path = plane0 / "stat.npy"
    if not stat_path.exists():
        return None

    stat = np.load(stat_path, allow_pickle=True)
    if len(stat) == 0:
        raise ValueError(f"Manual ROI stat.npy contains no ROI: {stat_path}")

    iscell_path = plane0 / "iscell.npy"
    if iscell_path.exists():
        iscell = np.load(iscell_path, allow_pickle=True)
    else:
        iscell = np.ones((len(stat), 2), dtype=np.float32)
    if iscell.ndim != 2 or iscell.shape[0] != len(stat):
        raise ValueError(f"Manual iscell shape invalid: {iscell.shape}, expected rows={len(stat)}")

    f_path = plane0 / "F.npy"
    fneu_path = plane0 / "Fneu.npy"
    f_raw = np.load(f_path, allow_pickle=True).astype(np.float32, copy=False) if f_path.exists() else None
    fneu = np.load(fneu_path, allow_pickle=True).astype(np.float32, copy=False) if fneu_path.exists() else None
    return stat, iscell, f_raw, fneu, str(plane0)


def select_rois(
    iscell: np.ndarray,
    include_noncell: bool,
    roi_source: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, str, str | None]:
    iscell_flag = iscell[:, 0].astype(bool)
    iscell_prob = iscell[:, 1].astype(float) if iscell.shape[1] >= 2 else np.full(iscell.shape[0], np.nan)
    selection_label = "iscell"
    selection_path = None

    if roi_source == "all" or include_noncell:
        selected = np.arange(iscell.shape[0], dtype=int)
        return selected, iscell_flag, iscell_prob, "all_suite2p_roi", selection_path

    selected = np.where(iscell_flag)[0].astype(int)
    return selected, iscell_flag, iscell_prob, selection_label, selection_path


def corrected_movie_path(data_root: Path, trial: TrialInput, explicit_root: Path | None = None) -> Path | None:
    roots = []
    if explicit_root is not None:
        roots.append(explicit_root)
    roots.append(data_root / "03_motion_correct")

    patterns = (
        "*_corrected_movie.tif",
        "*_corrected_movie.tiff",
    )
    for root in roots:
        trial_dir = root / trial.rel_parent / trial.trial_id
        for pattern in patterns:
            matches = sorted(trial_dir.glob(pattern))
            if matches:
                return matches[0]
    return None


def movie_as_tyx(path: Path) -> np.ndarray:
    try:
        movie = tf.memmap(path)
    except Exception:
        movie = tf.imread(path)
    arr = np.asarray(movie)
    if arr.ndim == 2:
        arr = arr[np.newaxis, :, :]
    if arr.ndim == 3:
        return arr
    if arr.ndim == 4 and arr.shape[-1] in (1, 2, 3, 4):
        return arr[..., 0]
    raise ValueError(f"Expected movie shaped T x Y x X, got {arr.shape} from {path}")


def stat_mask(roi: object, shape_yx: tuple[int, int]) -> tuple[np.ndarray, np.ndarray]:
    mask = np.zeros(shape_yx, dtype=bool)
    weights = np.array([], dtype=np.float32)
    if not isinstance(roi, dict):
        return mask, weights
    ypix = np.asarray(roi.get("ypix", []), dtype=int)
    xpix = np.asarray(roi.get("xpix", []), dtype=int)
    valid = (ypix >= 0) & (ypix < shape_yx[0]) & (xpix >= 0) & (xpix < shape_yx[1])
    ypix = ypix[valid]
    xpix = xpix[valid]
    if len(ypix) == 0:
        return mask, weights
    mask[ypix, xpix] = True
    lam = np.asarray(roi.get("lam", []), dtype=np.float32)
    if len(lam) == len(valid):
        lam = lam[valid]
    if len(lam) != len(ypix) or not np.isfinite(lam).any() or float(np.nansum(lam)) <= 0:
        weights = np.ones(len(ypix), dtype=np.float32)
    else:
        weights = lam.astype(np.float32, copy=False)
    return mask, weights


def mean_trace_from_mask(movie: np.ndarray, mask: np.ndarray, weights: np.ndarray | None = None) -> np.ndarray:
    if not np.any(mask):
        return np.full((movie.shape[0],), np.nan, dtype=np.float32)
    pixels = np.asarray(movie[:, mask], dtype=np.float32)
    if weights is not None and len(weights) == pixels.shape[1]:
        total = float(np.nansum(weights))
        if total > 0:
            return np.asarray(np.nansum(pixels * weights[np.newaxis, :], axis=1) / total, dtype=np.float32)
    return np.asarray(np.nanmean(pixels, axis=1), dtype=np.float32)


def neuropil_mask(
    roi_mask: np.ndarray,
    all_roi_mask: np.ndarray,
    inner_radius: int,
    outer_radius: int,
    min_pixels: int,
) -> np.ndarray:
    try:
        from scipy import ndimage as ndi
    except Exception:
        ypix, xpix = np.where(roi_mask)
        out = np.zeros_like(roi_mask, dtype=bool)
        if len(ypix) == 0:
            return out
        y0 = max(0, int(ypix.min()) - outer_radius)
        y1 = min(roi_mask.shape[0], int(ypix.max()) + outer_radius + 1)
        x0 = max(0, int(xpix.min()) - outer_radius)
        x1 = min(roi_mask.shape[1], int(xpix.max()) + outer_radius + 1)
        out[y0:y1, x0:x1] = True
        out &= ~all_roi_mask
        return out

    inner_radius = max(1, int(inner_radius))
    outer_radius = max(inner_radius + 1, int(outer_radius))
    inner = ndi.binary_dilation(roi_mask, iterations=inner_radius)
    outer = ndi.binary_dilation(roi_mask, iterations=outer_radius)
    ring = outer & ~inner & ~all_roi_mask
    if int(np.count_nonzero(ring)) >= min_pixels:
        return ring

    expanded = ndi.binary_dilation(roi_mask, iterations=outer_radius * 2)
    ring = expanded & ~inner & ~all_roi_mask
    return ring


def extract_traces_from_corrected_movie(
    movie_path: Path,
    stat: np.ndarray,
    selected: np.ndarray,
    neuropil_inner_radius: int,
    neuropil_outer_radius: int,
    min_neuropil_pixels: int,
) -> tuple[np.ndarray, np.ndarray]:
    movie = movie_as_tyx(movie_path)
    shape_yx = tuple(movie.shape[-2:])
    roi_masks: list[np.ndarray] = []
    roi_weights: list[np.ndarray] = []
    all_roi_mask = np.zeros(shape_yx, dtype=bool)

    for suite2p_idx in selected:
        mask, weights = stat_mask(stat[int(suite2p_idx)], shape_yx)
        roi_masks.append(mask)
        roi_weights.append(weights)
        all_roi_mask |= mask

    f_rows = []
    fneu_rows = []
    for mask, weights in zip(roi_masks, roi_weights):
        f_rows.append(mean_trace_from_mask(movie, mask, weights))
        nmask = neuropil_mask(
            roi_mask=mask,
            all_roi_mask=all_roi_mask,
            inner_radius=neuropil_inner_radius,
            outer_radius=neuropil_outer_radius,
            min_pixels=min_neuropil_pixels,
        )
        fneu_rows.append(mean_trace_from_mask(movie, nmask, None))

    return np.vstack(f_rows).astype(np.float32), np.vstack(fneu_rows).astype(np.float32)


def build_background_tile_traces(
    movie: np.ndarray,
    roi_masks: list[np.ndarray],
    pad_radius: int,
    grid_rows: int,
    grid_cols: int,
    min_pixels: int,
) -> tuple[np.ndarray, dict]:
    try:
        from scipy import ndimage as ndi
    except Exception:
        ndi = None

    shape_yx = tuple(movie.shape[-2:])
    exclusion_mask = np.zeros(shape_yx, dtype=bool)
    for mask in roi_masks:
        exclusion_mask |= mask
    if ndi is not None and pad_radius > 0:
        exclusion_mask = ndi.binary_dilation(exclusion_mask, iterations=int(pad_radius))

    nonroi_mask = ~exclusion_mask
    tile_traces: list[np.ndarray] = []
    tile_labels: list[str] = []
    y_edges = np.linspace(0, shape_yx[0], max(2, int(grid_rows)) + 1, dtype=int)
    x_edges = np.linspace(0, shape_yx[1], max(2, int(grid_cols)) + 1, dtype=int)
    for gy in range(len(y_edges) - 1):
        for gx in range(len(x_edges) - 1):
            y0, y1 = int(y_edges[gy]), int(y_edges[gy + 1])
            x0, x1 = int(x_edges[gx]), int(x_edges[gx + 1])
            tile_mask = np.zeros(shape_yx, dtype=bool)
            tile_mask[y0:y1, x0:x1] = True
            sample_mask = tile_mask & nonroi_mask
            if int(np.count_nonzero(sample_mask)) < int(min_pixels):
                continue
            pixels = np.asarray(movie[:, sample_mask], dtype=np.float32)
            trace = np.nanmedian(pixels, axis=1).astype(np.float32)
            tile_traces.append(trace)
            tile_labels.append(f"tile_r{gy + 1:02d}_c{gx + 1:02d}")

    info = {
        "n_nonroi_pixels": int(np.count_nonzero(nonroi_mask)),
        "n_tiles_total": int(max(1, int(grid_rows)) * max(1, int(grid_cols))),
        "n_tiles_kept": int(len(tile_traces)),
        "tile_labels": tile_labels,
    }
    if not tile_traces:
        return np.zeros((movie.shape[0], 0), dtype=np.float32), info
    return np.column_stack(tile_traces).astype(np.float32), info


def standardize_columns(matrix: np.ndarray, min_std: float = 1e-6) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    if matrix.ndim != 2:
        raise ValueError(f"Expected 2D matrix for column standardization, got {matrix.shape}")
    if matrix.shape[1] == 0:
        return matrix.astype(np.float32, copy=True), np.zeros((0,), dtype=np.float32), np.ones((0,), dtype=np.float32)
    mean = np.nanmean(matrix, axis=0).astype(np.float32)
    centered = matrix - mean[np.newaxis, :]
    scale = np.nanstd(centered, axis=0).astype(np.float32)
    scale[~np.isfinite(scale) | (scale < min_std)] = 1.0
    return (centered / scale[np.newaxis, :]).astype(np.float32), mean, scale


def compute_artifact_components(
    movie_path: Path,
    stat: np.ndarray,
    selected: np.ndarray,
    pad_radius: int,
    grid_rows: int,
    grid_cols: int,
    min_pixels: int,
    n_components: int,
) -> tuple[np.ndarray, dict]:
    movie = movie_as_tyx(movie_path)
    shape_yx = tuple(movie.shape[-2:])
    roi_masks: list[np.ndarray] = []
    for suite2p_idx in selected:
        mask, _ = stat_mask(stat[int(suite2p_idx)], shape_yx)
        roi_masks.append(mask)

    background_traces, bg_info = build_background_tile_traces(
        movie=movie,
        roi_masks=roi_masks,
        pad_radius=pad_radius,
        grid_rows=grid_rows,
        grid_cols=grid_cols,
        min_pixels=min_pixels,
    )
    if background_traces.shape[1] == 0:
        return np.zeros((movie.shape[0], 0), dtype=np.float32), {
            **bg_info,
            "method": "none",
            "reason": "no_background_tiles",
            "n_components_requested": int(n_components),
            "n_components_used": 0,
        }

    global_trace = np.nanmedian(background_traces, axis=1, keepdims=True).astype(np.float32)
    standardized, _, _ = standardize_columns(background_traces)
    if standardized.shape[1] == 0:
        return global_trace, {
            **bg_info,
            "method": "global_only",
            "reason": "no_standardized_tiles",
            "n_components_requested": int(n_components),
            "n_components_used": 1,
        }

    u, s, _ = np.linalg.svd(standardized, full_matrices=False)
    max_pc = int(min(max(0, n_components), u.shape[1]))
    pcs = u[:, :max_pc] * s[:max_pc][np.newaxis, :]
    components = np.column_stack([global_trace, pcs]).astype(np.float32)
    components, _, _ = standardize_columns(components)
    info = {
        **bg_info,
        "method": "nonroi_tile_pca",
        "reason": "ok",
        "n_components_requested": int(n_components),
        "n_components_used": int(components.shape[1]),
    }
    return components.astype(np.float32), info


def corrcoef_safe(x: np.ndarray, y: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    valid = np.isfinite(x) & np.isfinite(y)
    if int(np.count_nonzero(valid)) < 3:
        return np.nan
    xv = x[valid]
    yv = y[valid]
    xstd = float(np.nanstd(xv))
    ystd = float(np.nanstd(yv))
    if xstd <= 0 or ystd <= 0:
        return np.nan
    return float(np.corrcoef(xv, yv)[0, 1])


def regress_artifact_components(
    f_corrected: np.ndarray,
    components: np.ndarray,
) -> tuple[np.ndarray, pd.DataFrame]:
    n_roi, n_frames = f_corrected.shape
    if components.ndim != 2 or components.shape[0] != n_frames or components.shape[1] == 0:
        empty = pd.DataFrame(
            {
                "roi_id": np.arange(1, n_roi + 1, dtype=int),
                "artifact_r2": np.zeros((n_roi,), dtype=float),
                "artifact_corr_before": np.full((n_roi,), np.nan, dtype=float),
                "artifact_corr_after": np.full((n_roi,), np.nan, dtype=float),
                "artifact_beta_l2": np.zeros((n_roi,), dtype=float),
            }
        )
        return f_corrected.astype(np.float32, copy=True), empty

    x = np.asarray(components, dtype=np.float32)
    x_centered = x - np.nanmean(x, axis=0, keepdims=True)
    xtx_inv_xt = np.linalg.pinv(x_centered)
    global_component = x_centered[:, 0] if x_centered.shape[1] else np.full((n_frames,), np.nan, dtype=np.float32)

    cleaned_rows = []
    qc_rows = []
    for roi_idx in range(n_roi):
        y = np.asarray(f_corrected[roi_idx], dtype=np.float32)
        y_centered = y - np.nanmean(y)
        beta = xtx_inv_xt @ y_centered
        fitted = x_centered @ beta
        cleaned = (y_centered - fitted) + np.nanmean(y)
        var_total = float(np.nanvar(y_centered))
        var_resid = float(np.nanvar(cleaned - np.nanmean(cleaned)))
        artifact_r2 = 0.0 if var_total <= 0 else max(0.0, min(1.0, 1.0 - (var_resid / var_total)))
        cleaned_rows.append(cleaned.astype(np.float32))
        qc_rows.append(
            {
                "roi_id": int(roi_idx + 1),
                "artifact_r2": float(artifact_r2),
                "artifact_corr_before": corrcoef_safe(y, global_component),
                "artifact_corr_after": corrcoef_safe(cleaned, global_component),
                "artifact_beta_l2": float(np.linalg.norm(beta)),
            }
        )
    return np.vstack(cleaned_rows).astype(np.float32), pd.DataFrame(qc_rows)


def first_stim_start_sec(stim_events: pd.DataFrame) -> float | None:
    if stim_events.empty or "start_time_sec" not in stim_events.columns:
        return None
    values = pd.to_numeric(stim_events["start_time_sec"], errors="coerce").dropna()
    if values.empty:
        return None
    first = float(values.min())
    return first if first >= 0 else None


def compute_f0(
    f_corrected: np.ndarray,
    fps: float,
    stim_events: pd.DataFrame,
    f0_mode: str,
    f0_percentile: float,
    f0_window_sec: float,
    default_baseline_sec: float,
    min_baseline_frames: int,
) -> tuple[np.ndarray, dict]:
    info = {
        "f0_mode": f0_mode,
        "f0_percentile": float(f0_percentile),
        "f0_window_sec": float(f0_window_sec),
    }

    if f0_mode == "percentile":
        f0 = np.percentile(f_corrected, f0_percentile, axis=1, keepdims=True)
        return f0.astype(np.float32), info

    if f0_mode == "stim-baseline":
        start_sec = first_stim_start_sec(stim_events)
        if start_sec is None:
            baseline_frames = int(round(default_baseline_sec * fps))
        else:
            baseline_frames = int(np.floor(start_sec * fps))
        baseline_frames = min(max(baseline_frames, min_baseline_frames), f_corrected.shape[1])
        baseline = f_corrected[:, :baseline_frames]
        f0 = np.percentile(baseline, f0_percentile, axis=1, keepdims=True)
        info.update({"baseline_frames": int(baseline_frames), "first_stim_start_sec": start_sec})
        return f0.astype(np.float32), info

    window = max(1, int(round(f0_window_sec * fps)))
    rows = []
    for trace in f_corrected:
        series = pd.Series(trace)
        if f0_mode == "rolling-percentile":
            rows.append(
                series.rolling(window=window, center=True, min_periods=1)
                .quantile(f0_percentile / 100.0)
                .to_numpy(dtype=np.float32)
            )
        elif f0_mode == "rolling-median":
            rows.append(
                series.rolling(window=window, center=True, min_periods=1)
                .median()
                .to_numpy(dtype=np.float32)
            )
        else:
            raise ValueError(f"Unsupported f0_mode: {f0_mode}")
    info["rolling_window_frames"] = int(window)
    return np.vstack(rows).astype(np.float32), info


def compute_dff(f_corrected: np.ndarray, f0: np.ndarray, eps: float) -> np.ndarray:
    denominator = np.maximum(np.abs(f0), eps)
    return ((f_corrected - f0) / denominator).astype(np.float32)


def stat_xy(roi) -> tuple[float, float, int]:
    if not isinstance(roi, dict):
        return np.nan, np.nan, 0
    xpix = np.asarray(roi.get("xpix", []), dtype=float)
    ypix = np.asarray(roi.get("ypix", []), dtype=float)
    if len(xpix) and len(ypix):
        return float(np.mean(xpix)), float(np.mean(ypix)), int(len(xpix))
    med = roi.get("med", [np.nan, np.nan])
    y_mean = safe_float(med[0] if len(med) > 0 else None, np.nan)
    x_mean = safe_float(med[1] if len(med) > 1 else None, np.nan)
    return float(x_mean), float(y_mean), 0


def safe_int(value, default: int = -1) -> int:
    try:
        if value is None:
            return default
        out = int(value)
        return out
    except Exception:
        return default


def stat_roi_metadata(roi: object, stat_index: int) -> dict:
    if not isinstance(roi, dict):
        return {
            "roi_source": "suite2p",
            "roi_type": "suite2p",
            "manual_roi_id": -1,
            "suite2p_original_id": int(stat_index),
            "previous_suite2p_original_id": -1,
            "source_roi_id": f"suite2p_{int(stat_index)}",
        }

    roi_source = str(roi.get("roi_source", "") or "").strip()
    if roi_source in {"suite2p_reference", "suite2p"} or (not roi_source and "manual_roi_id" not in roi):
        suite2p_id = safe_int(roi.get("suite2p_original_id"), int(stat_index))
        return {
            "roi_source": "suite2p",
            "roi_type": str(roi.get("roi_type", "suite2p") or "suite2p"),
            "manual_roi_id": -1,
            "suite2p_original_id": suite2p_id,
            "previous_suite2p_original_id": -1,
            "source_roi_id": str(roi.get("source_roi_id", f"suite2p_{suite2p_id}") or f"suite2p_{suite2p_id}"),
        }

    manual_id = safe_int(roi.get("manual_roi_id"), int(stat_index) + 1)
    previous_suite2p_id = safe_int(roi.get("previous_suite2p_original_id"), -1)
    if previous_suite2p_id < 0:
        previous_suite2p_id = safe_int(roi.get("suite2p_original_id"), -1)
    return {
        "roi_source": "manual",
        "roi_type": str(roi.get("roi_type", "manual") or "manual"),
        "manual_roi_id": manual_id,
        "suite2p_original_id": -1,
        "previous_suite2p_original_id": previous_suite2p_id,
        "source_roi_id": str(roi.get("source_roi_id", f"manual_{manual_id}") or f"manual_{manual_id}"),
    }


def build_roi_table(
    trial_id: str,
    selected: np.ndarray,
    iscell_flag: np.ndarray,
    iscell_prob: np.ndarray,
    stat: np.ndarray,
    f_raw: np.ndarray,
    fneu: np.ndarray,
    f_corrected: np.ndarray,
    f0: np.ndarray,
    dff: np.ndarray,
    artifact_qc: pd.DataFrame | None = None,
) -> pd.DataFrame:
    artifact_qc = artifact_qc.copy() if artifact_qc is not None else pd.DataFrame()
    artifact_lookup = artifact_qc.set_index("roi_id") if not artifact_qc.empty and "roi_id" in artifact_qc.columns else pd.DataFrame()
    rows = []
    f0_stat = f0 if f0.shape == dff.shape else np.repeat(f0, dff.shape[1], axis=1)
    for out_idx, stat_idx in enumerate(selected):
        roi_stat = stat[int(stat_idx)]
        x_mean, y_mean, npix = stat_xy(roi_stat)
        metadata = stat_roi_metadata(roi_stat, int(stat_idx))
        trace = dff[out_idx]
        std_dff = float(np.nanstd(trace))
        max_dff = float(np.nanmax(trace))
        rows.append(
            {
                "trial_id": trial_id,
                "roi_id": out_idx + 1,
                "source_roi_id": metadata["source_roi_id"],
                "roi_source": metadata["roi_source"],
                "roi_type": metadata["roi_type"],
                "manual_roi_id": metadata["manual_roi_id"],
                "suite2p_original_id": metadata["suite2p_original_id"],
                "previous_suite2p_original_id": metadata["previous_suite2p_original_id"],
                "stat_index": int(stat_idx),
                "iscell": int(bool(iscell_flag[stat_idx])),
                "iscell_prob": float(iscell_prob[stat_idx]) if np.isfinite(iscell_prob[stat_idx]) else np.nan,
                "x_mean": x_mean,
                "y_mean": y_mean,
                "npix": npix,
                "mean_F": float(np.nanmean(f_raw[out_idx])),
                "mean_Fneu": float(np.nanmean(fneu[out_idx])),
                "mean_F_corrected": float(np.nanmean(f_corrected[out_idx])),
                "mean_F0": float(np.nanmean(f0_stat[out_idx])),
                "mean_dff": float(np.nanmean(trace)),
                "std_dff": std_dff,
                "max_dff": max_dff,
                "snr_like": float(max_dff / std_dff) if std_dff > 0 else np.nan,
                "artifact_r2": float(artifact_lookup.at[out_idx + 1, "artifact_r2"]) if not artifact_lookup.empty and (out_idx + 1) in artifact_lookup.index else np.nan,
                "artifact_corr_before": float(artifact_lookup.at[out_idx + 1, "artifact_corr_before"]) if not artifact_lookup.empty and (out_idx + 1) in artifact_lookup.index else np.nan,
                "artifact_corr_after": float(artifact_lookup.at[out_idx + 1, "artifact_corr_after"]) if not artifact_lookup.empty and (out_idx + 1) in artifact_lookup.index else np.nan,
                "artifact_beta_l2": float(artifact_lookup.at[out_idx + 1, "artifact_beta_l2"]) if not artifact_lookup.empty and (out_idx + 1) in artifact_lookup.index else np.nan,
            }
        )
    return pd.DataFrame(rows)


def write_dff_traces_csv(path: Path, dff: np.ndarray, fps: float) -> None:
    n_roi, n_frames = dff.shape
    fieldnames = ["frame", "time_sec"] + [f"roi_{i + 1:04d}" for i in range(n_roi)]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(fieldnames)
        for frame in range(n_frames):
            writer.writerow([frame, frame / fps, *dff[:, frame].tolist()])


def stim_spans(stim_events: pd.DataFrame) -> list[tuple[float, float]]:
    if stim_events.empty or "start_time_sec" not in stim_events.columns:
        return []
    spans = []
    for _, row in stim_events.iterrows():
        start = safe_float(row.get("start_time_sec"), None)
        if start is None:
            continue
        end = safe_float(row.get("end_time_sec"), None)
        duration = safe_float(row.get("duration_sec"), None)
        if end is None and duration is not None:
            end = start + duration
        if end is None or end < start:
            end = start
        spans.append((float(start), float(end)))
    return spans


def mark_stimuli(ax, stim_events: pd.DataFrame, label: str = "stimulus") -> None:
    spans = stim_spans(stim_events)
    for i, (start, end) in enumerate(spans):
        if end > start:
            ax.axvspan(start, end, color="tab:orange", alpha=0.16, lw=0, label=label if i == 0 else None)
        else:
            ax.axvline(start, color="tab:orange", alpha=0.35, lw=0.8, label=label if i == 0 else None)


def save_figure(fig, output_path: Path, plot_format: str, dpi: int) -> None:
    if plot_format in ("png", "both"):
        fig.savefig(output_path.with_suffix(".png"), dpi=dpi, bbox_inches="tight")
    if plot_format in ("pdf", "both"):
        fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")


def finite_percentile(values: np.ndarray, q: float, default: float) -> float:
    finite = np.asarray(values)[np.isfinite(values)]
    if finite.size == 0:
        return default
    return float(np.nanpercentile(finite, q))


def deterministic_example_indices(activity: np.ndarray, n_examples: int = 10) -> list[int]:
    activity = np.asarray(activity, dtype=float)
    finite_idx = np.flatnonzero(np.isfinite(activity))
    if finite_idx.size == 0:
        return list(range(min(n_examples, len(activity))))
    order = finite_idx[np.argsort(activity[finite_idx])]
    if len(order) <= n_examples:
        return [int(idx) for idx in order]
    positions = np.linspace(0, len(order) - 1, n_examples).round().astype(int)
    return [int(order[pos]) for pos in positions]


def save_dff_heatmap(
    dff: np.ndarray,
    fps: float,
    stim_events: pd.DataFrame,
    output_path: Path,
    trial_id: str,
    max_rois: int,
    dpi: int,
    plot_format: str,
) -> None:
    import matplotlib.pyplot as plt

    if dff.size == 0:
        return
    heatmap = dff
    if max_rois > 0 and dff.shape[0] > max_rois:
        keep = np.argsort(np.nanmax(dff, axis=1))[::-1][:max_rois]
        heatmap = dff[keep]
    finite = heatmap[np.isfinite(heatmap)]
    vmin = float(np.nanpercentile(finite, 2)) if finite.size else -1.0
    vmax = float(np.nanpercentile(finite, 98)) if finite.size else 2.0
    if vmax <= vmin:
        vmax = vmin + 1e-6

    fig, ax = plt.subplots(figsize=(12, 6))
    im = ax.imshow(
        heatmap,
        aspect="auto",
        interpolation="nearest",
        cmap="viridis",
        extent=[0, heatmap.shape[1] / fps, heatmap.shape[0], 0],
        vmin=vmin,
        vmax=vmax,
    )
    mark_stimuli(ax, stim_events)
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("ROI")
    ax.set_title(f"dF/F heatmap - {trial_id}")
    fig.colorbar(im, ax=ax, label="dF/F")
    plt.tight_layout()
    handles, labels = ax.get_legend_handles_labels()
    if labels:
        ax.legend(loc="upper right", frameon=False)
    try:
        save_figure(fig, output_path, plot_format=plot_format, dpi=dpi)
    finally:
        plt.close(fig)


def save_example_traces(
    dff: np.ndarray,
    roi_table: pd.DataFrame,
    fps: float,
    stim_events: pd.DataFrame,
    output_path: Path,
    trial_id: str,
    dpi: int,
    plot_format: str,
) -> None:
    import matplotlib.pyplot as plt

    activity = pd.to_numeric(roi_table.get("max_dff", pd.Series(np.nan, index=roi_table.index)), errors="coerce").to_numpy()
    indices = deterministic_example_indices(activity, n_examples=min(12, dff.shape[0]))
    if not indices:
        return
    time_axis = np.arange(dff.shape[1]) / fps
    fig, axes = plt.subplots(len(indices), 1, figsize=(12, max(3, 1.9 * len(indices))), sharex=True)
    if len(indices) == 1:
        axes = [axes]
    for ax, idx in zip(axes, indices):
        mark_stimuli(ax, stim_events)
        ax.plot(time_axis, dff[idx], lw=0.9, color="tab:blue")
        row = roi_table.iloc[idx]
        roi_source = str(row.get("roi_source", "suite2p"))
        if roi_source == "manual":
            source_label = f"manual {int(row.get('manual_roi_id', row['roi_id']))}"
        else:
            source_label = f"s2p {int(row.get('suite2p_original_id', idx))}"
        ax.set_ylabel(
            f"ROI {int(row['roi_id'])}\n{source_label}",
            rotation=0,
            labelpad=36,
            va="center",
        )
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
    axes[-1].set_xlabel("Time (s)")
    handles, labels = axes[0].get_legend_handles_labels()
    if labels:
        axes[0].legend(loc="upper right", frameon=False)
    fig.suptitle(f"Representative dF/F traces with stimulus timing - {trial_id}", y=0.995)
    plt.tight_layout()
    try:
        save_figure(fig, output_path, plot_format=plot_format, dpi=dpi)
    finally:
        plt.close(fig)


def save_dff_distribution(
    roi_table: pd.DataFrame,
    output_path: Path,
    trial_id: str,
    dpi: int,
    plot_format: str,
) -> None:
    import matplotlib.pyplot as plt

    columns = [
        ("max_dff", "Max dF/F"),
        ("std_dff", "Trace SD"),
        ("mean_F0", "Baseline F0"),
        ("snr_like", "SNR-like max/SD"),
    ]
    fig, axes = plt.subplots(2, 2, figsize=(10, 7))
    for ax, (column, title) in zip(axes.ravel(), columns):
        values = pd.to_numeric(roi_table[column], errors="coerce").replace([np.inf, -np.inf], np.nan).dropna() if column in roi_table else pd.Series(dtype=float)
        if values.empty:
            ax.text(0.5, 0.5, f"No {column} values", ha="center", va="center")
            ax.set_axis_off()
            continue
        ax.hist(values, bins=min(40, max(8, int(np.sqrt(len(values))))), color="tab:blue", alpha=0.78)
        ax.axvline(values.median(), color="tab:orange", lw=1.4, label="median")
        ax.set_title(title)
        ax.set_xlabel(title)
        ax.set_ylabel("ROI count")
        ax.legend(frameon=False)
    fig.suptitle(f"dF/F ROI activity distributions - {trial_id}", y=0.995)
    fig.tight_layout()
    try:
        save_figure(fig, output_path, plot_format=plot_format, dpi=dpi)
    finally:
        plt.close(fig)


def save_neuropil_examples(
    f_raw: np.ndarray,
    fneu: np.ndarray,
    f_corrected: np.ndarray,
    dff: np.ndarray,
    roi_table: pd.DataFrame,
    fps: float,
    stim_events: pd.DataFrame,
    output_path: Path,
    trial_id: str,
    dpi: int,
    plot_format: str,
) -> None:
    import matplotlib.pyplot as plt

    activity = pd.to_numeric(roi_table.get("max_dff", pd.Series(np.nan, index=roi_table.index)), errors="coerce").to_numpy()
    indices = deterministic_example_indices(activity, n_examples=min(6, dff.shape[0]))
    if not indices:
        return
    time_axis = np.arange(dff.shape[1]) / fps
    fig, axes = plt.subplots(len(indices), 1, figsize=(12, max(4, 2.2 * len(indices))), sharex=True)
    if len(indices) == 1:
        axes = [axes]
    for ax, idx in zip(axes, indices):
        mark_stimuli(ax, stim_events)
        ax.plot(time_axis, f_raw[idx], lw=0.7, label="F raw", color="tab:blue")
        ax.plot(time_axis, fneu[idx], lw=0.7, label="Fneu", color="tab:orange")
        ax.plot(time_axis, f_corrected[idx], lw=0.7, label="F corrected", color="tab:green")
        ax2 = ax.twinx()
        ax2.plot(time_axis, dff[idx], lw=0.8, label="dF/F", color="tab:red", alpha=0.75)
        ax.set_ylabel(f"ROI {int(roi_table.iloc[idx].get('roi_id', idx + 1))}")
        ax2.set_ylabel("dF/F")
        ax.spines["top"].set_visible(False)
        ax2.spines["top"].set_visible(False)
    axes[-1].set_xlabel("Time (s)")
    handles, labels = axes[0].get_legend_handles_labels()
    handles.append(plt.Line2D([0], [0], color="tab:red", lw=0.8))
    labels.append("dF/F")
    fig.legend(handles, labels, loc="upper right", frameon=False)
    fig.suptitle(f"Neuropil correction examples - {trial_id}", y=0.995)
    fig.tight_layout()
    try:
        save_figure(fig, output_path, plot_format=plot_format, dpi=dpi)
    finally:
        plt.close(fig)


def save_artifact_regression_examples(
    f_corrected_before: np.ndarray,
    f_corrected_after: np.ndarray,
    dff_before: np.ndarray,
    dff_after: np.ndarray,
    roi_table: pd.DataFrame,
    components: np.ndarray,
    fps: float,
    stim_events: pd.DataFrame,
    output_path: Path,
    trial_id: str,
    dpi: int,
    plot_format: str,
) -> None:
    import matplotlib.pyplot as plt

    if components.ndim != 2 or components.shape[1] == 0:
        LOGGER.warning("Skipping artifact regression examples for %s: no artifact components available.", trial_id)
        return
    score = pd.to_numeric(roi_table.get("artifact_r2", pd.Series(np.nan, index=roi_table.index)), errors="coerce").to_numpy()
    indices = deterministic_example_indices(score, n_examples=min(6, dff_after.shape[0]))
    if not indices:
        return
    time_axis = np.arange(dff_after.shape[1]) / fps
    nrows = len(indices) + 1
    fig, axes = plt.subplots(nrows, 1, figsize=(12, max(4, 2.0 * nrows)), sharex=True)
    if nrows == 1:
        axes = [axes]

    bg_ax = axes[0]
    for comp_idx in range(min(3, components.shape[1])):
        bg_ax.plot(time_axis, components[:, comp_idx], lw=0.9, label=f"artifact comp {comp_idx + 1}")
    mark_stimuli(bg_ax, stim_events)
    bg_ax.set_ylabel("BG comps")
    bg_ax.legend(loc="upper right", frameon=False)
    bg_ax.spines["top"].set_visible(False)
    bg_ax.spines["right"].set_visible(False)

    for ax, idx in zip(axes[1:], indices):
        mark_stimuli(ax, stim_events)
        ax.plot(time_axis, dff_before[idx], lw=0.7, color="tab:gray", alpha=0.8, label="before")
        ax.plot(time_axis, dff_after[idx], lw=0.8, color="tab:red", alpha=0.9, label="after")
        row = roi_table.iloc[idx]
        ax.set_ylabel(
            f"ROI {int(row.get('roi_id', idx + 1))}\nR2={float(row.get('artifact_r2', np.nan)):.2f}",
            rotation=0,
            labelpad=40,
            va="center",
        )
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
    axes[-1].set_xlabel("Time (s)")
    handles, labels = axes[1].get_legend_handles_labels() if len(axes) > 1 else axes[0].get_legend_handles_labels()
    if labels:
        axes[1 if len(axes) > 1 else 0].legend(loc="upper right", frameon=False)
    fig.suptitle(f"Artifact regression examples - {trial_id}", y=0.995)
    fig.tight_layout()
    try:
        save_figure(fig, output_path, plot_format=plot_format, dpi=dpi)
    finally:
        plt.close(fig)


def save_artifact_qc_summary(
    roi_table: pd.DataFrame,
    output_path: Path,
    trial_id: str,
    dpi: int,
    plot_format: str,
) -> None:
    import matplotlib.pyplot as plt

    columns = [
        ("artifact_r2", "Artifact R2"),
        ("artifact_corr_before", "Corr before"),
        ("artifact_corr_after", "Corr after"),
        ("artifact_beta_l2", "Artifact beta L2"),
    ]
    fig, axes = plt.subplots(2, 2, figsize=(10, 7))
    for ax, (column, title) in zip(axes.ravel(), columns):
        values = pd.to_numeric(roi_table.get(column, pd.Series(dtype=float)), errors="coerce").replace([np.inf, -np.inf], np.nan).dropna()
        if values.empty:
            ax.text(0.5, 0.5, f"No {column}", ha="center", va="center")
            ax.set_axis_off()
            continue
        ax.hist(values, bins=min(40, max(8, int(np.sqrt(len(values))))), color="tab:purple", alpha=0.78)
        ax.axvline(values.median(), color="tab:orange", lw=1.4, label="median")
        ax.set_title(title)
        ax.set_xlabel(title)
        ax.set_ylabel("ROI count")
        ax.legend(frameon=False)
    fig.suptitle(f"Artifact QC summary - {trial_id}", y=0.995)
    fig.tight_layout()
    try:
        save_figure(fig, output_path, plot_format=plot_format, dpi=dpi)
    finally:
        plt.close(fig)


def save_roi_spatial_activity_map(
    roi_table: pd.DataFrame,
    output_path: Path,
    trial_id: str,
    dpi: int,
    plot_format: str,
) -> None:
    import matplotlib.pyplot as plt

    required = {"x_mean", "y_mean", "max_dff"}
    if not required.issubset(set(roi_table.columns)):
        LOGGER.warning("Skipping ROI spatial activity map for %s: missing ROI coordinate/activity columns.", trial_id)
        return
    plot_df = roi_table.copy()
    for column in required:
        plot_df[column] = pd.to_numeric(plot_df[column], errors="coerce")
    plot_df = plot_df.replace([np.inf, -np.inf], np.nan).dropna(subset=["x_mean", "y_mean", "max_dff"])
    if plot_df.empty:
        LOGGER.warning("Skipping ROI spatial activity map for %s: no finite ROI coordinates.", trial_id)
        return
    fig, ax = plt.subplots(figsize=(7, 6))
    sizes = np.clip(pd.to_numeric(plot_df.get("npix", 20), errors="coerce").fillna(20).to_numpy(), 10, 250)
    im = ax.scatter(plot_df["x_mean"], plot_df["y_mean"], c=plot_df["max_dff"], s=sizes, cmap="magma", alpha=0.82, edgecolors="black", linewidths=0.2)
    ax.invert_yaxis()
    ax.set_aspect("equal", adjustable="box")
    ax.set_xlabel("X position (pixels)")
    ax.set_ylabel("Y position (pixels)")
    ax.set_title(f"ROI spatial activity map - {trial_id}")
    fig.colorbar(im, ax=ax, label="Max dF/F")
    fig.tight_layout()
    try:
        save_figure(fig, output_path, plot_format=plot_format, dpi=dpi)
    finally:
        plt.close(fig)


def write_qc_plots(
    out_dir: Path,
    trial_id: str,
    dff: np.ndarray,
    roi_table: pd.DataFrame,
    fps: float,
    stim_events: pd.DataFrame,
    args: argparse.Namespace,
    f_raw: np.ndarray | None = None,
    fneu: np.ndarray | None = None,
    f_corrected: np.ndarray | None = None,
    dff_before_artifact: np.ndarray | None = None,
    f_corrected_before_artifact: np.ndarray | None = None,
    artifact_components: np.ndarray | None = None,
) -> None:
    if args.plot_level == "none":
        return
    plot_jobs = [
        ("dF/F heatmap", save_dff_heatmap, dict(dff=dff, fps=fps, stim_events=stim_events, output_path=out_dir / f"{trial_id}_dff_heatmap_sorted", trial_id=trial_id, max_rois=args.heatmap_max_rois, dpi=args.plot_dpi, plot_format=args.plot_format)),
        ("dF/F trace examples", save_example_traces, dict(dff=dff, roi_table=roi_table, fps=fps, stim_events=stim_events, output_path=out_dir / f"{trial_id}_dff_trace_examples_with_stim", trial_id=trial_id, dpi=args.plot_dpi, plot_format=args.plot_format)),
        ("dF/F distribution", save_dff_distribution, dict(roi_table=roi_table, output_path=out_dir / f"{trial_id}_dff_distribution", trial_id=trial_id, dpi=args.plot_dpi, plot_format=args.plot_format)),
    ]
    if args.plot_level == "full":
        if f_raw is not None and fneu is not None and f_corrected is not None:
            plot_jobs.append(("neuropil correction examples", save_neuropil_examples, dict(f_raw=f_raw, fneu=fneu, f_corrected=f_corrected, dff=dff, roi_table=roi_table, fps=fps, stim_events=stim_events, output_path=out_dir / f"{trial_id}_neuropil_correction_examples", trial_id=trial_id, dpi=args.plot_dpi, plot_format=args.plot_format)))
        else:
            LOGGER.warning("Skipping neuropil correction examples for %s: missing saved F arrays.", trial_id)
        if (
            args.artifact_regression != "none"
            and dff_before_artifact is not None
            and f_corrected_before_artifact is not None
            and artifact_components is not None
            and artifact_components.shape[1] > 0
        ):
            plot_jobs.append(
                (
                    "artifact regression examples",
                    save_artifact_regression_examples,
                    dict(
                        f_corrected_before=f_corrected_before_artifact,
                        f_corrected_after=f_corrected,
                        dff_before=dff_before_artifact,
                        dff_after=dff,
                        roi_table=roi_table,
                        components=artifact_components,
                        fps=fps,
                        stim_events=stim_events,
                        output_path=out_dir / f"{trial_id}_artifact_regression_examples",
                        trial_id=trial_id,
                        dpi=args.plot_dpi,
                        plot_format=args.plot_format,
                    ),
                )
            )
            plot_jobs.append(
                (
                    "artifact QC summary",
                    save_artifact_qc_summary,
                    dict(
                        roi_table=roi_table,
                        output_path=out_dir / f"{trial_id}_artifact_qc_summary",
                        trial_id=trial_id,
                        dpi=args.plot_dpi,
                        plot_format=args.plot_format,
                    ),
                )
            )
        plot_jobs.append(("ROI spatial activity map", save_roi_spatial_activity_map, dict(roi_table=roi_table, output_path=out_dir / f"{trial_id}_roi_spatial_activity_map", trial_id=trial_id, dpi=args.plot_dpi, plot_format=args.plot_format)))
    for label, func, kwargs in plot_jobs:
        try:
            func(**kwargs)
        except Exception as exc:
            LOGGER.warning("Could not write %s for %s: %s", label, trial_id, exc)


def refresh_trial_plots(out_dir: Path, trial_id: str, args: argparse.Namespace) -> bool:
    if args.plot_level == "none":
        return True
    dff_path = out_dir / f"{trial_id}_dff.npy"
    roi_table_path = out_dir / f"{trial_id}_roi_table.csv"
    summary_path = out_dir / f"{trial_id}_dff_summary.json"
    if not dff_path.exists() or not roi_table_path.exists():
        LOGGER.warning("Cannot refresh step-06 plots for %s: missing dF/F array or ROI table.", trial_id)
        return False
    dff = np.load(dff_path, allow_pickle=True).astype(np.float32, copy=False)
    roi_table = pd.read_csv(roi_table_path)
    summary = load_json(summary_path)
    fps = safe_float(summary.get("fps"), args.default_fps) or args.default_fps
    stim_events = read_csv_if_exists(out_dir / f"{trial_id}_stim_events.csv")
    f_raw = np.load(out_dir / f"{trial_id}_F_raw.npy", allow_pickle=True) if (out_dir / f"{trial_id}_F_raw.npy").exists() else None
    fneu = np.load(out_dir / f"{trial_id}_Fneu.npy", allow_pickle=True) if (out_dir / f"{trial_id}_Fneu.npy").exists() else None
    f_corrected = np.load(out_dir / f"{trial_id}_F_corrected.npy", allow_pickle=True) if (out_dir / f"{trial_id}_F_corrected.npy").exists() else None
    write_qc_plots(
        out_dir=out_dir,
        trial_id=trial_id,
        dff=dff,
        roi_table=roi_table,
        fps=float(fps),
        stim_events=stim_events,
        args=args,
        f_raw=f_raw,
        fneu=fneu,
        f_corrected=f_corrected,
    )
    return True


def process_trial(trial: TrialInput, out_dir: Path, args: argparse.Namespace) -> tuple[str, dict]:
    manual_inputs = None
    if args.roi_source in ("auto", "manual"):
        manual_inputs = load_manual_roi_inputs(args.manual_root, trial)
        if manual_inputs is None and args.roi_source == "manual":
            return (
                "skipped",
                {
                    "trial_id": trial.trial_id,
                    "status": "skipped",
                    "message": "No final manual ROI compatible output was found.",
                    "roi_source_requested": args.roi_source,
                    "manual_root": str(args.manual_root),
                },
            )

    out_dir.mkdir(parents=True, exist_ok=True)
    copy_sidecar_outputs(trial, out_dir)

    suite2p_f_all, suite2p_fneu_all, suite2p_iscell, suite2p_stat, ops = load_suite2p_inputs(trial)
    f_all = suite2p_f_all
    fneu_all = suite2p_fneu_all
    iscell = suite2p_iscell
    stat = suite2p_stat
    manual_source_path = None

    if manual_inputs is not None:
        stat, iscell, manual_f, manual_fneu, manual_source_path = manual_inputs
        if manual_f is not None and manual_fneu is not None and manual_f.shape == manual_fneu.shape:
            f_all = manual_f
            fneu_all = manual_fneu
        else:
            n_frames = suite2p_f_all.shape[1]
            f_all = np.full((len(stat), n_frames), np.nan, dtype=np.float32)
            fneu_all = np.full((len(stat), n_frames), np.nan, dtype=np.float32)

    selected, iscell_flag, iscell_prob, roi_source_used, roi_source_path = select_rois(
        iscell,
        include_noncell=args.include_noncell,
        roi_source=args.roi_source,
    )
    if manual_inputs is not None:
        roi_source_used = "manual_curation"
        roi_source_path = manual_source_path
    if len(selected) == 0:
        return "failed", {"trial_id": trial.trial_id, "status": "failed", "message": "No ROI selected after ROI filtering"}

    meta = load_json(trial.metadata_path)
    stim_events = read_csv_if_exists(trial.stim_events_path)
    fps = get_fps_from_metadata(meta, ops=ops, default_fps=args.default_fps)

    trace_movie_path = None
    if args.trace_source == "motion-corrected":
        trace_movie_path = corrected_movie_path(args.data_root, trial, args.trace_movie_root)
        if trace_movie_path is None:
            raise FileNotFoundError(
                f"Could not find motion-corrected movie for {trial.trial_id}. "
                "Use --trace-source suite2p to fall back to suite2p F.npy/Fneu.npy."
            )
        f_raw, fneu = extract_traces_from_corrected_movie(
            movie_path=trace_movie_path,
            stat=stat,
            selected=selected,
            neuropil_inner_radius=args.neuropil_inner_radius,
            neuropil_outer_radius=args.neuropil_outer_radius,
            min_neuropil_pixels=args.min_neuropil_pixels,
        )
        trace_source_used = "motion_corrected_movie"
        neuropil_source = "local_annulus_from_motion_corrected_movie"
    else:
        f_raw = f_all[selected]
        fneu = fneu_all[selected]
        trace_source_used = "manual_or_suite2p_F.npy" if manual_inputs is not None else "suite2p_F.npy"
        neuropil_source = "manual_or_suite2p_Fneu.npy" if manual_inputs is not None else "suite2p_Fneu.npy"

    f_corrected_before_artifact = (f_raw - args.neuropil_coeff * fneu).astype(np.float32)
    artifact_components = np.zeros((f_corrected_before_artifact.shape[1], 0), dtype=np.float32)
    artifact_info = {
        "method": "none",
        "reason": "artifact_regression_disabled",
        "n_components_requested": 0,
        "n_components_used": 0,
    }
    artifact_qc = pd.DataFrame(
        {
            "roi_id": np.arange(1, f_corrected_before_artifact.shape[0] + 1, dtype=int),
            "artifact_r2": np.zeros((f_corrected_before_artifact.shape[0],), dtype=float),
            "artifact_corr_before": np.full((f_corrected_before_artifact.shape[0],), np.nan, dtype=float),
            "artifact_corr_after": np.full((f_corrected_before_artifact.shape[0],), np.nan, dtype=float),
            "artifact_beta_l2": np.zeros((f_corrected_before_artifact.shape[0],), dtype=float),
        }
    )
    if args.artifact_regression != "none":
        if args.trace_source != "motion-corrected" or trace_movie_path is None:
            artifact_info = {
                "method": args.artifact_regression,
                "reason": "artifact_regression_requires_motion_corrected_trace_source",
                "n_components_requested": int(args.artifact_n_components),
                "n_components_used": 0,
            }
        else:
            artifact_components, artifact_info = compute_artifact_components(
                movie_path=trace_movie_path,
                stat=stat,
                selected=selected,
                pad_radius=args.artifact_exclusion_radius,
                grid_rows=args.artifact_grid_rows,
                grid_cols=args.artifact_grid_cols,
                min_pixels=args.artifact_min_pixels,
                n_components=args.artifact_n_components,
            )
            if artifact_components.shape[1] > 0:
                f_corrected, artifact_qc = regress_artifact_components(
                    f_corrected=f_corrected_before_artifact,
                    components=artifact_components,
                )
            else:
                f_corrected = f_corrected_before_artifact.astype(np.float32, copy=True)
    else:
        f_corrected = f_corrected_before_artifact.astype(np.float32, copy=True)

    f0, f0_info = compute_f0(
        f_corrected=f_corrected,
        fps=fps,
        stim_events=stim_events,
        f0_mode=args.f0_mode,
        f0_percentile=args.f0_percentile,
        f0_window_sec=args.f0_window_sec,
        default_baseline_sec=args.default_baseline_sec,
        min_baseline_frames=args.min_baseline_frames,
    )
    dff = compute_dff(f_corrected, f0=f0, eps=args.f0_eps)

    np.save(out_dir / f"{trial.trial_id}_F_raw.npy", f_raw)
    np.save(out_dir / f"{trial.trial_id}_Fneu.npy", fneu)
    np.save(out_dir / f"{trial.trial_id}_F_corrected.npy", f_corrected)
    np.save(out_dir / f"{trial.trial_id}_F0.npy", f0)
    np.save(out_dir / f"{trial.trial_id}_dff.npy", dff)

    roi_table = build_roi_table(
        trial_id=trial.trial_id,
        selected=selected,
        iscell_flag=iscell_flag,
        iscell_prob=iscell_prob,
        stat=stat,
        f_raw=f_raw,
        fneu=fneu,
        f_corrected=f_corrected,
        f0=f0,
        dff=dff,
        artifact_qc=artifact_qc,
    )
    roi_table.to_csv(out_dir / f"{trial.trial_id}_roi_table.csv", index=False)
    write_dff_traces_csv(out_dir / f"{trial.trial_id}_dff_traces.csv", dff=dff, fps=fps)
    if artifact_components.shape[1] > 0:
        pd.DataFrame(
            artifact_components,
            columns=[f"artifact_component_{i + 1:02d}" for i in range(artifact_components.shape[1])],
        ).assign(frame=np.arange(artifact_components.shape[0], dtype=int), time_sec=np.arange(artifact_components.shape[0], dtype=float) / float(fps)).to_csv(
            out_dir / f"{trial.trial_id}_artifact_components.csv",
            index=False,
        )

    f0_before_artifact, _ = compute_f0(
        f_corrected=f_corrected_before_artifact,
        fps=fps,
        stim_events=stim_events,
        f0_mode=args.f0_mode,
        f0_percentile=args.f0_percentile,
        f0_window_sec=args.f0_window_sec,
        default_baseline_sec=args.default_baseline_sec,
        min_baseline_frames=args.min_baseline_frames,
    )
    dff_before_artifact = compute_dff(f_corrected_before_artifact, f0=f0_before_artifact, eps=args.f0_eps)

    summary = {
        "trial_id": trial.trial_id,
        "status": "ok",
        "n_suite2p_roi_total": int(suite2p_f_all.shape[0]),
        "n_roi_total": int(len(stat)),
        "n_roi_selected": int(len(selected)),
        "n_frames": int(dff.shape[1]),
        "fps": float(fps),
        "duration_sec": float(dff.shape[1] / fps),
        "include_noncell": bool(args.include_noncell),
        "roi_source_requested": args.roi_source,
        "roi_source_used": roi_source_used,
        "roi_source_path": roi_source_path,
        "trace_source": trace_source_used,
        "trace_movie_path": str(trace_movie_path) if trace_movie_path is not None else None,
        "neuropil_source": neuropil_source,
        "neuropil_coeff": float(args.neuropil_coeff),
        "artifact_regression": args.artifact_regression,
        "artifact_n_components": int(args.artifact_n_components),
        "artifact_grid_rows": int(args.artifact_grid_rows),
        "artifact_grid_cols": int(args.artifact_grid_cols),
        "artifact_exclusion_radius": int(args.artifact_exclusion_radius),
        "artifact_min_pixels": int(args.artifact_min_pixels),
        "artifact_method_used": artifact_info.get("method"),
        "artifact_reason": artifact_info.get("reason"),
        "artifact_components_used": int(artifact_info.get("n_components_used", 0)),
        "artifact_tiles_kept": int(artifact_info.get("n_tiles_kept", 0)),
        "artifact_nonroi_pixels": int(artifact_info.get("n_nonroi_pixels", 0)),
        "mean_artifact_r2": float(pd.to_numeric(artifact_qc["artifact_r2"], errors="coerce").mean()),
        "median_artifact_r2": float(pd.to_numeric(artifact_qc["artifact_r2"], errors="coerce").median()),
        "mean_artifact_corr_before": float(pd.to_numeric(artifact_qc["artifact_corr_before"], errors="coerce").mean()),
        "mean_artifact_corr_after": float(pd.to_numeric(artifact_qc["artifact_corr_after"], errors="coerce").mean()),
        "f0_eps": float(args.f0_eps),
        "mean_dff": float(np.nanmean(dff)),
        "max_dff": float(np.nanmax(dff)),
        "mean_snr_like": float(pd.to_numeric(roi_table["snr_like"], errors="coerce").mean()),
        "metadata_path": str(trial.metadata_path) if trial.metadata_path else None,
        "stim_events_path": str(trial.stim_events_path) if trial.stim_events_path else None,
        "suite2p_plane0": str(trial.plane0_dir),
        "manual_root": str(args.manual_root),
        **f0_info,
    }
    pd.DataFrame([summary]).to_csv(out_dir / f"{trial.trial_id}_dff_summary.csv", index=False)

    write_qc_plots(
        out_dir=out_dir,
        trial_id=trial.trial_id,
        dff=dff,
        roi_table=roi_table,
        fps=fps,
        stim_events=stim_events,
        args=args,
        f_raw=f_raw,
        fneu=fneu,
        f_corrected=f_corrected,
        dff_before_artifact=dff_before_artifact,
        f_corrected_before_artifact=f_corrected_before_artifact,
        artifact_components=artifact_components,
    )

    selected_records = roi_table[
        [
            "roi_id",
            "source_roi_id",
            "roi_source",
            "roi_type",
            "manual_roi_id",
            "suite2p_original_id",
            "previous_suite2p_original_id",
            "stat_index",
        ]
    ].to_dict(orient="records")
    with (out_dir / f"{trial.trial_id}_dff_summary.json").open("w", encoding="utf-8") as handle:
        json.dump(
            {
                **summary,
                "selected_roi_records": selected_records,
                "selected_suite2p_indices": [
                    int(value)
                    for value in roi_table["suite2p_original_id"].tolist()
                    if pd.notna(value) and int(value) >= 0
                ],
            },
            handle,
            indent=2,
        )
    return "processed", summary


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Extract neuropil-corrected dF/F traces from suite2p outputs.")
    parser.add_argument("--data-root", type=Path, required=True, help="Original data root.")
    parser.add_argument("--input-root", type=Path, help="Step-05 suite2p root. Default: OUTPUT_ROOT/05_suite2p_roi_detection.")
    parser.add_argument("--manual-root", type=Path, help="Manual ROI curation root. Default: OUTPUT_ROOT/05e_roi_manual_curation.")
    parser.add_argument("--output-root", type=Path, help="Pipeline output root. Default: DATA_ROOT.")
    parser.add_argument("--trial-id", help="Only process one trial ID, or a comma-separated list of trial IDs.")
    parser.add_argument("--action", choices=("skip", "overwrite"), default="skip", help="Existing-output behavior.")
    parser.add_argument("--dry-run", action="store_true", help="Print work plan without reading suite2p arrays or writing files.")
    parser.add_argument(
        "--roi-source",
        choices=("auto", "manual", "suite2p", "all"),
        default="auto",
        help="ROI selection source. Default auto uses final manual ROI when present, otherwise suite2p iscell.",
    )
    parser.add_argument("--include-noncell", action="store_true", help="Keep all suite2p ROIs instead of only iscell==1.")
    parser.add_argument(
        "--trace-source",
        choices=("motion-corrected", "suite2p"),
        default="motion-corrected",
        help="Trace source. Default: use suite2p ROI shapes but extract F/Fneu from step-03 motion-corrected movies.",
    )
    parser.add_argument(
        "--trace-movie-root",
        type=Path,
        help="Optional root containing motion-corrected movies. Default: DATA_ROOT/03_motion_correct.",
    )
    parser.add_argument("--neuropil-coeff", type=float, default=0.7, help="Coefficient for suite2p Fneu subtraction.")
    parser.add_argument("--neuropil-inner-radius", type=int, default=2, help="Step 06 motion-corrected trace mode: pixels excluded around each ROI before neuropil sampling.")
    parser.add_argument("--neuropil-outer-radius", type=int, default=20, help="Step 06 motion-corrected trace mode: outer neuropil ring radius in pixels.")
    parser.add_argument("--min-neuropil-pixels", type=int, default=50, help="Step 06 motion-corrected trace mode: minimum neuropil pixels before expanding the ring.")
    parser.add_argument(
        "--artifact-regression",
        choices=("none", "nonroi-pca"),
        default="none",
        help="Optional spatially aware artifact regression performed after local neuropil subtraction.",
    )
    parser.add_argument("--artifact-n-components", type=int, default=3, help="Number of non-ROI PCA-like background components, excluding the global median trace.")
    parser.add_argument("--artifact-grid-rows", type=int, default=4, help="Number of rows for non-ROI background tiles.")
    parser.add_argument("--artifact-grid-cols", type=int, default=4, help="Number of columns for non-ROI background tiles.")
    parser.add_argument("--artifact-exclusion-radius", type=int, default=4, help="Pixels dilated around all ROI masks before sampling non-ROI background tiles.")
    parser.add_argument("--artifact-min-pixels", type=int, default=100, help="Minimum non-ROI pixels required to keep one background tile.")
    parser.add_argument(
        "--f0-mode",
        choices=("percentile", "rolling-percentile", "rolling-median", "stim-baseline"),
        default="percentile",
        help="F0 estimation method.",
    )
    parser.add_argument("--f0-percentile", type=float, default=10.0, help="Percentile used by percentile-based F0 modes.")
    parser.add_argument("--f0-window-sec", type=float, default=60.0, help="Rolling F0 window size in seconds.")
    parser.add_argument("--f0-eps", type=float, default=1e-6, help="Minimum denominator for dF/F.")
    parser.add_argument("--default-fps", type=float, default=2.0, help="Fallback fps when metadata and ops are missing.")
    parser.add_argument("--default-baseline-sec", type=float, default=10.0, help="Fallback baseline duration for stim-baseline mode.")
    parser.add_argument("--min-baseline-frames", type=int, default=5, help="Minimum baseline frames for stim-baseline mode.")
    parser.add_argument("--heatmap-max-rois", type=int, default=300, help="Maximum ROIs shown in heatmap; 0 means all.")
    parser.add_argument("--dpi", type=int, default=150, help="Legacy alias for --plot-dpi.")
    parser.add_argument("--plot-level", choices=("none", "basic", "full"), default="basic", help="New step-06 QC figure level.")
    parser.add_argument("--plot-format", choices=("png", "pdf", "both"), default="both", help="New step-06 QC figure format.")
    parser.add_argument("--plot-dpi", type=int, default=None, help="New step-06 QC figure DPI. Defaults to --dpi.")
    parser.add_argument("--refresh-plots", action="store_true", help="Rebuild step-06 QC plots from existing numeric outputs when possible.")
    parser.add_argument("--random-seed", type=int, default=0, help="Seed for choosing one random example trace.")
    parser.add_argument("--verbose", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    configure_logging(args.verbose)
    if args.plot_dpi is None:
        args.plot_dpi = args.dpi

    data_root = args.data_root.expanduser().resolve()
    output_root = args.output_root.expanduser().resolve() if args.output_root else default_output_root(data_root).resolve()
    input_root = args.input_root.expanduser().resolve() if args.input_root else default_input_root(output_root).resolve()
    args.manual_root = args.manual_root.expanduser().resolve() if args.manual_root else default_manual_root(output_root).resolve()
    stim_root = default_stim_root(output_root).resolve()
    out_root = step_output_root(output_root)

    if not input_root.exists():
        if args.dry_run:
            LOGGER.warning("Input root does not exist yet: %s", input_root)
            return 0
        LOGGER.error("Input root does not exist: %s", input_root)
        return 1

    trials = discover_trials(input_root, stim_root)
    if args.trial_id:
        wanted = {item.strip() for item in args.trial_id.split(",") if item.strip()}
        trials = [trial for trial in trials if trial.trial_id in wanted]
    summary = RunSummary(found=len(trials))
    rows: list[dict] = []

    LOGGER.info("Input root : %s", input_root)
    LOGGER.info("Manual root: %s", args.manual_root)
    LOGGER.info("Stim root  : %s", stim_root)
    LOGGER.info("Output root: %s", out_root)
    LOGGER.info("Found %d trial(s) with suite2p F.npy.", len(trials))

    for trial in trials:
        out_dir = trial_output_dir(out_root, trial)
        if required_outputs_done(out_dir, trial.trial_id) and args.action == "skip":
            if args.refresh_plots:
                if args.dry_run:
                    summary.processed += 1
                    LOGGER.info("[dry-run] Would refresh step-06 QC plots for %s -> %s", trial.trial_id, out_dir)
                elif refresh_trial_plots(out_dir, trial.trial_id, args):
                    summary.processed += 1
                    LOGGER.info("[plots] refreshed step-06 QC plots for %s", trial.trial_id)
                else:
                    summary.skipped += 1
                continue
            summary.skipped += 1
            LOGGER.info("[skip] %s", trial.trial_id)
            continue

        if args.dry_run:
            summary.processed += 1
            LOGGER.info("[dry-run] Would extract dF/F from %s -> %s", trial.plane0_dir, out_dir)
            continue

        temp_dir = make_temp_output_dir(out_dir)
        try:
            status, row = process_trial(trial, temp_dir, args)
            if status == "processed":
                install_temp_outputs(temp_dir, out_dir, clean_existing=args.action == "overwrite")
            else:
                shutil.rmtree(temp_dir, ignore_errors=True)
            rows.append(row)
            if status == "processed":
                summary.processed += 1
                LOGGER.info("[ok] %s: n_roi=%s n_frames=%s", trial.trial_id, row.get("n_roi_selected"), row.get("n_frames"))
            elif status == "skipped":
                summary.skipped += 1
                LOGGER.info("[skip] %s: %s", trial.trial_id, row.get("message"))
            else:
                summary.failed += 1
                LOGGER.error("[failed] %s: %s", trial.trial_id, row.get("message"))
        except Exception as exc:
            shutil.rmtree(temp_dir, ignore_errors=True)
            summary.failed += 1
            LOGGER.exception("[failed] %s: %s", trial.trial_id, exc)
            rows.append({"trial_id": trial.trial_id, "status": "failed", "message": str(exc)})

    if rows:
        out_root.mkdir(parents=True, exist_ok=True)
        pd.DataFrame(rows).to_csv(out_root / "dff_summary.csv", index=False)

    LOGGER.info("Summary:")
    LOGGER.info("  found: %d", summary.found)
    LOGGER.info("  processed or would process: %d", summary.processed)
    LOGGER.info("  skipped: %d", summary.skipped)
    LOGGER.info("  failed: %d", summary.failed)
    return 1 if summary.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
